(function(){"use strict";const root=document.getElementById("concept-galaxy-app");if(!root||root.dataset.galaxyReady)return;root.dataset.galaxyReady="1";const T=window.GalaxyThree;const coarse=matchMedia("(pointer: coarse)").matches;const phone=coarse&&Math.min(innerWidth,innerHeight)<820;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;function probeGpu(){try{const strict=document.createElement("canvas");let gl=strict.getContext("webgl2",{failIfMajorPerformanceCaveat:true})||strict.getContext("webgl",{failIfMajorPerformanceCaveat:true});const caveat=!gl;if(!gl){const c=document.createElement("canvas");gl=c.getContext("webgl2")||c.getContext("webgl");}
if(!gl)return{slow:false,renderer:""};const ext=gl.getExtension("WEBGL_debug_renderer_info");const name=String((ext&&gl.getParameter(ext.UNMASKED_RENDERER_WEBGL))||gl.getParameter(gl.RENDERER)||"");try{const lose=gl.getExtension("WEBGL_lose_context");if(lose)lose.loseContext();}catch(_){}
return{slow:caveat||/swiftshader|llvmpipe|softpipe|software|basic render|mesa offscreen/i.test(name),renderer:name};}catch(_){return{slow:false,renderer:""};}}
const qualityParam=new URLSearchParams(location.search).get("quality");const gpu=qualityParam==="full"?{slow:false,renderer:""}:qualityParam==="lite"?{slow:true,renderer:"forced"}:probeGpu();let lite=gpu.slow;let DPR=lite?1:Math.min(window.devicePixelRatio||1,phone?1.5:2);const LEVEL_NAMES=["Unknown","Partial","Clear","Mastered"];const LIT=[0.34,0.6,0.86,1];const esc=s=>String(s).replace(/[&<>"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));function hash01(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0)/4294967296;}
function seeded(seed){let a=seed>>>0||1;return()=>{a=(a*16807)%2147483647;return a/2147483647;};}
function gaussOf(r){return()=>{let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);};}
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));function galaxyProgressKey(id){let s=String(id||"").split("#")[0].split("?")[0].replace(/\\/g,"/").toLowerCase();const k=s.indexOf("year-");if(k>0)s=s.slice(k);return s.replace(/^\/+/,"").replace(/\/+$/,"").replace(/\.(html?|md)$/,"").replace(/\/index$/,"");}
function galaxyProgressRecords(CM,account){let local=null,ledger=null;try{local=CM&&typeof CM._readAll==="function"?CM._readAll():null;}catch(_){local=null;}
try{ledger=account&&typeof account.getMasteryMap==="function"?account.getMasteryMap():null;}catch(_){ledger=null;}
if(!local&&!ledger)return null;const norm=rec=>{try{return rec&&typeof rec==="object"?(CM&&typeof CM._normaliseRecord==="function"?CM._normaliseRecord(rec):rec):null;}catch(_){return null;}};const isRated=m=>m===0||m===1||m===2||m===3;const out=new Map();for(const[id,rec]of Object.entries(local||{})){const key=galaxyProgressKey(id),r=norm(rec);if(key&&r)out.set(key,r);}
for(const[id,rec]of Object.entries(ledger||{})){const key=galaxyProgressKey(id),r=norm(rec);if(!key||!r)continue;const prev=out.get(key);if(!prev){out.set(key,r);continue;}
const clearedLater=prev.m==null&&(Number(prev.ratingClearedAt)||0)>(Number(r.lastReviewed)||0);out.set(key,Object.assign({},prev,isRated(r.m)&&!clearedLater?{m:r.m,lastReviewed:r.lastReviewed}:{},{visited:!!(prev.visited||r.visited)}));}
return out;}
function galaxyNodeState(rec){const m=rec&&typeof rec.m==="number"?rec.m:null;if(m===0||m===1||m===2||m===3)return m>=2?3:2;return rec&&rec.visited?1:0;}
function galaxyFlowPairs(pairs,level){const step=level>=2?4:level>=1?2:1;return step===1?pairs:pairs.filter((p,i)=>i%step===0);}
root.innerHTML=`
    <canvas class="mk-galaxy__sky" aria-label="Three-dimensional map of the wiki: courses are galaxies, lectures and weeks are star clusters, concepts are stars."></canvas>
    <div class="mk-galaxy__labels" aria-hidden="true"></div>
    <p class="mk-galaxy__status" role="status">Charting the concepts…</p>
    <div class="mk-galaxy__top">
      <div class="mk-galaxy__brand">
        <h2>Concept <em>Galaxy</em></h2>
        <p data-galaxy-summary>BSc EOR Wiki</p>
      </div>
      <div class="mk-galaxy__tools">
        <div class="mk-galaxy__search">
          <input id="mk-galaxy-q" type="search" placeholder="Find a concept…" autocomplete="off" spellcheck="false" aria-label="Find a concept in the galaxy">
          <div class="mk-galaxy__hits mk-galaxy__glass" hidden></div>
        </div>
        <button type="button" class="mk-galaxy__btn" data-act="home">Overview</button>
        <button type="button" class="mk-galaxy__btn" data-act="progress" aria-pressed="true"><span class="mk-galaxy__led"></span>Progress</button>
        <button type="button" class="mk-galaxy__btn" data-act="glow" aria-pressed="true"><span class="mk-galaxy__led"></span>Glow</button>
        <button type="button" class="mk-galaxy__btn" data-act="drift" aria-pressed="true"><span class="mk-galaxy__led"></span>Drift</button>
        <button type="button" class="mk-galaxy__btn mk-galaxy__close" data-act="close" aria-label="Close the galaxy" title="Close">×</button>
      </div>
    </div>
    <nav class="mk-galaxy__legend mk-galaxy__glass" aria-label="Courses"><h3>Galaxies <span>explored</span></h3></nav>
    <aside class="mk-galaxy__info mk-galaxy__glass" hidden aria-live="polite"></aside>
    <p class="mk-galaxy__hint" aria-hidden="true">${coarse ? "Drag to orbit · Pinch to zoom · Tap a star" : "Drag to orbit · Scroll to zoom · Right-drag to pan · Click a star"}</p>`;const $=s=>root.querySelector(s);if(lite)root.dataset.galaxyQuality="lite";const statusEl=$(".mk-galaxy__status");const fail=msg=>{statusEl.innerHTML=msg;statusEl.classList.add("is-error");};function closeGalaxy(){let sameSite=false;try{sameSite=!!document.referrer&&new URL(document.referrer).origin===location.origin&&history.length>1;}catch(_){}
if(sameSite)history.back();else location.href=new URL("index.html",document.baseURI).href;}
root.querySelector('[data-act="close"]').addEventListener("click",closeGalaxy);document.querySelectorAll('meta[name="theme-color"]').forEach(m=>m.setAttribute("content","#04050a"));if(!T){fail('The 3D engine did not load. <a href="find.html">Open Concept Finder</a> instead.');return;}
fetch(root.dataset.galaxySrc||"assets/concept-galaxy.json",{cache:"no-cache"}).then(r=>{if(!r.ok)throw new Error(r.status);return r.json();}).then(start).catch(()=>fail('The galaxy map could not be loaded. Reload the page, or <a href="find.html">open Concept Finder</a>.'));function start(D){const courses=D.courses.map((c,i)=>({...c,i,color:new T.Color().setHSL(c.hue/360,0.78,0.62),css:`hsl(${c.hue} 78% 66%)`,stars:[],core:[],share:0}));const nodes=D.nodes.map(([id,title,kind,c,u,x,y,z,extra],i)=>({i,id,key:galaxyProgressKey(id),title,kind,c,u,p:new T.Vector3(x,y,z),pre:[],dep:[],rel:[],state:3,enrichment:extra===1}));for(const[a,b]of D.prereq){nodes[b].pre.push(a);nodes[a].dep.push(b);}
for(const[a,b]of D.related){nodes[a].rel.push(b);nodes[b].rel.push(a);}
for(const n of nodes)if(n.kind==="star"){courses[n.c].stars.push(n.i);if(!n.enrichment)courses[n.c].core.push(n.i);}
const N=nodes.length;const sunOf=courses.map(c=>nodes.find(n=>n.kind==="sun"&&n.c===c.i));const stars=nodes.filter(n=>n.kind==="star");const byId=new Map(nodes.map(n=>[n.id,n]));$("[data-galaxy-summary]").textContent=`${courses.length} galaxies · ${stars.length} stars · ${D.prereq.length} prerequisite links`;function nodeColor(n){const h=hash01(n.id);const c=courses[n.c];if(n.kind==="sun")return new T.Color().setHSL(c.hue/360,0.6,0.8);const col=new T.Color().setHSL((c.hue+(h-0.5)*26)/360,0.55+h*0.3,0.55+((h*7)%1)*0.18);if(h>0.9)col.lerp(new T.Color(0.85,0.9,1),0.55);else if(h<0.08)col.lerp(new T.Color(1,0.75,0.45),0.45);if(n.enrichment)col.lerp(new T.Color(0.62,0.64,0.7),0.55).multiplyScalar(0.75);return col;}
function nodeSize(n){if(n.kind==="sun")return 80;return 11+Math.sqrt(n.pre.length+n.dep.length+n.rel.length*0.5)*5.2;}
const designation=n=>{const c=courses[n.c];if(n.kind==="sun")return`${c.code} · course · block ${c.block}`;return`${c.code} · ${n.u >= 0 && c.units[n.u] ? c.units[n.u][0] : "outer halo"}`;};const canvas=$(".mk-galaxy__sky");let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:!phone,powerPreference:"high-performance"});}catch(_){fail('This browser could not start 3D graphics (WebGL). <a href="find.html">Open Concept Finder</a> instead.');return;}
renderer.setPixelRatio(DPR);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;const scene=new T.Scene();const camera=new T.PerspectiveCamera(phone?62:55,1,5,60000);const HOME={base:new T.Vector3(250,3000,5000),pos:new T.Vector3(250,3000,5000),target:new T.Vector3(0,-100,0)};camera.position.set(1400,11000,19000);const controls=new T.OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=0.07;controls.rotateSpeed=0.55;controls.zoomSpeed=0.9;controls.minDistance=35;controls.maxDistance=16000;controls.autoRotateSpeed=0.25;controls.target.copy(HOME.target);const U={uTime:{value:0},uScale:{value:400},uPx:{value:DPR}};const additive=(extra)=>Object.assign({transparent:true,depthWrite:false,depthTest:false,blending:T.AdditiveBlending},extra);const floatAttr=(arr,n)=>new T.Float32BufferAttribute(arr,n);function billboards(items,fragmentShader,uniforms,nearFade){const P=[],C=[],K=[],S=[],Sd=[],R=[];const corners=[[-1,-1],[1,-1],[1,1],[-1,-1],[1,1],[-1,1]];for(const it of items)for(const k of corners){P.push(it.p[0],it.p[1],it.p[2]);C.push(it.c[0],it.c[1],it.c[2]);K.push(k[0],k[1]);S.push(it.s);Sd.push(it.seed||0);R.push(it.rot||0);}
const g=new T.BufferGeometry();g.setAttribute("position",floatAttr(P,3));g.setAttribute("aColor",floatAttr(C,3));g.setAttribute("aCorner",floatAttr(K,2));g.setAttribute("aSize",floatAttr(S,1));g.setAttribute("aSeed",floatAttr(Sd,1));g.setAttribute("aRot",floatAttr(R,1));g.boundingSphere=new T.Sphere(new T.Vector3(),1e7);const m=new T.ShaderMaterial(additive({uniforms:Object.assign({uNear:{value:new T.Vector2(nearFade?nearFade[0]:0,nearFade?nearFade[1]:1)}},U,uniforms),vertexShader:`
          attribute vec3 aColor; attribute vec2 aCorner; attribute float aSize; attribute float aSeed; attribute float aRot;
          uniform vec2 uNear; uniform float uTime;
          varying vec2 vUv; varying vec3 vColor; varying float vSeed; varying float vFade;
          void main() {
            vec4 mv = modelViewMatrix * vec4(position, 1.0);
            float a = aRot; float c = cos(a), s = sin(a);
            mv.xy += mat2(c, s, -s, c) * aCorner * aSize;
            vUv = aCorner; vColor = aColor; vSeed = aSeed;
            vFade = smoothstep(uNear.x, uNear.y, -mv.z);
            gl_Position = projectionMatrix * mv;
          }`,fragmentShader,}));const mesh=new T.Mesh(g,m);mesh.frustumCulled=false;return mesh;}
const NOISE=`
      float gHash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
      float gNoise(vec2 p) { vec2 i = floor(p), f = fract(p); vec2 u = f * f * (3.0 - 2.0 * f);
        return mix(mix(gHash(i), gHash(i + vec2(1.0, 0.0)), u.x), mix(gHash(i + vec2(0.0, 1.0)), gHash(i + vec2(1.0, 1.0)), u.x), u.y); }
      float gFbm(vec2 p) { float v = 0.0, a = 0.5; for (int i = 0; i < ${lite ? 2 : phone ? 3 : 5}; i++) { v += a * gNoise(p); p = p * 2.03 + 17.1; a *= 0.5; } return v; }`;const CLOUD_FRAG=NOISE+`
      uniform float uAlpha; uniform float uTime; varying vec2 vUv; varying vec3 vColor; varying float vSeed; varying float vFade;
      void main() {
        float r = length(vUv); if (r > 1.0) discard;
        float n = gFbm(vUv * 1.7 + vSeed * 37.0 + vec2(uTime * 0.006, 0.0));
        float wisp = gFbm(vUv * 4.1 - vSeed * 11.0);
        float d = pow(n, 2.6) * (0.65 + 0.7 * wisp) * smoothstep(1.0, 0.1, r);
        gl_FragColor = vec4(vColor * d * uAlpha * vFade, 1.0);
      }`;const GLOW_FRAG=`
      uniform float uAlpha; varying vec2 vUv; varying vec3 vColor; varying float vFade;
      void main() {
        vec2 q = vUv; float r = length(q); if (r > 1.0) discard;
        float halo = exp(-r * r * 10.0) * 0.85 + exp(-r * 4.2) * 0.22;
        float spike = exp(-abs(q.x) * 110.0) * exp(-abs(q.y) * 3.4) + exp(-abs(q.y) * 110.0) * exp(-abs(q.x) * 3.4);
        vec2 q2 = mat2(0.7071, -0.7071, 0.7071, 0.7071) * q;
        float spike2 = exp(-abs(q2.x) * 160.0) * exp(-abs(q2.y) * 7.0) + exp(-abs(q2.y) * 160.0) * exp(-abs(q2.x) * 7.0);
        float a = (halo + spike * 0.55 + spike2 * 0.22) * smoothstep(1.0, 0.55, r);
        gl_FragColor = vec4(vColor * a * uAlpha * vFade, 1.0);
      }`;let skyHaze=null;{const M=lite?1400:phone?2600:5200,P=[],C=[],S=[];const r=seeded(11),g1=gaussOf(r);const tilt=new T.Vector3(0.25,1,-0.18).normalize(),ax=new T.Vector3(1,0,0).cross(tilt).normalize(),ay=tilt.clone().cross(ax);for(let i=0;i<M;i++){const band=r()<0.55,R=18000+r()*9000,t=r()*Math.PI*2;let d;if(band){const lat=g1()*0.11;d=ax.clone().multiplyScalar(Math.cos(t)*Math.cos(lat)).addScaledVector(ay,Math.sin(t)*Math.cos(lat)).addScaledVector(tilt,Math.sin(lat));}
else{const u=r()*2-1,s=Math.sqrt(1-u*u);d=new T.Vector3(Math.cos(t)*s,u,Math.sin(t)*s);}
P.push(d.x*R,d.y*R,d.z*R);const w=(band?0.25:0.35)+r()*0.6,tint=r();C.push(w*(tint<0.25?1:0.84),w*0.9,w*(tint>0.7?1.12:0.9));S.push(0.7+Math.pow(r(),3)*2.2);}
const g=new T.BufferGeometry();g.setAttribute("position",floatAttr(P,3));g.setAttribute("aColor",floatAttr(C,3));g.setAttribute("aSize",floatAttr(S,1));const pts=new T.Points(g,new T.ShaderMaterial(additive({uniforms:U,vertexShader:`attribute vec3 aColor; attribute float aSize; uniform float uPx; varying vec3 vColor;
          void main() { vColor = aColor; gl_PointSize = aSize * uPx; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }`,fragmentShader:`varying vec3 vColor; void main() { vec2 q = gl_PointCoord * 2.0 - 1.0; float d = dot(q, q); if (d > 1.0) discard; gl_FragColor = vec4(vColor * (1.0 - d) * 0.5, 1.0); }`,})));pts.frustumCulled=false;scene.add(pts);const haze=[];const hues=[[0.32,0.18,0.5],[0.12,0.28,0.42],[0.42,0.2,0.3],[0.16,0.22,0.45]];for(let k=0;k<9;k++){const t=k/9*Math.PI*2+r()*0.4,R=21000;const d=ax.clone().multiplyScalar(Math.cos(t)).addScaledVector(ay,Math.sin(t)).addScaledVector(tilt,g1()*0.06);haze.push({p:[d.x*R,d.y*R,d.z*R],c:hues[k%hues.length],s:6500+r()*4000,seed:r(),rot:r()*6.28});}
skyHaze=billboards(haze,CLOUD_FRAG,{uAlpha:{value:0.32}});scene.add(skyHaze);}
const galaxyGlow=courses.map(()=>({value:1}));const nebulaMeshes=[],dustMeshes=[];courses.forEach((c)=>{const f=c.frame,O=c.centre,r=seeded(1+Math.floor(hash01(c.id)*1e6)),g1=gaussOf(r);const local=(x,y,h)=>[O[0]+f[0]*x+f[3]*y+f[6]*h,O[1]+f[1]*x+f[4]*y+f[7]*h,O[2]+f[2]*x+f[5]*y+f[8]*h];const armPoint=(t,arm,j)=>{const ang=f[9]+arm*Math.PI+t*1.8*Math.PI,rad=40+t*300;return[Math.cos(ang)*rad+g1()*j,Math.sin(ang)*rad+g1()*j];};const clouds=[{p:local(0,0,0),c:c.color.clone().lerp(new T.Color(1,0.95,0.85),0.45).multiplyScalar(0.42).toArray(),s:330,seed:r(),rot:r()*6.28}];const nCloud=lite?10:phone?16:30;for(let k=0;k<nCloud;k++){const t=0.08+(k/nCloud)*1.05,[x,y]=armPoint(t,k%2,30);const col=c.color.clone().offsetHSL((r()-0.5)*0.06,0,0).multiplyScalar(0.55+r()*0.3);clouds.push({p:local(x,y,g1()*8),c:col.toArray(),s:120+r()*130,seed:r(),rot:r()*6.28});if(r()<0.35)clouds.push({p:local(x+g1()*20,y+g1()*20,0),c:[0.75,0.25,0.45],s:40+r()*40,seed:r(),rot:r()*6.28});}
const neb=billboards(clouds,CLOUD_FRAG,{uAlpha:{value:0.36},uGlow:galaxyGlow[c.i]},[380,1400]);neb.material.fragmentShader=neb.material.fragmentShader.replace("uniform float uAlpha;","uniform float uAlpha; uniform float uGlow;").replace("uAlpha * vFade","uAlpha * uGlow * vFade");nebulaMeshes.push(neb);scene.add(neb);const per=lite?200:phone?300:650,P=[],C=[],S=[];for(let k=0;k<per;k++){const bulge=k<per*0.2;let p;if(bulge)p=local(g1()*48,g1()*48,g1()*28);else{const[x,y]=armPoint(Math.pow(r(),0.8)*1.2,k%2,10+r()*26);p=local(x,y,g1()*7);}
P.push(...p);const hot=r()<0.18;const col=c.color.clone().lerp(hot?new T.Color(0.8,0.88,1):new T.Color(1,0.96,0.88),bulge?0.6:0.2+r()*0.35).multiplyScalar(bulge?0.5:0.55);C.push(col.r,col.g,col.b);S.push(2.2+Math.pow(r(),2)*4.8);}
const g=new T.BufferGeometry();g.setAttribute("position",floatAttr(P,3));g.setAttribute("aColor",floatAttr(C,3));g.setAttribute("aSize",floatAttr(S,1));const dust=new T.Points(g,new T.ShaderMaterial(additive({uniforms:Object.assign({uGlow:galaxyGlow[c.i]},U),vertexShader:`attribute vec3 aColor; attribute float aSize; uniform float uScale; varying vec3 vColor;
          void main() { vec4 mv = modelViewMatrix * vec4(position, 1.0); vColor = aColor; gl_PointSize = clamp(aSize * uScale / -mv.z, 1.0, 9.0); gl_Position = projectionMatrix * mv; }`,fragmentShader:`uniform float uGlow; varying vec3 vColor; void main() { vec2 q = gl_PointCoord * 2.0 - 1.0; float d = dot(q, q); if (d > 1.0) discard; gl_FragColor = vec4(vColor * (1.0 - d) * uGlow, 1.0); }`,})));dustMeshes.push(dust);scene.add(dust);});const pos=new Float32Array(N*3),col=new Float32Array(N*3),size=new Float32Array(N),phase=new Float32Array(N);const dim=new Float32Array(N).fill(0),dimTarget=new Float32Array(N).fill(1);nodes.forEach((n,i)=>{n.p.toArray(pos,i*3);n.color=nodeColor(n);n.color.toArray(col,i*3);n.size=nodeSize(n);size[i]=n.size;phase[i]=hash01(n.id+"#");n.css="#"+n.color.getHexString(T.SRGBColorSpace);});const starGeo=new T.BufferGeometry();starGeo.setAttribute("position",new T.BufferAttribute(pos,3));starGeo.setAttribute("aColor",new T.BufferAttribute(col,3));starGeo.setAttribute("aSize",new T.BufferAttribute(size,1));starGeo.setAttribute("aPhase",new T.BufferAttribute(phase,1));const dimAttr=new T.BufferAttribute(dim,1);dimAttr.setUsage(T.DynamicDrawUsage);starGeo.setAttribute("aDim",dimAttr);const starPoints=new T.Points(starGeo,new T.ShaderMaterial(additive({uniforms:U,vertexShader:`
        attribute vec3 aColor; attribute float aSize; attribute float aPhase; attribute float aDim;
        uniform float uTime; uniform float uScale; varying vec3 vColor; varying float vDim;
        void main() {
          vec4 mv = modelViewMatrix * vec4(position, 1.0);
          float tw = 1.0 + 0.1 * sin(uTime * 1.6 + aPhase * 6.2831);
          gl_PointSize = clamp(aSize * (0.55 + 0.45 * aDim) * uScale / -mv.z * tw, 2.0, 420.0);
          vColor = aColor; vDim = aDim;
          gl_Position = projectionMatrix * mv;
        }`,fragmentShader:`
        varying vec3 vColor; varying float vDim;
        void main() {
          vec2 q = gl_PointCoord * 2.0 - 1.0; float d = dot(q, q); if (d > 1.0) discard;
          float halo = exp(-d * 6.0) * (1.0 - d), core = exp(-d * 42.0);
          vec3 c = vColor * halo * 0.95 + vec3(1.0, 0.98, 0.94) * core * 1.25 * vDim;
          gl_FragColor = vec4(c * vDim, 1.0);
        }`,})));starPoints.frustumCulled=false;scene.add(starPoints);const glowItems=nodes.filter(n=>n.kind==="sun").map(n=>({p:n.p.toArray(),c:n.color.clone().multiplyScalar(0.36).toArray(),s:170,rot:hash01(n.id)*0.6}));scene.add(billboards(glowItems,GLOW_FRAG,{uAlpha:{value:1}},[40,160]));const ringMat=new T.ShaderMaterial(additive({uniforms:Object.assign({uCenter:{value:new T.Vector3()},uSize:{value:30},uColor:{value:new T.Color(1,1,1)},uOn:{value:0}},U),vertexShader:`attribute vec2 aCorner; uniform vec3 uCenter; uniform float uSize; varying vec2 vUv;
        void main() { vec4 mv = modelViewMatrix * vec4(uCenter, 1.0); mv.xy += aCorner * uSize; vUv = aCorner; gl_Position = projectionMatrix * mv; }`,fragmentShader:`uniform float uTime; uniform vec3 uColor; uniform float uOn; varying vec2 vUv;
        void main() {
          float r = length(vUv); if (r > 1.0) discard;
          float pulse = fract(uTime * 0.45);
          float ring = exp(-pow((r - 0.42) / 0.035, 2.0)) * 0.9 + exp(-pow((r - (0.42 + pulse * 0.5)) / 0.05, 2.0)) * (1.0 - pulse) * 0.55;
          float spike = (exp(-abs(vUv.x) * 140.0) * exp(-abs(vUv.y) * 4.0) + exp(-abs(vUv.y) * 140.0) * exp(-abs(vUv.x) * 4.0)) * 0.6;
          gl_FragColor = vec4(uColor * (ring + spike) * uOn, 1.0);
        }`,}));{const g=new T.BufferGeometry();g.setAttribute("position",floatAttr(new Array(18).fill(0),3));g.setAttribute("aCorner",floatAttr([-1,-1,1,-1,1,1,-1,-1,1,1,-1,1],2));const ring=new T.Mesh(g,ringMat);ring.frustumCulled=false;scene.add(ring);}
function ctrlPoint(a,b){if(nodes[a].c===nodes[b].c)return nodes[a].p.clone().add(nodes[b].p).multiplyScalar(0.5);const A=nodes[a].p,B=nodes[b].p,len=A.distanceTo(B),mid=A.clone().add(B).multiplyScalar(0.5);const out=mid.clone().setY(0);if(out.lengthSq()>1)out.normalize();return mid.addScaledVector(out,len*0.12).add(new T.Vector3(0,len*0.28,0));}
const bez=(A,Cp,B,t,out)=>out.set(0,0,0).addScaledVector(A,(1-t)*(1-t)).addScaledVector(Cp,2*t*(1-t)).addScaledVector(B,t*t);const GOLD=new T.Color(1,0.82,0.5);function buildLines(pairs,strength,opts={}){let count=0;for(const[a,b]of pairs)count+=nodes[a].c!==nodes[b].c?18:1;const P=new Float32Array(count*6),C=new Float32Array(count*6),t1=new T.Vector3(),t2=new T.Vector3();const ca=new T.Color(),cb=new T.Color();let o=0;for(const[a,b]of pairs){const A=nodes[a].p,B=nodes[b].p,cross=nodes[a].c!==nodes[b].c,Cp=ctrlPoint(a,b),seg=cross?18:1;const lit=opts.progress&&progressOn&&nodes[a].state>=2&&nodes[b].state>=2;const k=strength*(cross?0.4:1)*(opts.progress&&progressOn?(lit?1.25:0.55):1);ca.copy(nodes[a].color);cb.copy(nodes[b].color);if(lit){ca.lerp(GOLD,0.45);cb.lerp(GOLD,0.45);}
for(let s=0;s<seg;s++){const u0=s/seg,u1=(s+1)/seg;bez(A,Cp,B,u0,t1);bez(A,Cp,B,u1,t2);P[o]=t1.x;P[o+1]=t1.y;P[o+2]=t1.z;P[o+3]=t2.x;P[o+4]=t2.y;P[o+5]=t2.z;const k0=k*(0.45+0.55*u0),k1=k*(0.45+0.55*u1);C[o]=(ca.r+(cb.r-ca.r)*u0)*k0;C[o+1]=(ca.g+(cb.g-ca.g)*u0)*k0;C[o+2]=(ca.b+(cb.b-ca.b)*u0)*k0;C[o+3]=(ca.r+(cb.r-ca.r)*u1)*k1;C[o+4]=(ca.g+(cb.g-ca.g)*u1)*k1;C[o+5]=(ca.b+(cb.b-ca.b)*u1)*k1;o+=6;}}
const g=new T.BufferGeometry();g.setAttribute("position",new T.BufferAttribute(P,3));g.setAttribute("color",new T.BufferAttribute(C,3));return g;}
const lineMat=o=>new T.LineBasicMaterial(additive({vertexColors:true,opacity:o}));const BASE_OPACITY={prereq:0.24,related:0.08};const prereqLines=new T.LineSegments(new T.BufferGeometry(),lineMat(BASE_OPACITY.prereq));const relatedLines=new T.LineSegments(buildLines(D.related,0.7),lineMat(BASE_OPACITY.related));const focusLines=new T.LineSegments(new T.BufferGeometry(),lineMat(0.9));[prereqLines,relatedLines,focusLines].forEach(l=>{l.frustumCulled=false;scene.add(l);});function flowMaterial(alpha){return new T.ShaderMaterial(additive({uniforms:Object.assign({uAlpha:{value:alpha}},U),vertexShader:`
          attribute vec3 aA; attribute vec3 aB; attribute vec3 aC; attribute vec3 aColor; attribute float aOff; attribute float aSpeed; attribute float aSize;
          uniform float uTime; uniform float uScale; varying vec3 vColor; varying float vFade;
          void main() {
            float t = fract(uTime * aSpeed + aOff);
            vec3 p = (1.0 - t) * (1.0 - t) * aA + 2.0 * t * (1.0 - t) * aC + t * t * aB;
            vec4 mv = modelViewMatrix * vec4(p, 1.0);
            gl_PointSize = clamp(aSize * uScale / -mv.z, 1.5, 40.0);
            vFade = sin(t * 3.14159); vColor = aColor;
            gl_Position = projectionMatrix * mv;
          }`,fragmentShader:`
          uniform float uAlpha; varying vec3 vColor; varying float vFade;
          void main() { vec2 q = gl_PointCoord * 2.0 - 1.0; float d = dot(q, q); if (d > 1.0) discard;
            gl_FragColor = vec4((vColor * 0.8 + 0.35) * exp(-d * 4.0) * vFade * uAlpha, 1.0); }`,}));}
function buildFlow(pairs,perEdge,sz,speedK){const A=[],B=[],Cc=[],Col=[],Off=[],Sp=[],Sz=[];for(const[a,b]of pairs){const cp=ctrlPoint(a,b),len=nodes[a].p.distanceTo(nodes[b].p);for(let k=0;k<perEdge;k++){A.push(...nodes[a].p.toArray());B.push(...nodes[b].p.toArray());Cc.push(...cp.toArray());Col.push(...nodes[b].color.toArray());Off.push(k/perEdge+hash01(nodes[a].id+nodes[b].id)*0.5);Sp.push(speedK*70/Math.max(60,len));Sz.push(sz);}}
const g=new T.BufferGeometry();g.setAttribute("position",floatAttr(A,3));g.setAttribute("aA",floatAttr(A,3));g.setAttribute("aB",floatAttr(B,3));g.setAttribute("aC",floatAttr(Cc,3));g.setAttribute("aColor",floatAttr(Col,3));g.setAttribute("aOff",floatAttr(Off,1));g.setAttribute("aSpeed",floatAttr(Sp,1));g.setAttribute("aSize",floatAttr(Sz,1));return g;}
const flowAll=new T.Points(buildFlow(D.prereq,1,7,0.55),flowMaterial(1));const flowFocus=new T.Points(new T.BufferGeometry(),flowMaterial(1.4));[flowAll,flowFocus].forEach(p=>{p.frustumCulled=false;scene.add(p);});const composer=new T.EffectComposer(renderer);composer.addPass(new T.RenderPass(scene,camera));const bloom=new T.UnrealBloomPass(new T.Vector2(256,256),phone?0.5:0.62,0.5,0.2);composer.addPass(bloom);composer.addPass(new T.ShaderPass({uniforms:{tDiffuse:{value:null}},vertexShader:"varying vec2 vUv; void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }",fragmentShader:`uniform sampler2D tDiffuse; varying vec2 vUv;
        void main() { vec4 c = texture2D(tDiffuse, vUv); vec2 d = (vUv - 0.5) * vec2(1.15, 1.0);
          c.rgb *= mix(0.5, 1.0, smoothstep(0.78, 0.2, length(d))); gl_FragColor = c; }`,}));composer.addPass(new T.OutputPass());if(lite)bloom.enabled=false;let sizeKey="",resizeQueued=0,dirty=true;function resize(){const w=Math.max(1,root.clientWidth),h=Math.max(1,root.clientHeight);if(sizeKey===w+"x"+h)return;sizeKey=w+"x"+h;renderer.setSize(w,h,false);composer.setPixelRatio(DPR);composer.setSize(w,h);bloom.setSize(Math.round(w*DPR*(phone?0.5:1)),Math.round(h*DPR*(phone?0.5:1)));camera.aspect=w/h;camera.updateProjectionMatrix();HOME.pos.copy(HOME.base).multiplyScalar(Math.max(1,Math.pow(1.45/camera.aspect,0.85)));HOME.target.set(0,-100,0);const portrait=camera.aspect<0.85;setCameraUp(portrait?ringAxis:WORLD_UP);if(portrait)portraitHome();U.uScale.value=(h*DPR)/(2*Math.tan(T.MathUtils.degToRad(camera.fov)/2));viewShift();dirty=true;}
const WORLD_UP=new T.Vector3(0,1,0);const ringCentre=new T.Vector3(),ringAxis=new T.Vector3(1,0,0),ringSide=new T.Vector3(0,0,1);{courses.forEach(c=>ringCentre.add(new T.Vector3(c.centre[0],c.centre[1],c.centre[2])));ringCentre.divideScalar(Math.max(1,courses.length));let xx=0,zz=0,xz=0;courses.forEach(c=>{const dx=c.centre[0]-ringCentre.x,dz=c.centre[2]-ringCentre.z;xx+=dx*dx;zz+=dz*dz;xz+=dx*dz;});const ang=0.5*Math.atan2(2*xz,xx-zz);ringAxis.set(Math.cos(ang),0,Math.sin(ang));ringSide.copy(ringAxis).cross(WORLD_UP).normalize();if(ringSide.dot(HOME.base)<0)ringSide.negate();}
function setCameraUp(up){if(camera.up.distanceToSquared(up)<1e-9)return;camera.up.copy(up);if(controls._quat&&controls._quatInverse){controls._quat.setFromUnitVectors(camera.up,WORLD_UP);controls._quatInverse.copy(controls._quat).invert();}
camera.lookAt(controls.target);controls.update();}
const portraitProbe=new T.PerspectiveCamera();function portraitHome(){const elev=T.MathUtils.degToRad(34);const dir=ringSide.clone().multiplyScalar(Math.cos(elev)).addScaledVector(WORLD_UP,Math.sin(elev)).normalize();const pts=[];for(const c of courses)for(const[dx,dy,dz]of[[320,0,0],[-320,0,0],[0,0,320],[0,0,-320],[0,200,0],[0,-200,0]])pts.push(new T.Vector3(c.centre[0]+dx,c.centre[1]+dy,c.centre[2]+dz));portraitProbe.fov=camera.fov;portraitProbe.aspect=camera.aspect;portraitProbe.near=camera.near;portraitProbe.far=camera.far;portraitProbe.up.copy(ringAxis);portraitProbe.updateProjectionMatrix();const v2=new T.Vector3();const fits=d=>{portraitProbe.position.copy(ringCentre).addScaledVector(dir,d);portraitProbe.lookAt(ringCentre);portraitProbe.updateMatrixWorld();return pts.every(p=>{v2.copy(p).project(portraitProbe);return v2.z<1&&Math.abs(v2.x)<=0.94&&v2.y<=0.74&&v2.y>=-0.82;});};let d=2500;while(!fits(d)&&d<40000)d*=1.04;HOME.pos.copy(ringCentre).addScaledVector(dir,d);HOME.target.copy(ringCentre);}
const queueResize=()=>{if(!resizeQueued)resizeQueued=requestAnimationFrame(()=>{resizeQueued=0;resize();});};addEventListener("resize",queueResize);if(window.ResizeObserver)new ResizeObserver(queueResize).observe(root);let progressOn=true,progressAvailable=false;function readProgress(){const CM=window.ConceptMastery;if(!CM||typeof CM._readAll!=="function")return false;const records=galaxyProgressRecords(CM,window.MkAccountData);if(!records)return false;for(const n of stars){const rec=records.get(n.key)||null;n.state=galaxyNodeState(rec);n.m=n.state>=2?rec.m:null;}
return true;}
function applyProgress(){for(const c of courses){const explored=c.core.filter(i=>nodes[i].state>=2).length;c.share=c.core.length?explored/c.core.length:0;c.explored=explored;galaxyGlow[c.i].value=progressOn&&progressAvailable?0.55+0.45*c.share:1;}
prereqLines.geometry.dispose();prereqLines.geometry=buildLines(D.prereq,1,{progress:progressAvailable});dirty=true;refreshFocus();renderLegend();updateCourseLabels();}
function baseDim(n){if(n.kind!=="star"||!progressOn||!progressAvailable)return 1;return LIT[n.state];}
let progressKey=null,progressTimer=0;function syncProgress(){progressTimer=0;progressAvailable=readProgress();progressBtn.hidden=!progressAvailable;const key=progressAvailable+":"+stars.map(n=>n.state+(n.m==null?"":n.m)).join("");if(key===progressKey)return;progressKey=key;applyProgress();}
const queueProgressSync=()=>{clearTimeout(progressTimer);progressTimer=setTimeout(syncProgress,400);};const layer=$(".mk-galaxy__labels");function mkLabel(cls,html){const d=document.createElement("div");d.className="mk-galaxy__lbl "+cls;d.innerHTML=html;d.style.opacity="0";layer.appendChild(d);return d;}
const courseLabels=courses.map(c=>{const d=mkLabel("is-course","");d.style.color=c.css;return d;});function updateCourseLabels(){courses.forEach((c,i)=>{const tail=progressOn&&progressAvailable?` · ${Math.round(c.share * 100)}% explored`:` · ${c.core.length} concepts`;courseLabels[i].innerHTML=`${esc(c.name)}<small>${c.code} · block ${c.block}${tail}</small>`;courseLabels[i]._w=0;courseLabels[i]._h=0;});}
const labelOrder=courses.map((c,i)=>i).sort((a,b)=>courses[b].stars.length-courses[a].stars.length);let chromeRects=null;const chromeChanged=()=>{chromeRects=null;};function chromeObstacles(){if(chromeRects)return chromeRects;const base=layer.getBoundingClientRect();chromeRects=[".mk-galaxy__tools",".mk-galaxy__brand",".mk-galaxy__legend",".mk-galaxy__info"].flatMap(sel=>{const el=root.querySelector(sel);if(!el||el.hidden)return[];const r=el.getBoundingClientRect();return r.width&&r.height?[{x:r.left-base.left-4,y:r.top-base.top-4,w:r.width+8,h:r.height+8}]:[];});return chromeRects;}
const overlaps=(a,b)=>a.x<b.x+b.w&&b.x<a.x+a.w&&a.y<b.y+b.h&&b.y<a.y+a.h;const unitLabels=courses.flatMap(c=>c.units.map(([t,n,x,y,z])=>({d:mkLabel("is-unit",`${esc(t)} · ${n}`),p:new T.Vector3(x,y,z),c:c.i})));const pool=Array.from({length:lite?20:40},()=>mkLabel("is-star",""));const v=new T.Vector3();const scr=new Float32Array(N*3);let W=1,H=1;function updateScreen(){W=root.clientWidth;H=root.clientHeight;for(let i=0;i<N;i++){v.copy(nodes[i].p).project(camera);scr[i*3]=(v.x+1)/2*W;scr[i*3+1]=(1-v.y)/2*H;scr[i*3+2]=v.z<1?camera.position.distanceTo(nodes[i].p):-1;}}
function place(d,x,y,op){if(op<=0.01){if(d.style.opacity!=="0")d.style.opacity="0";return;}
d.style.transform=`translate3d(${x.toFixed(1)}px, ${y.toFixed(1)}px, 0)`;d.style.opacity=op.toFixed(2);}
let hover=-1,selected=-1;function updateLabels(){const taken=[],chrome=chromeObstacles();labelOrder.forEach(i=>{const s=sunOf[i],z=scr[s.i*3+2],d=courseLabels[i];if(z<0)return place(d,0,0,0);const own=selected>=0&&nodes[selected].kind==="sun"&&nodes[selected].c===i;let op=own?0:clamp((z-1000)/900,0,1)*(selected>=0&&nodes[selected].c!==i?0.35:1);if(!d._w){d._w=d.offsetWidth||140;d._h=d.offsetHeight||30;}
const x=clamp(scr[s.i*3]-d._w/2,8,Math.max(8,W-8-d._w));let y=scr[s.i*3+1]+22;if(op>0.01){const step=d._h+6;const spot=[0,step,-step,2*step,-2*step].map(dy=>({x,y:y+dy,w:d._w,h:d._h})).find(r=>r.y>=4&&r.y+r.h<=H-4&&!taken.some(o=>overlaps(o,r))&&!chrome.some(o=>overlaps(o,r)));if(spot)y=spot.y;else op=Math.min(op,0.3);taken.push({x,y,w:d._w,h:d._h});}
place(d,x,y,op);});for(const u of unitLabels){v.copy(u.p).project(camera);const dist=camera.position.distanceTo(u.p);const op=v.z<1?clamp((1150-dist)/400,0,1)*clamp((dist-150)/200,0,1)*(selected>=0?0.25:0.85):0;place(u.d,(v.x+1)/2*W-30,(1-v.y)/2*H-34,op);}
const want=[],seen=new Set();const push=(i,k)=>{if(i<0||seen.has(i)||scr[i*3+2]<0)return;seen.add(i);want.push([i,k]);};push(hover,2);push(selected,3);if(selected>=0){const s=nodes[selected];[...s.pre,...s.dep,...s.rel].slice(0,30).forEach(i=>push(i,1));}
else{const near=[];for(const n of stars){const z=scr[n.i*3+2];if(z>0&&z<340)near.push([z,n.i]);}
near.sort((a,b)=>a[0]-b[0]);near.slice(0,16).forEach(([,i])=>push(i,0));}
pool.forEach((d,k)=>{const w=want[k];if(!w){if(d.style.opacity!=="0")d.style.opacity="0";d._i=-1;return;}
const[i,kind]=w,n=nodes[i];if(d._i!==i){d.textContent=n.title;d._i=i;}
d.classList.toggle("is-sel",kind>=2);d.classList.toggle("is-dim",kind<2&&n.kind==="star"&&progressOn&&progressAvailable&&n.state===0);const z=scr[i*3+2];place(d,scr[i*3]+2,scr[i*3+1]-8,kind>=1?1:clamp((340-z)/120,0,1));});}
let flight=null,idleSince=performance.now();const ease=t=>(t<0.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2);function flyTo(target,dist,dur=1500){const dir=camera.position.clone().sub(controls.target).normalize();if(dir.lengthSq()<0.5)dir.set(0,0.5,1).normalize();flight={t0:performance.now(),dur:reduced?1:dur,fromP:camera.position.clone(),fromT:controls.target.clone(),endP:target.clone().add(dir.multiplyScalar(dist)),endT:target.clone()};}
function flyHome(dur=1800){flight={t0:performance.now(),dur:reduced?1:dur,fromP:camera.position.clone(),fromT:controls.target.clone(),endP:HOME.pos.clone(),endT:HOME.target.clone()};}
function refreshFocus(){const i=selected;for(let k=0;k<N;k++)dimTarget[k]=baseDim(nodes[k]);focusLines.geometry.dispose();flowFocus.geometry.dispose();if(i<0){focusLines.geometry=new T.BufferGeometry();flowFocus.geometry=new T.BufferGeometry();prereqLines.material.opacity=BASE_OPACITY.prereq;relatedLines.material.opacity=BASE_OPACITY.related;flowAll.visible=true;ringMat.uniforms.uOn.value=0;return;}
const n=nodes[i],keep=new Set([i]);if(n.kind==="star")[...n.pre,...n.dep,...n.rel].forEach(k=>keep.add(k));for(let k=0;k<N;k++){const o=nodes[k],b=baseDim(o);if(keep.has(k))dimTarget[k]=Math.max(b,0.75);else if(n.kind==="sun"&&o.c===n.c)dimTarget[k]=b;else if(n.kind==="star"&&o.c===n.c)dimTarget[k]=b*0.35;else dimTarget[k]=b*0.14;}
let pairs=[];if(n.kind==="star")pairs=[...n.pre.map(p=>[p,i]),...n.dep.map(d=>[i,d])];else if(n.kind==="sun")pairs=D.prereq.filter(([a,b])=>nodes[a].c===n.c&&nodes[b].c===n.c);focusLines.geometry=buildLines([...pairs,...(n.kind==="star"?n.rel.map(r=>[i,r]):[])],1);focusLines.material.opacity=n.kind==="star"?0.9:0.32;flowFocus.geometry=buildFlow(pairs,n.kind==="star"?3:1,n.kind==="star"?6:7,0.8);prereqLines.material.opacity=0.05;relatedLines.material.opacity=0.025;flowAll.visible=false;ringMat.uniforms.uCenter.value.copy(n.p);ringMat.uniforms.uSize.value=n.kind==="sun"?190:Math.max(26,n.size*2.2);ringMat.uniforms.uColor.value.copy(n.color).lerp(new T.Color(1,1,1),0.35);ringMat.uniforms.uOn.value=n.kind==="star"?0.8:0.45;}
function setFocus(i){selected=i;dirty=true;refreshFocus();renderInfo();}
function select(i,fly=true){setFocus(i);if(i<0)return;const n=nodes[i];if(fly)flyTo(n.p,n.kind==="sun"?980:430);controls.autoRotate=false;idleSince=performance.now();}
const info=$(".mk-galaxy__info");function viewShift(){chromeChanged();const w=root.clientWidth,h=root.clientHeight;if(phone&&!info.hidden)camera.setViewOffset(w,h,0,Math.min(h*0.3,info.offsetHeight/2+12),w,h);else camera.clearViewOffset();}
function progressChip(n){if(!progressAvailable||n.kind!=="star")return"";const text=n.state===0?"Not visited yet":n.state===1?"Visited · not rated":`Rated · ${LEVEL_NAMES[n.m]}`;return`<span class="mk-galaxy__state" data-state="${n.state}">${text}</span>`+(n.enrichment?`<span class="mk-galaxy__state" data-enrichment="1">Enrichment · not counted in explored</span>`:"");}
function chip(i){const n=nodes[i];const dimmed=progressOn&&progressAvailable&&n.kind==="star"&&n.state===0?" is-dim":"";return`<button class="mk-galaxy__chip${dimmed}" type="button" data-go="${i}"><i style="background:${n.css}"></i>${esc(n.title)}</button>`;}
function chipList(title,list,cap=12){if(!list.length)return"";const more=list.length>cap?`<span class="mk-galaxy__more">and ${list.length - cap} more</span>`:"";return`<section><h4>${title} · ${list.length}</h4><div class="mk-galaxy__chips">${list.slice(0, cap).map(chip).join("")}${more}</div></section>`;}
function renderInfo(){if(selected<0){info.hidden=true;info.innerHTML="";viewShift();return;}
const n=nodes[selected];const tint=courses[n.c].css;let body="";if(n.kind==="star"){body=`<div class="mk-galaxy__stats">${progressChip(n)}<span><b>${n.pre.length}</b> builds on</span><span><b>${n.dep.length}</b> leads to</span><span><b>${n.rel.length}</b> related</span></div>`
+chipList("Builds on",n.pre)+chipList("Leads to",n.dep)+chipList("Related",n.rel,8);}else{const c=courses[n.c];const links=D.prereq.filter(([a,b])=>nodes[a].c===c.i&&nodes[b].c===c.i).length;const bridges=D.prereq.filter(([a,b])=>(nodes[a].c===c.i)!==(nodes[b].c===c.i)).length;const extra=c.stars.length-c.core.length;const explored=(progressAvailable?`<span><b>${c.explored}</b> of ${c.core.length} explored</span>`:`<span><b>${c.core.length}</b> concepts</span>`)
+(extra?`<span><b>${extra}</b> enrichment</span>`:"");body=`<div class="mk-galaxy__stats">${explored}<span><b>${c.units.length}</b> clusters</span><span><b>${links}</b> internal links</span><span><b>${bridges}</b> bridges</span></div>`
+`<section><h4>Clusters</h4><div class="mk-galaxy__chips">${c.units.map(([t, k], u) => `<button class="mk-galaxy__chip" type="button" data-unit="${c.i}:${u}"><i style="background:${c.css}"></i>${esc(t)} · ${k}</button>`).join("")}</div></section>`;}
info.innerHTML=`<div class="mk-galaxy__head">
          <div class="mk-galaxy__desig" style="color:${tint}"><span class="mk-galaxy__sw" style="background:${tint};box-shadow:0 0 8px ${tint}"></span>${esc(designation(n))}</div>
          <a class="mk-galaxy__open" href="${esc(n.id)}">${n.kind === "sun" ? "Course page" : "Open page"}</a>
          <button class="mk-galaxy__x" type="button" aria-label="Close the details" data-close>×</button>
        </div>
        <h3>${esc(n.title)}</h3>${body}`;info.hidden=false;info.scrollTop=0;viewShift();}
info.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.close!=null){setFocus(-1);return;}
if(b.dataset.go)select(+b.dataset.go);if(b.dataset.unit){const[ci,u]=b.dataset.unit.split(":").map(Number),[,,x,y,z]=courses[ci].units[u];flyTo(new T.Vector3(x,y,z),420,1200);}});const legend=$(".mk-galaxy__legend");const legendRows=courses.map(c=>{const b=document.createElement("button");b.type="button";b.title=c.name;b.addEventListener("click",()=>select(sunOf[c.i].i));legend.appendChild(b);return b;});function renderLegend(){chromeChanged();legend.classList.toggle("has-progress",progressOn&&progressAvailable);courses.forEach((c,i)=>{const pct=Math.round(c.share*100);legendRows[i].innerHTML=`<span class="mk-galaxy__sw" style="background:${c.css};box-shadow:0 0 8px ${c.css}"></span><span class="mk-galaxy__code">${c.code}</span><span class="mk-galaxy__name">${esc(c.name)}</span>`
+(progressOn&&progressAvailable?`<span class="mk-galaxy__bar" style="--p:${pct}%;--c:${c.css}"><span></span></span><span class="mk-galaxy__n">${pct}%</span>`:`<span class="mk-galaxy__bar is-empty"></span><span class="mk-galaxy__n">${c.core.length}</span>`);});}
const q=$("#mk-galaxy-q"),hits=$(".mk-galaxy__hits");let hitIdx=[],cursor=0;function runSearch(){const s=q.value.trim().toLowerCase();if(!s){hits.hidden=true;return;}
const scored=[];for(const n of nodes){const t=n.title.toLowerCase(),k=t.indexOf(s);if(k>=0)scored.push([(k===0?0:1)+t.length/200,n.i]);}
scored.sort((a,b)=>a[0]-b[0]);hitIdx=scored.slice(0,8).map(x=>x[1]);cursor=0;hits.innerHTML=hitIdx.length?hitIdx.map((i,k)=>`<button class="mk-galaxy__hit${k === 0 ? " is-on" : ""}" type="button" data-go="${i}">${esc(nodes[i].title)}<small>${esc(designation(nodes[i]))}</small></button>`).join(""):`<div class="mk-galaxy__hit"><small>No concept with that name</small></div>`;hits.hidden=false;}
q.addEventListener("input",runSearch);q.addEventListener("keydown",e=>{if((e.key==="ArrowDown"||e.key==="ArrowUp")&&hitIdx.length){e.preventDefault();cursor=(cursor+(e.key==="ArrowDown"?1:-1)+hitIdx.length)%hitIdx.length;[...hits.children].forEach((h,k)=>h.classList.toggle("is-on",k===cursor));}
if(e.key==="Enter"&&hitIdx.length){select(hitIdx[cursor]);hits.hidden=true;q.blur();}
if(e.key==="Escape"){q.value="";hits.hidden=true;}});hits.addEventListener("click",e=>{const b=e.target.closest("[data-go]");if(b){select(+b.dataset.go);hits.hidden=true;}});root.addEventListener("pointerdown",e=>{if(!e.target.closest(".mk-galaxy__search"))hits.hidden=true;});let drift=!reduced;const btn=act=>$(`[data-act="${act}"]`);const progressBtn=btn("progress");btn("drift").setAttribute("aria-pressed",String(drift));btn("home").addEventListener("click",()=>{setFocus(-1);flyHome();});btn("drift").addEventListener("click",e=>{drift=!drift;e.currentTarget.setAttribute("aria-pressed",String(drift));controls.autoRotate=drift&&selected<0;});btn("glow").setAttribute("aria-pressed",String(bloom.enabled));btn("glow").addEventListener("click",e=>{bloom.enabled=!bloom.enabled;dirty=true;e.currentTarget.setAttribute("aria-pressed",String(bloom.enabled));});progressBtn.addEventListener("click",e=>{progressOn=!progressOn;e.currentTarget.setAttribute("aria-pressed",String(progressOn));progressKey=null;applyProgress();renderInfo();});addEventListener("keydown",e=>{if(e.key!=="Escape"||e.target===q)return;if(selected>=0)setFocus(-1);else closeGalaxy();});function pick(x,y){let best=-1,bestScore=Infinity;for(let i=0;i<N;i++){const z=scr[i*3+2];if(z<0)continue;const dx=scr[i*3]-x,dy=scr[i*3+1]-y,d2=dx*dx+dy*dy;const r=Math.max(coarse?22:13,Math.min(60,nodes[i].size*U.uScale.value/z/DPR*0.3));if(d2>r*r)continue;const score=d2/(r*r)+z/20000;if(score<bestScore){bestScore=score;best=i;}}
return best;}
let down=null;const local=e=>{const r=canvas.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top];};canvas.addEventListener("pointerdown",e=>{down={x:e.clientX,y:e.clientY,t:performance.now()};canvas.classList.add("is-dragging");});addEventListener("pointerup",e=>{canvas.classList.remove("is-dragging");if(!down)return;const moved=Math.hypot(e.clientX-down.x,e.clientY-down.y),dt=performance.now()-down.t;down=null;if(e.target!==canvas||moved>7||dt>600)return;const i=pick(...local(e));if(i>=0)select(i);else if(selected>=0)setFocus(-1);});canvas.addEventListener("pointermove",e=>{if(e.pointerType!=="mouse"||down)return;const i=pick(...local(e));if(i!==hover){hover=i;dirty=true;canvas.classList.toggle("is-pointing",i>=0);}});canvas.addEventListener("pointerleave",()=>{hover=-1;});controls.addEventListener("start",()=>{controls.autoRotate=false;flight=null;idleSince=performance.now();});controls.addEventListener("change",()=>{dirty=true;});controls.addEventListener("end",()=>{idleSince=performance.now();});const clock=new T.Clock();let running=true,started=false,last=0;document.addEventListener("visibilitychange",()=>{running=!document.hidden;dirty=true;if(running){clock.getDelta();requestAnimationFrame(frame);}});let level=lite?2:0,sampleFrom=0,samples=[],onDemand=lite;function degrade(to){if(to<=level)return;level=to;root.dataset.galaxyQuality=to>=2?"lite":"reduced";if(to>=1){bloom.enabled=false;btn("glow").setAttribute("aria-pressed","false");if(DPR>1){DPR=1;U.uPx.value=1;renderer.setPixelRatio(1);sizeKey="";resize();}
if(!gpu.slow){flowAll.geometry.dispose();flowAll.geometry=buildFlow(galaxyFlowPairs(D.prereq,to),1,7,0.55);}}
if(to>=2){if(gpu.slow)onDemand=true;nebulaMeshes.forEach(m=>{m.visible=false;});if(skyHaze)skyHaze.visible=false;}
dirty=true;}
if(lite)degrade(2);const SLOW_FRAME_MS=phone?50:33;function frame(now){if(!running)return;requestAnimationFrame(frame);if(phone&&now-last<24)return;const interval=now-last;last=now;if(started&&level<2&&!document.hidden){if(!sampleFrom)sampleFrom=now+1500;else if(now>sampleFrom&&interval>0&&interval<1000){samples.push(interval);if(samples.length>=30){const mean=samples.reduce((a,b)=>a+b,0)/samples.length;samples=[];sampleFrom=now+1200;if(mean>SLOW_FRAME_MS)degrade(level+1);}}}
const dt=Math.min(clock.getDelta(),0.1);const idle=onDemand&&!flight&&!controls.autoRotate&&!dirty;if(!reduced&&!onDemand)U.uTime.value+=dt;if(flight){const t=Math.min(1,(performance.now()-flight.t0)/flight.dur),k=ease(t);camera.position.lerpVectors(flight.fromP,flight.endP,k);controls.target.lerpVectors(flight.fromT,flight.endT,k);if(t>=1)flight=null;}
if(drift&&!controls.autoRotate&&!flight&&selected<0&&performance.now()-idleSince>14000)controls.autoRotate=true;const moved=controls.update();let changed=false;for(let i=0;i<N;i++){const d=dimTarget[i]-dim[i];if(Math.abs(d)>0.003){dim[i]+=d*Math.min(1,dt*6);changed=true;}}
if(changed)dimAttr.needsUpdate=true;if(idle&&!moved&&!changed&&started)return;dirty=false;composer.render();updateScreen();updateLabels();if(!started){started=true;statusEl.remove();root.classList.add("is-ready");const params=new URLSearchParams(location.search);const target=byId.get(params.get("concept")||"")||byId.get((params.get("course")||"")+"/index.html");if(target){select(target.i);flight.dur=reduced?1:2600;}
else{flyHome(reduced?1:3400);controls.autoRotate=false;}}}
resize();try{renderer.compile(scene,camera);}catch(_){}
renderLegend();syncProgress();if(!progressAvailable){let tries=0;const wait=setInterval(()=>{if(window.ConceptMastery||++tries>40){clearInterval(wait);syncProgress();}},150);}
addEventListener("conceptMasteryChanged",queueProgressSync);["mk-local-activity-change","mk-account-mastery-recovered","mk-account-login-change","mk-account-workspace-changed"].forEach(t=>addEventListener(t,queueProgressSync));addEventListener("storage",e=>{if(!e.key||e.key==="concept_mastery_v1"||e.key==="mk_account_data_file_v1")queueProgressSync();});requestAnimationFrame(frame);window.__mkGalaxy={nodes,courses,select,setFocus,flyHome,camera,controls,syncProgress,quality:()=>({lite,level,onDemand,dpr:DPR,bloom:bloom.enabled,gpu:gpu.renderer})};}})();