(()=>{"use strict";const root=document.documentElement;const STYLE_ID="mk-shop-extras-style-v1";const PROGRESS_ID="mk-shop-reading-progress";const BGM_PLAYER_ID="mk-bgm-player";const BGM_STATE_KEY="mk_bgm_player_state_v1";function ensureStyles(){if(document.getElementById(STYLE_ID))return;const style=document.createElement("style");style.id=STYLE_ID;style.textContent=`
      .mk-shop-fx-layer{position:fixed;inset:0;z-index:2147483500;overflow:hidden;pointer-events:none}
      .mk-shop-fx-particle{position:fixed;left:var(--x);top:var(--y);font-size:var(--size,20px);filter:drop-shadow(0 0 7px var(--glow,#fff));animation:mk-shop-particle .9s ease-out forwards}
      @keyframes mk-shop-particle{to{transform:translate(var(--dx),var(--dy)) rotate(var(--rot,160deg)) scale(.35);opacity:0}}
      #${PROGRESS_ID}{position:fixed;z-index:2147482400;left:0;right:0;top:var(--mk-reading-bar-top,2.4rem);height:8px;pointer-events:none;background:color-mix(in srgb,var(--md-default-fg-color) 14%,var(--md-default-bg-color));box-shadow:0 1px 0 rgba(255,255,255,.42),0 3px 10px rgba(15,23,42,.16);contain:layout style paint}
      #${PROGRESS_ID}>span{display:block;position:relative;width:0;height:100%}
      #${PROGRESS_ID}>span::after{content:"◆";position:absolute;right:-11px;top:50%;display:grid;place-items:center;width:22px;height:22px;transform:translateY(-50%);font:900 15px/1 "Segoe UI Emoji",sans-serif;filter:drop-shadow(0 2px 5px rgba(15,23,42,.35))}
      #${PROGRESS_ID}>b{position:absolute;right:10px;top:12px;padding:.13rem .34rem;border-radius:999px;color:var(--md-default-fg-color);background:color-mix(in srgb,var(--md-default-bg-color) 94%,transparent);border:1px solid color-mix(in srgb,var(--md-default-fg-color) 14%,transparent);box-shadow:0 4px 12px rgba(15,23,42,.14);font:850 10px/1 system-ui}
      #${PROGRESS_ID}>b>input{all:unset;display:block;width:4ch;color:inherit;font:inherit;line-height:inherit;text-align:center;pointer-events:none}
      html[data-mk-reading-progress="reading_lightsaber"] #${PROGRESS_ID}>span{background:#55eaff;box-shadow:0 0 5px #fff,0 0 13px #22d3ee}html[data-mk-reading-progress="reading_lightsaber"] #${PROGRESS_ID}>span::after{content:"💠";animation:mk-reading-marker-pulse 1.3s ease-in-out infinite}
      html[data-mk-reading-progress="reading_liquid_rainbow"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#ff3b7b,#ffb800,#68ff8c,#2edcff,#9d5cff,#ff3b7b);background-size:220% 100%;animation:mk-shop-rainbow 2.4s linear infinite}html[data-mk-reading-progress="reading_liquid_rainbow"] #${PROGRESS_ID}>span::after{content:"🌈";animation:mk-reading-marker-float 1.8s ease-in-out infinite}
      html[data-mk-reading-progress="reading_racing_meter"] #${PROGRESS_ID}>span{background:repeating-linear-gradient(120deg,#ef233c 0 15px,#ffb703 15px 23px,#111 23px 27px);box-shadow:0 0 10px #ef233c}html[data-mk-reading-progress="reading_racing_meter"] #${PROGRESS_ID}>span::after{content:"🏎️";transform:translateY(-50%) scaleX(-1);animation:mk-reading-marker-race .65s ease-in-out infinite}
      html[data-mk-reading-progress="reading_star_trail"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#312e81,#8b5cf6,#f0abfc);box-shadow:8px 0 10px #fff,14px 0 18px #a78bfa}html[data-mk-reading-progress="reading_star_trail"] #${PROGRESS_ID}>span::after{content:"⭐";animation:mk-reading-marker-spin 2.8s linear infinite}
      html[data-mk-reading-progress="reading_crystal_charge"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#0ea5e9,#c4f1ff 48%,#818cf8);clip-path:polygon(0 0,98% 0,100% 50%,98% 100%,0 100%);box-shadow:0 0 13px #60a5fa}html[data-mk-reading-progress="reading_crystal_charge"] #${PROGRESS_ID}>span::after{content:"💎";animation:mk-reading-marker-pulse 1.45s ease-in-out infinite}
      html[data-mk-reading-progress="reading_sakura_runner"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#f9a8d4,#fb7185,#fecdd3);box-shadow:0 0 11px #fb718577}html[data-mk-reading-progress="reading_sakura_runner"] #${PROGRESS_ID}>span::after{content:"🌸";animation:mk-reading-marker-float 1.55s ease-in-out infinite}
      html[data-mk-reading-progress="reading_rocket_route"] #${PROGRESS_ID}>span{background:repeating-linear-gradient(90deg,#312e81 0 18px,#6366f1 18px 34px,#22d3ee 34px 40px);box-shadow:0 0 13px #38bdf8}html[data-mk-reading-progress="reading_rocket_route"] #${PROGRESS_ID}>span::after{content:"🚀";animation:mk-reading-marker-rocket .8s ease-in-out infinite}
      html[data-mk-reading-progress="reading_koi_stream"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#0ea5e9,#67e8f9,#99f6e4);box-shadow:0 2px 10px #06b6d488}html[data-mk-reading-progress="reading_koi_stream"] #${PROGRESS_ID}>span::after{content:"🐟";transform:translateY(-50%) scaleX(-1);animation:mk-reading-marker-swim 1.2s ease-in-out infinite}
      html[data-mk-reading-progress="reading_pixel_quest"] #${PROGRESS_ID}{height:10px;background:#111827}html[data-mk-reading-progress="reading_pixel_quest"] #${PROGRESS_ID}>span{background:repeating-linear-gradient(90deg,#22d3ee 0 10px,#a3e635 10px 20px,#facc15 20px 30px);image-rendering:pixelated}html[data-mk-reading-progress="reading_pixel_quest"] #${PROGRESS_ID}>span::after{content:"👾";animation:mk-reading-marker-pixel .55s steps(2,end) infinite}
      html[data-mk-reading-progress="reading_moon_cycle"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#0f172a,#4338ca,#c4b5fd);box-shadow:0 0 14px #818cf8}html[data-mk-reading-progress="reading_moon_cycle"] #${PROGRESS_ID}>span::after{content:"🌙";animation:mk-reading-marker-moon 2.4s ease-in-out infinite}
      html[data-mk-reading-progress="reading_comet_runner"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#1e1b4b,#7c3aed,#f0abfc);box-shadow:0 0 14px #c084fc}html[data-mk-reading-progress="reading_comet_runner"] #${PROGRESS_ID}>span::after{content:"☄️";animation:mk-reading-marker-comet .78s ease-in-out infinite}
      html[data-mk-reading-progress="reading_paper_plane"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#38bdf8,#bae6fd,#f8fafc);box-shadow:0 0 11px #7dd3fc}html[data-mk-reading-progress="reading_paper_plane"] #${PROGRESS_ID}>span::after{content:"✈️";animation:mk-reading-marker-plane 1.15s ease-in-out infinite}
      html[data-mk-reading-progress="reading_fox_sprint"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#365314,#84cc16,#f59e0b);box-shadow:0 0 11px #f59e0b88}html[data-mk-reading-progress="reading_fox_sprint"] #${PROGRESS_ID}>span::after{content:"🦊";transform:translateY(-50%) scaleX(-1);animation:mk-reading-marker-sprint .62s ease-in-out infinite}
      html[data-mk-reading-progress="reading_dragon_flight"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#450a0a,#dc2626,#fb923c,#fde047);box-shadow:0 0 15px #f97316}html[data-mk-reading-progress="reading_dragon_flight"] #${PROGRESS_ID}>span::after{content:"🐉";transform:translateY(-50%) scaleX(-1);animation:mk-reading-marker-dragon 1.05s ease-in-out infinite}
      html[data-mk-reading-progress="reading_train_route"] #${PROGRESS_ID}{height:9px;background:repeating-linear-gradient(90deg,#334155 0 13px,#94a3b8 13px 16px)}html[data-mk-reading-progress="reading_train_route"] #${PROGRESS_ID}>span{background:linear-gradient(90deg,#0f172a,#2563eb,#e2e8f0);box-shadow:0 0 10px #60a5fa}html[data-mk-reading-progress="reading_train_route"] #${PROGRESS_ID}>span::after{content:"🚄";animation:mk-reading-marker-train .65s ease-in-out infinite}
      @keyframes mk-shop-rainbow{to{background-position:220% 0}}
      @keyframes mk-reading-marker-pulse{50%{transform:translateY(-50%) scale(1.24);filter:drop-shadow(0 0 8px #fff)}}
      @keyframes mk-reading-marker-float{50%{transform:translateY(-72%) rotate(8deg)}}
      @keyframes mk-reading-marker-race{0%,100%{transform:translateY(-50%) scaleX(-1)}50%{transform:translate(3px,-55%) scaleX(-1) rotate(-3deg)}}
      @keyframes mk-reading-marker-spin{to{transform:translateY(-50%) rotate(360deg)}}
      @keyframes mk-reading-marker-rocket{50%{transform:translate(4px,-60%) rotate(-8deg);filter:drop-shadow(-7px 4px 4px #f97316)}}
      @keyframes mk-reading-marker-swim{0%,100%{transform:translateY(-50%) scaleX(-1)}50%{transform:translate(3px,-45%) scaleX(-1) rotate(7deg)}}
      @keyframes mk-reading-marker-pixel{50%{transform:translateY(-58%) scale(1.08)}}
      @keyframes mk-reading-marker-moon{50%{transform:translateY(-50%) rotate(18deg);filter:drop-shadow(0 0 9px #c4b5fd)}}
      @keyframes mk-reading-marker-comet{50%{transform:translate(5px,-57%) rotate(-5deg);filter:drop-shadow(-8px 3px 5px #c084fc)}}
      @keyframes mk-reading-marker-plane{50%{transform:translate(4px,-66%) rotate(-5deg);filter:drop-shadow(-7px 5px 4px #38bdf8)}}
      @keyframes mk-reading-marker-sprint{0%,100%{transform:translateY(-50%) scaleX(-1)}50%{transform:translate(4px,-60%) scaleX(-1) rotate(-3deg)}}
      @keyframes mk-reading-marker-dragon{0%,100%{transform:translateY(-50%) scaleX(-1)}50%{transform:translate(4px,-64%) scaleX(-1) rotate(4deg);filter:drop-shadow(-8px 4px 5px #f97316)}}
      @keyframes mk-reading-marker-train{50%{transform:translate(5px,-54%);filter:drop-shadow(-8px 2px 4px #60a5fa)}}

      :is(.mk-comment-card[data-nameplate-style] .mk-comment-name,html[data-mk-nameplate-style] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style] .mk-account-profile-card .mk-local-profile-name){display:inline-flex;align-items:center;width:max-content;padding:.12rem .42rem;border-radius:999px}
      :is(.mk-comment-card[data-nameplate-style="nameplate_neon_gamer"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_neon_gamer"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_neon_gamer"] .mk-account-profile-card .mk-local-profile-name){color:#d9ffff;background:#10162e;border:1px solid #22d3ee;box-shadow:0 0 10px #22d3ee,0 0 16px #ec4899}
      :is(.mk-comment-card[data-nameplate-style="nameplate_royal_gold"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_royal_gold"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_royal_gold"] .mk-account-profile-card .mk-local-profile-name){color:#ffe59a;background:linear-gradient(135deg,#17120a,#51320a);border:1px solid #d4a72c;box-shadow:inset 0 0 0 1px #fff3b044}
      :is(.mk-comment-card[data-nameplate-style="nameplate_royal_gold"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_royal_gold"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_royal_gold"] .mk-account-profile-card .mk-local-profile-name)::before{content:"♛";margin-right:.24rem}
      :is(.mk-comment-card[data-nameplate-style="nameplate_holo_id"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_holo_id"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_holo_id"] .mk-account-profile-card .mk-local-profile-name){color:#282044;background:linear-gradient(110deg,#91f5ff,#ffb4ed,#fff49a,#91f5ff);background-size:220%;border:1px solid #fff;animation:mk-shop-rainbow 3s linear infinite}
      :is(.mk-comment-card[data-nameplate-style="nameplate_sakura_tag"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_sakura_tag"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_sakura_tag"] .mk-account-profile-card .mk-local-profile-name){color:#861b50;background:#fff0f6;border:1px solid #fb8fbd;box-shadow:0 4px 12px #ec489933}
      :is(.mk-comment-card[data-nameplate-style="nameplate_sakura_tag"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_sakura_tag"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_sakura_tag"] .mk-account-profile-card .mk-local-profile-name)::after{content:"✿";margin-left:.25rem;color:#ec4899}
      :is(.mk-comment-card[data-nameplate-style="nameplate_cosmic_call_sign"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_cosmic_call_sign"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_cosmic_call_sign"] .mk-account-profile-card .mk-local-profile-name){color:#eef4ff;background:linear-gradient(135deg,#15152e,#3b176a);border:1px solid #a78bfa;box-shadow:0 0 13px #7c3aed66}
      :is(.mk-comment-card[data-nameplate-style="nameplate_pixel_pass"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_pixel_pass"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_pixel_pass"] .mk-account-profile-card .mk-local-profile-name){color:#fef08a;background:#17152f;border:2px solid #22d3ee;border-radius:3px;box-shadow:3px 3px 0 #ec4899;font-family:ui-monospace,monospace}
      :is(.mk-comment-card[data-nameplate-style="nameplate_flame_signature"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_flame_signature"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_flame_signature"] .mk-account-profile-card .mk-local-profile-name){color:#fff7ed;background:linear-gradient(135deg,#1c0703,#7f1d1d);border:1px solid #fb923c;box-shadow:0 0 13px #ef444477,inset 0 -3px #f97316}
      :is(.mk-comment-card[data-nameplate-style="nameplate_ocean_badge"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_ocean_badge"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_ocean_badge"] .mk-account-profile-card .mk-local-profile-name){color:#083344;background:linear-gradient(135deg,#cffafecc,#67e8f9aa);border:1px solid #06b6d4;box-shadow:inset 0 1px #fff,0 4px 12px #0891b244}
      :is(.mk-comment-card[data-nameplate-style="nameplate_ocean_badge"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_ocean_badge"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_ocean_badge"] .mk-account-profile-card .mk-local-profile-name)::after{content:"≈";margin-left:.25rem;color:#0891b2}
      :is(.mk-comment-card[data-nameplate-style="nameplate_frost_crest"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_frost_crest"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_frost_crest"] .mk-account-profile-card .mk-local-profile-name){color:#172554;background:linear-gradient(135deg,#eff6ff,#bae6fd,#c4b5fd);border:1px solid #60a5fa;clip-path:polygon(7px 0,calc(100% - 7px) 0,100% 50%,calc(100% - 7px) 100%,7px 100%,0 50%);box-shadow:0 0 12px #60a5fa55}
      :is(.mk-comment-card[data-nameplate-style="nameplate_botanical_mark"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_botanical_mark"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_botanical_mark"] .mk-account-profile-card .mk-local-profile-name){color:#14532d;background:#ecfdf5;border:1px solid #4ade80;box-shadow:0 4px 12px #16a34a33}
      :is(.mk-comment-card[data-nameplate-style="nameplate_botanical_mark"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_botanical_mark"] .mk-comment-card[data-comment-owner="1"] .mk-comment-name,html[data-mk-nameplate-style="nameplate_botanical_mark"] .mk-account-profile-card .mk-local-profile-name)::before{content:"❧";margin-right:.25rem;color:#16a34a}

      .mk-comment-card[data-reaction-effect] .mk-comment-reaction,
      html[data-mk-reaction-effect] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{position:relative;overflow:visible;isolation:isolate;font-weight:850;transition:transform .18s ease,filter .18s ease}
      .mk-comment-card[data-reaction-effect] .mk-comment-reaction:hover,
      html[data-mk-reaction-effect] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction:hover{transform:translateY(-2px) scale(1.06)}
      .mk-comment-card[data-reaction-effect="reaction_coin_burst"] .mk-comment-reaction,
      html[data-mk-reaction-effect="reaction_coin_burst"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#5b3900;border-color:#e7ad22;background:linear-gradient(135deg,#fff4a8,#f8bd32);box-shadow:0 0 0 1px #fff5 inset,0 4px 12px #d4951944;animation:mk-reaction-coin 2.3s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_heart_rain"] .mk-comment-reaction,
      html[data-mk-reaction-effect="reaction_heart_rain"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#9f1239;border-color:#fb7185;background:linear-gradient(135deg,#fff1f5,#fecdd3);box-shadow:0 4px 12px #fb718544;animation:mk-reaction-heart 1.8s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_thunder_hit"] .mk-comment-reaction,
      html[data-mk-reaction-effect="reaction_thunder_hit"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#082f49;border-color:#22d3ee;background:linear-gradient(135deg,#cffafe,#fef08a);box-shadow:0 0 12px #22d3ee66;animation:mk-reaction-thunder 1.45s steps(2,end) infinite}
      .mk-comment-card[data-reaction-effect="reaction_petal_pop"] .mk-comment-reaction,
      html[data-mk-reaction-effect="reaction_petal_pop"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#9d174d;border-color:#f9a8d4;background:linear-gradient(135deg,#fdf2f8,#fce7f3);box-shadow:0 4px 12px #f472b633;animation:mk-reaction-petal 2.6s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_galaxy_pulse"] .mk-comment-reaction,
      html[data-mk-reaction-effect="reaction_galaxy_pulse"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#f5f3ff;border-color:#8b5cf6;background:linear-gradient(135deg,#1e1b4b,#581c87);box-shadow:0 0 14px #8b5cf677;animation:mk-reaction-galaxy 2.1s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_prism_pop"] .mk-comment-reaction,html[data-mk-reaction-effect="reaction_prism_pop"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#312e81;border-color:#c084fc;background:linear-gradient(120deg,#a5f3fc,#f0abfc,#fde68a,#a7f3d0);background-size:220%;animation:mk-shop-rainbow 2.4s linear infinite}
      .mk-comment-card[data-reaction-effect="reaction_bubble_beat"] .mk-comment-reaction,html[data-mk-reaction-effect="reaction_bubble_beat"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#155e75;border-color:#22d3ee;background:radial-gradient(circle at 75% 24%,#fff 0 3px,transparent 4px),linear-gradient(135deg,#ecfeff,#a5f3fc);box-shadow:0 5px 13px #06b6d444;animation:mk-reaction-bubble 1.7s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_flame_charge"] .mk-comment-reaction,html[data-mk-reaction-effect="reaction_flame_charge"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#fff7ed;border-color:#fb923c;background:linear-gradient(135deg,#7f1d1d,#ea580c);box-shadow:0 0 15px #f9731677;animation:mk-reaction-flame 1.35s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_snow_spark"] .mk-comment-reaction,html[data-mk-reaction-effect="reaction_snow_spark"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#1e3a8a;border-color:#93c5fd;background:linear-gradient(135deg,#eff6ff,#dbeafe);box-shadow:0 0 13px #60a5fa55;animation:mk-reaction-snow 2s ease-in-out infinite}
      .mk-comment-card[data-reaction-effect="reaction_lucky_clover"] .mk-comment-reaction,html[data-mk-reaction-effect="reaction_lucky_clover"] .mk-comment-card[data-comment-owner="1"] .mk-comment-reaction{color:#14532d;border-color:#4ade80;background:linear-gradient(135deg,#f0fdf4,#bbf7d0);box-shadow:0 5px 13px #22c55e44;animation:mk-reaction-clover 1.85s ease-in-out infinite}
      @keyframes mk-reaction-coin{50%{filter:brightness(1.13);box-shadow:0 0 0 1px #fff5 inset,0 4px 18px #eab30888}}
      @keyframes mk-reaction-heart{50%{transform:scale(1.04);filter:saturate(1.18)}}
      @keyframes mk-reaction-thunder{45%{filter:brightness(1.35)}48%{filter:brightness(.9)}}
      @keyframes mk-reaction-petal{50%{transform:translateY(-1px) rotate(-1deg)}}
      @keyframes mk-reaction-galaxy{50%{box-shadow:0 0 22px #a78bfa,0 0 7px #fff inset}}
      @keyframes mk-reaction-bubble{50%{transform:translateY(-2px);filter:brightness(1.08)}}
      @keyframes mk-reaction-flame{50%{box-shadow:0 0 24px #fb9234;filter:brightness(1.18)}}
      @keyframes mk-reaction-snow{50%{filter:brightness(1.12);box-shadow:0 0 19px #bfdbfe}}
      @keyframes mk-reaction-clover{50%{transform:rotate(-1.5deg) scale(1.04);filter:saturate(1.2)}}

      html[data-mk-concept-card-skin] .md-typeset .grid.cards>ul>li{position:relative;overflow:hidden;transition:transform .18s ease,box-shadow .18s ease}
      html[data-mk-concept-card-skin] .md-typeset .grid.cards>ul>li :is(a,strong,em,small,p){color:inherit!important}
      html[data-mk-concept-card-skin] .md-typeset .grid.cards>ul>li:hover{transform:translateY(-3px)}
      html[data-mk-concept-card-skin="concept_card_glass_lab"] .md-typeset .grid.cards>ul>li{background:linear-gradient(135deg,#ffffff99,#bdeeff44)!important;border-color:#8be5ff!important;box-shadow:inset 0 0 0 1px #fff8,0 12px 28px #0ea5e922!important;backdrop-filter:blur(12px)}
      html[data-mk-concept-card-skin="concept_card_cyber_hud"] .md-typeset .grid.cards>ul>li{color:#d9ffff;background:#071c28!important;border:1px solid #22d3ee!important;box-shadow:inset 0 0 22px #06b6d422,0 0 16px #06b6d433!important}
      html[data-mk-concept-card-skin="concept_card_study_notes"] .md-typeset .grid.cards>ul>li{background:repeating-linear-gradient(#fff9d7 0 25px,#b9d9ff 26px)!important;border-color:#e0b44c!important;box-shadow:5px 7px 0 #cf9d3b22!important;transform:rotate(-.35deg)}
      html[data-mk-concept-card-skin="concept_card_manga_panel"] .md-typeset .grid.cards>ul>li{background:#fff!important;border:3px solid #111!important;border-radius:3px!important;box-shadow:7px 7px 0 #111!important}
      html[data-mk-concept-card-skin="concept_card_cosmic_orbit"] .md-typeset .grid.cards>ul>li{color:#eef4ff;background:radial-gradient(circle at 80% 20%,#fff 0 1px,transparent 2px),linear-gradient(135deg,#11152e,#31155b)!important;border-color:#8b5cf6!important;box-shadow:0 0 22px #8b5cf644!important}
      html[data-mk-concept-card-skin="concept_card_blueprint_desk"] .md-typeset .grid.cards>ul>li{color:#e0f2fe;background:linear-gradient(rgba(56,189,248,.13) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.13) 1px,transparent 1px),#0c4a6e!important;background-size:18px 18px!important;border:1px solid #38bdf8!important;box-shadow:inset 0 0 22px #082f4988!important}
      html[data-mk-concept-card-skin="concept_card_forest_journal"] .md-typeset .grid.cards>ul>li{color:#29431f;background:linear-gradient(135deg,#f1f5d8,#d4e7b2)!important;border:1px solid #65a30d!important;box-shadow:inset 6px 0 #4d7c0f,4px 6px 0 #36531422!important}
      html[data-mk-concept-card-skin="concept_card_sunset_glass"] .md-typeset .grid.cards>ul>li{color:#4c1d3d;background:linear-gradient(135deg,#fed7aa99,#f9a8d499,#c4b5fd88)!important;border:1px solid #fb7185!important;box-shadow:inset 0 1px #fff9,0 12px 26px #f9731640!important;backdrop-filter:blur(10px)}
      html[data-mk-concept-card-skin="concept_card_retro_computer"] .md-typeset .grid.cards>ul>li{color:#86efac;background:#052e16!important;border:2px solid #22c55e!important;border-radius:4px!important;box-shadow:inset 0 0 25px #16a34a33,5px 5px 0 #14532d!important;font-family:ui-monospace,monospace}
      html[data-mk-concept-card-skin="concept_card_minimal_ink"] .md-typeset .grid.cards>ul>li{color:#111;background:#fff!important;border:1px solid #111!important;border-radius:2px!important;box-shadow:4px 4px 0 #111!important}

      html[data-mk-notification-skin] .mk-notification-row{position:relative;overflow:visible!important;height:auto!important;min-height:0!important;box-sizing:border-box;border-radius:14px!important;margin:.5rem 0!important;padding:.72rem .82rem!important}
      html[data-mk-notification-skin] .mk-notification-row .mk-local-activity-main{min-width:0}
      html[data-mk-notification-skin] .mk-notification-row .mk-notification-left{padding-block:.08rem;min-width:0}
      html[data-mk-notification-skin] .mk-notification-row :is(.mk-notification-line,.mk-notification-actor-name,.mk-local-activity-link,.mk-local-activity-meta,.mk-notification-context){color:inherit!important}
      html[data-mk-notification-skin="notification_neon_toast"] .mk-notification-row{background:#10162e!important;border:1px solid #22d3ee!important;color:#eaffff;box-shadow:0 0 14px #22d3ee55}
      html[data-mk-notification-skin="notification_royal_letter"] .mk-notification-row{background:linear-gradient(135deg,#fff3d0,#f8dfac)!important;border:1px solid #9f3157!important;box-shadow:inset 5px 0 #8a1f43}
      html[data-mk-notification-skin="notification_holo_message"] .mk-notification-row{background:linear-gradient(120deg,#d9fbffcc,#f7cfffcc,#fff7bacc)!important;border:1px solid #fff!important;box-shadow:0 8px 20px #8b5cf633}
      html[data-mk-notification-skin="notification_forest_sprite"] .mk-notification-row{background:linear-gradient(135deg,#e3fff0,#c5f5dc)!important;border:1px solid #24b58a!important;box-shadow:0 8px 20px #16a36e33}
      html[data-mk-notification-skin="notification_arcade_alert"] .mk-notification-row{background:#17152f!important;border:3px solid #facc15!important;border-radius:2px!important;color:#fff;box-shadow:5px 5px 0 #ec4899!important;font-family:ui-monospace,monospace}
      html[data-mk-notification-skin="notification_cloud_note"] .mk-notification-row{background:linear-gradient(135deg,#f0f9ff,#dbeafe)!important;border:1px solid #7dd3fc!important;box-shadow:0 9px 20px #38bdf833!important}
      html[data-mk-notification-skin="notification_lava_signal"] .mk-notification-row{color:#fff7ed;background:linear-gradient(135deg,#1c0703,#7f1d1d)!important;border:1px solid #fb923c!important;box-shadow:inset 5px 0 #f97316,0 0 16px #ef444455!important}
      html[data-mk-notification-skin="notification_frost_message"] .mk-notification-row{color:#172554;background:linear-gradient(135deg,#eff6fff2,#bae6fddd)!important;border:1px solid #60a5fa!important;box-shadow:inset 0 1px #fff,0 9px 20px #3b82f633!important;backdrop-filter:blur(9px)}
      html[data-mk-notification-skin="notification_paper_plane"] .mk-notification-row{background:linear-gradient(145deg,#fffdf5,#f7edd2)!important;border:1px solid #c8a86b!important;border-radius:5px!important;box-shadow:5px 6px 0 #a1620722!important;transform:rotate(-.15deg)}
      html[data-mk-notification-skin="notification_constellation_ping"] .mk-notification-row{color:#eef2ff;background:radial-gradient(circle at 84% 22%,#fff 0 1px,transparent 2px),linear-gradient(135deg,#11152e,#312e81)!important;border:1px solid #818cf8!important;box-shadow:0 0 17px #6366f155!important}

      .mk-shop-series-preview{position:relative;display:grid;place-items:center;min-height:4rem;margin:.32rem 0 .08rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 12%,transparent);border-radius:14px;overflow:hidden;background:color-mix(in srgb,var(--md-default-bg-color) 94%,transparent)}
      .mk-account-shop-meta{line-height:1.25!important;white-space:normal!important}
      .mk-shop-series-preview:is([data-preview-kind="reaction"],[data-preview-kind="quiz"],[data-preview-kind="sound"],[data-preview-kind="bgm"]){cursor:pointer;pointer-events:auto}
      .mk-shop-series-preview strong,.mk-shop-series-preview span{position:relative;z-index:2}
      .mk-shop-preview-comment-line{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:.45rem;width:82%;font-size:.55rem}
      .mk-shop-preview-comment-line i{display:grid;width:1.15rem;height:1.15rem;place-items:center;border-radius:50%;color:#fff;background:linear-gradient(135deg,#3b82f6,#8b5cf6);font-style:normal;font-weight:900}
      .mk-shop-preview-comment-line strong{justify-self:start;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:.2rem .55rem;border-radius:999px}
      .mk-shop-series-preview[data-preview-variant="neon-gamer"] .mk-shop-preview-comment-line strong{color:#d9ffff;background:#10162e;border:1px solid #22d3ee;box-shadow:0 0 10px #22d3ee,0 0 14px #ec4899}
      .mk-shop-series-preview[data-preview-variant="royal-gold"] .mk-shop-preview-comment-line strong{color:#ffe59a;background:#2a1908;border:1px solid #d4a72c}
      .mk-shop-series-preview[data-preview-variant="holo-id"] .mk-shop-preview-comment-line strong{color:#282044;background:linear-gradient(110deg,#91f5ff,#ffb4ed,#fff49a);border:1px solid #fff}
      .mk-shop-series-preview[data-preview-variant="sakura-tag"] .mk-shop-preview-comment-line strong{color:#861b50;background:#fff0f6;border:1px solid #fb8fbd}
      .mk-shop-series-preview[data-preview-variant="cosmic-call-sign"] .mk-shop-preview-comment-line strong{color:#eef4ff;background:#25124d;border:1px solid #a78bfa}
      .mk-shop-series-preview[data-preview-variant="pixel-pass"] .mk-shop-preview-comment-line strong{color:#fef08a;background:#17152f;border:2px solid #22d3ee;border-radius:3px;box-shadow:3px 3px 0 #ec4899;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-variant="flame-signature"] .mk-shop-preview-comment-line strong{color:#fff7ed;background:#4c0b08;border:1px solid #fb923c;box-shadow:0 0 12px #ef444477}
      .mk-shop-series-preview[data-preview-variant="ocean-badge"] .mk-shop-preview-comment-line strong{color:#083344;background:linear-gradient(135deg,#cffafe,#67e8f9);border:1px solid #06b6d4}
      .mk-shop-series-preview[data-preview-variant="frost-crest"] .mk-shop-preview-comment-line strong{color:#172554;background:linear-gradient(135deg,#eff6ff,#bae6fd,#c4b5fd);border:1px solid #60a5fa;clip-path:polygon(7px 0,calc(100% - 7px) 0,100% 50%,calc(100% - 7px) 100%,7px 100%,0 50%)}
      .mk-shop-series-preview[data-preview-variant="botanical-mark"] .mk-shop-preview-comment-line strong{color:#14532d;background:#ecfdf5;border:1px solid #4ade80}
      .mk-shop-preview-reaction-row{display:flex;align-items:center;gap:.38rem}.mk-shop-preview-reaction-row button{padding:.26rem .42rem;border:1px solid #ddd;border-radius:999px;background:#fff;font:700 .55rem/1 system-ui}.mk-shop-preview-reaction-row span{font-size:1rem;animation:mk-shop-preview-pop 1.3s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="coin-burst"] .mk-shop-preview-reaction-row button{color:#5b3900;border-color:#e7ad22;background:linear-gradient(135deg,#fff4a8,#f8bd32);box-shadow:0 4px 12px #d4951944;animation:mk-reaction-coin 2.3s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="heart-rain"] .mk-shop-preview-reaction-row button{color:#9f1239;border-color:#fb7185;background:linear-gradient(135deg,#fff1f5,#fecdd3);animation:mk-reaction-heart 1.8s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="thunder-hit"] .mk-shop-preview-reaction-row button{color:#082f49;border-color:#22d3ee;background:linear-gradient(135deg,#cffafe,#fef08a);box-shadow:0 0 12px #22d3ee66;animation:mk-reaction-thunder 1.45s steps(2,end) infinite}
      .mk-shop-series-preview[data-preview-variant="petal-pop"] .mk-shop-preview-reaction-row button{color:#9d174d;border-color:#f9a8d4;background:linear-gradient(135deg,#fdf2f8,#fce7f3);animation:mk-reaction-petal 2.6s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="galaxy-pulse"] .mk-shop-preview-reaction-row button{color:#f5f3ff;border-color:#8b5cf6;background:linear-gradient(135deg,#1e1b4b,#581c87);box-shadow:0 0 14px #8b5cf677;animation:mk-reaction-galaxy 2.1s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="prism-pop"] .mk-shop-preview-reaction-row button{color:#312e81;border-color:#c084fc;background:linear-gradient(120deg,#a5f3fc,#f0abfc,#fde68a,#a7f3d0);background-size:220%;animation:mk-shop-rainbow 2.4s linear infinite}
      .mk-shop-series-preview[data-preview-variant="bubble-beat"] .mk-shop-preview-reaction-row button{color:#155e75;border-color:#22d3ee;background:linear-gradient(135deg,#ecfeff,#a5f3fc);animation:mk-reaction-bubble 1.7s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="flame-charge"] .mk-shop-preview-reaction-row button{color:#fff7ed;border-color:#fb923c;background:linear-gradient(135deg,#7f1d1d,#ea580c);animation:mk-reaction-flame 1.35s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="snow-spark"] .mk-shop-preview-reaction-row button{color:#1e3a8a;border-color:#93c5fd;background:linear-gradient(135deg,#eff6ff,#dbeafe);animation:mk-reaction-snow 2s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-variant="lucky-clover"] .mk-shop-preview-reaction-row button{color:#14532d;border-color:#4ade80;background:linear-gradient(135deg,#f0fdf4,#bbf7d0);animation:mk-reaction-clover 1.85s ease-in-out infinite}
      .mk-shop-preview-reading{display:grid;width:84%;gap:.35rem}.mk-shop-preview-reading i{position:relative;display:block;height:7px;border-radius:999px;background:linear-gradient(90deg,#22d3ee 0 68%,#ddd 68%);box-shadow:0 0 10px #22d3ee}.mk-shop-preview-reading i::after{content:"💠";position:absolute;left:calc(68% - 8px);top:50%;transform:translateY(-50%);font:13px/1 "Segoe UI Emoji",sans-serif}.mk-shop-preview-reading strong{font-size:.62rem}.mk-shop-preview-reading small{font-size:.45rem;opacity:.62}
      .mk-shop-series-preview[data-preview-variant="liquid-rainbow"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#ff3b7b,#ffb800,#68ff8c,#2edcff 68%,#ddd 68%);box-shadow:none}
      .mk-shop-series-preview[data-preview-variant="liquid-rainbow"] .mk-shop-preview-reading i::after{content:"🌈"}
      .mk-shop-series-preview[data-preview-variant="racing-meter"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#ef233c 0 55%,#ffb703 55% 68%,#222 68%);box-shadow:0 0 8px #ef233c}
      .mk-shop-series-preview[data-preview-variant="racing-meter"] .mk-shop-preview-reading i::after{content:"🏎️";transform:translateY(-50%) scaleX(-1)}
      .mk-shop-series-preview[data-preview-variant="star-trail"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#312e81,#8b5cf6,#f0abfc 68%,#ddd 68%);box-shadow:7px 0 9px #a78bfa}
      .mk-shop-series-preview[data-preview-variant="star-trail"] .mk-shop-preview-reading i::after{content:"⭐"}
      .mk-shop-series-preview[data-preview-variant="crystal-charge"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#0ea5e9,#c4f1ff 48%,#818cf8 68%,#ddd 68%);clip-path:polygon(0 0,98% 0,100% 50%,98% 100%,0 100%)}
      .mk-shop-series-preview[data-preview-variant="crystal-charge"] .mk-shop-preview-reading i::after{content:"💎"}
      .mk-shop-series-preview[data-preview-variant="sakura-runner"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#f9a8d4,#fb7185 68%,#ddd 68%)}
      .mk-shop-series-preview[data-preview-variant="sakura-runner"] .mk-shop-preview-reading i::after{content:"🌸"}
      .mk-shop-series-preview[data-preview-variant="rocket-route"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#312e81,#22d3ee 68%,#ddd 68%);box-shadow:0 0 9px #38bdf8}
      .mk-shop-series-preview[data-preview-variant="rocket-route"] .mk-shop-preview-reading i::after{content:"🚀"}
      .mk-shop-series-preview[data-preview-variant="koi-stream"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#0ea5e9,#99f6e4 68%,#ddd 68%)}
      .mk-shop-series-preview[data-preview-variant="koi-stream"] .mk-shop-preview-reading i::after{content:"🐟";transform:translateY(-50%) scaleX(-1)}
      .mk-shop-series-preview[data-preview-variant="pixel-quest"] .mk-shop-preview-reading i{background:repeating-linear-gradient(90deg,#22d3ee 0 8px,#a3e635 8px 16px,#facc15 16px 24px,#222 24px 26px)}
      .mk-shop-series-preview[data-preview-variant="pixel-quest"] .mk-shop-preview-reading i::after{content:"👾"}
      .mk-shop-series-preview[data-preview-variant="moon-cycle"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#0f172a,#818cf8 68%,#ddd 68%);box-shadow:0 0 10px #818cf8}
      .mk-shop-series-preview[data-preview-variant="moon-cycle"] .mk-shop-preview-reading i::after{content:"🌙"}
      .mk-shop-series-preview[data-preview-variant="comet-runner"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#1e1b4b,#7c3aed,#f0abfc 68%,#ddd 68%);box-shadow:0 0 10px #c084fc}
      .mk-shop-series-preview[data-preview-variant="comet-runner"] .mk-shop-preview-reading i::after{content:"☄️"}
      .mk-shop-series-preview[data-preview-variant="paper-plane"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#38bdf8,#bae6fd 68%,#ddd 68%);box-shadow:0 0 9px #7dd3fc}
      .mk-shop-series-preview[data-preview-variant="paper-plane"] .mk-shop-preview-reading i::after{content:"✈️"}
      .mk-shop-series-preview[data-preview-variant="fox-sprint"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#365314,#84cc16,#f59e0b 68%,#ddd 68%)}
      .mk-shop-series-preview[data-preview-variant="fox-sprint"] .mk-shop-preview-reading i::after{content:"🦊";transform:translateY(-50%) scaleX(-1)}
      .mk-shop-series-preview[data-preview-variant="dragon-flight"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#450a0a,#dc2626,#fb923c 68%,#ddd 68%);box-shadow:0 0 10px #f97316}
      .mk-shop-series-preview[data-preview-variant="dragon-flight"] .mk-shop-preview-reading i::after{content:"🐉";transform:translateY(-50%) scaleX(-1)}
      .mk-shop-series-preview[data-preview-variant="train-route"] .mk-shop-preview-reading i{background:linear-gradient(90deg,#0f172a,#2563eb,#e2e8f0 68%,#ddd 68%);box-shadow:0 0 9px #60a5fa}
      .mk-shop-series-preview[data-preview-variant="train-route"] .mk-shop-preview-reading i::after{content:"🚄"}
      .mk-shop-preview-connections{display:grid;width:82%;gap:.34rem;padding:.52rem .58rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 18%,transparent);border-radius:13px;background:linear-gradient(135deg,#eef4ff,#f8fbff);box-sizing:border-box;color:#1f2937;text-align:left}.mk-shop-preview-connections>strong{font-size:.58rem;padding-bottom:.26rem;border-bottom:1px solid currentColor;opacity:.88}.mk-conn-prev-section{display:grid;grid-template-columns:minmax(0,.86fr) minmax(0,1.14fr);align-items:center;gap:.35rem;padding-top:.04rem}.mk-conn-prev-section b{font-size:.43rem}.mk-conn-prev-section span{position:relative;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.39rem;font-weight:750}.mk-conn-prev-section.is-dependent b{color:#3b82f6}.mk-conn-prev-section.is-prerequisite b{color:#10b981}.mk-conn-prev-section.is-related b{color:#8b5cf6}
      .mk-shop-series-preview[data-preview-kind="connection_panel"][data-preview-variant="frosted-atlas"] .mk-shop-preview-connections{background:linear-gradient(135deg,#ffffffd9,#dbeafea8,#e0f2feb8);border-color:#7dd3fc;box-shadow:inset 0 1px #fff,0 8px 18px #0e749026;backdrop-filter:blur(8px)}
      .mk-shop-series-preview[data-preview-kind="connection_panel"][data-preview-variant="midnight-network"] .mk-shop-preview-connections{color:#eef2ff;background:radial-gradient(circle at 14% 20%,#fff 0 1px,transparent 1.6px),radial-gradient(circle at 86% 26%,#67e8f9 0 1px,transparent 1.8px),linear-gradient(135deg,#07152f,#312e81,#581c87);border-color:#818cf8;box-shadow:0 0 15px #6366f15c}
      .mk-shop-series-preview[data-preview-kind="connection_panel"][data-preview-variant="study-parchment"] .mk-shop-preview-connections{color:#4b3a20;background:linear-gradient(90deg,transparent 0 27px,#ef444433 27px 28px,transparent 28px),repeating-linear-gradient(0deg,#fff9df 0 19px,#bfd7f2 19px 20px);border-color:#c8a86b;box-shadow:4px 5px 0 #a162071f}
      .mk-shop-series-preview[data-preview-kind="connection_panel"][data-preview-variant="aurora-flow"] .mk-shop-preview-connections{color:#172554;background:linear-gradient(115deg,#bae6fd,#a7f3d0,#ddd6fe,#fbcfe8,#fde68a,#bae6fd);background-size:260%;border-color:#a78bfa;animation:mk-conn-preview-aurora 6s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="connection_panel"][data-preview-variant="blueprint-glass"] .mk-shop-preview-connections{color:#d9ffff;background:linear-gradient(#22d3ee1f 1px,transparent 1px),linear-gradient(90deg,#22d3ee1f 1px,transparent 1px),#071c28;background-size:12px 12px;border-color:#22d3ee;box-shadow:inset 0 0 15px #06b6d438}
      .mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="signal-tabs"] .mk-conn-prev-section b{padding:.14rem .25rem;border:1px solid currentColor;border-radius:999px;background:color-mix(in srgb,currentColor 10%,transparent)}
      .mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="neon-rails"] .mk-conn-prev-section{padding-left:.30rem;border-left:3px solid currentColor;box-shadow:-4px 0 10px color-mix(in srgb,currentColor 46%,transparent)}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="neon-rails"] .is-dependent{color:#3b82f6}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="neon-rails"] .is-prerequisite{color:#10b981}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="neon-rails"] .is-related{color:#8b5cf6}
      .mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="garden-markers"] .mk-conn-prev-section b::before{content:"❧";margin-right:.18rem;color:#16a34a}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="garden-markers"] .mk-conn-prev-section{padding:.12rem .22rem;border-radius:7px;background:#dcfce744}
      .mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="spectrum-headers"] .mk-conn-prev-section b{padding-bottom:.10rem;border-bottom:2px solid currentColor;text-shadow:0 0 8px color-mix(in srgb,currentColor 50%,transparent)}
      .mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="minimal-index"] .mk-conn-prev-section b{color:#111!important;text-transform:uppercase;letter-spacing:.04em;font-family:ui-monospace,monospace}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="minimal-index"] .is-dependent b::before{content:"01 ";opacity:.45}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="minimal-index"] .is-prerequisite b::before{content:"02 ";opacity:.45}.mk-shop-series-preview[data-preview-kind="connection_sections"][data-preview-variant="minimal-index"] .is-related b::before{content:"03 ";opacity:.45}
      .mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="orbit-nodes"] .mk-conn-prev-section span{padding:.12rem .30rem;border:1px solid #818cf8;border-radius:999px}.mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="orbit-nodes"] .mk-conn-prev-section span::after{content:"";position:absolute;right:.12rem;top:50%;width:.20rem;height:.20rem;border-radius:50%;background:#22d3ee;box-shadow:0 0 7px #22d3ee;transform-origin:-.35rem 0;animation:mk-conn-preview-orbit 2.2s linear infinite}
      .mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="comet-trails"] .mk-conn-prev-section span{padding:.13rem .30rem;border-radius:6px;background:linear-gradient(90deg,#6366f122,#22d3ee1f)}.mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="comet-trails"] .mk-conn-prev-section span::after{content:"";position:absolute;inset:0 auto 0 -45%;width:40%;background:linear-gradient(90deg,transparent,#fff9,transparent);transform:skewX(-20deg);animation:mk-conn-preview-comet 1.9s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="card-stack"] .mk-conn-prev-section span{padding:.17rem .30rem;border:1px solid #cbd5e1;border-radius:7px;background:#fff;box-shadow:2px 3px 0 #94a3b84a}
      .mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="circuit-links"] .mk-conn-prev-section span{padding:.15rem .30rem;color:#cffafe;background:#083344;border:1px solid #22d3ee;border-radius:3px;box-shadow:inset 0 0 8px #06b6d438;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-kind="connection_links"][data-preview-variant="underline-pulse"] .mk-conn-prev-section span{padding-bottom:.10rem;background:linear-gradient(90deg,currentColor,currentColor) 0 100%/68% 2px no-repeat;animation:mk-conn-preview-underline 1.8s ease-in-out infinite}
      @keyframes mk-conn-preview-aurora{50%{background-position:100% 50%}}
      @keyframes mk-conn-preview-orbit{to{transform:rotate(360deg)}}
      @keyframes mk-conn-preview-comet{50%,100%{left:115%}}
      @keyframes mk-conn-preview-underline{50%{background-size:100% 2px}}
      .mk-shop-preview-finder-builder{display:grid;width:84%;gap:.48rem;padding:.58rem .62rem;border:1px solid #cbd5e1;border-radius:13px;background:linear-gradient(135deg,#f8fbff,#eef4ff);box-sizing:border-box;color:#1f2937;text-align:left}.mk-shop-preview-finder-builder>strong{font-size:.58rem}.mk-fb-prev-chips,.mk-fb-prev-actions{display:flex;align-items:center;gap:.25rem;min-width:0}.mk-fb-prev-chips span{position:relative;padding:.18rem .32rem;border:1px solid #a5b4fc;border-radius:999px;background:#eef2ff;font:750 .40rem/1 system-ui;white-space:nowrap}.mk-fb-prev-chips .is-op{color:#6d28d9;border-color:#c4b5fd;background:#f5f3ff}.mk-fb-prev-actions button{min-height:1.28rem;padding:.17rem .30rem;border:1px solid #cbd5e1;border-radius:999px;color:inherit;background:#fff;font:750 .38rem/1 system-ui;pointer-events:none}.mk-fb-prev-actions .is-run{margin-left:auto;color:#fff;border-color:#4f46e5;background:#4f46e5}
      .mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="frosted-prism"] .mk-shop-preview-finder-builder{background:linear-gradient(135deg,#ffffffdc,#dbeafea8,#f5d0fea0);border-color:#7dd3fc;box-shadow:inset 0 1px #fff,0 8px 18px #0e749026;backdrop-filter:blur(8px)}
      .mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="night-console"] .mk-shop-preview-finder-builder{color:#d9ffff;background:radial-gradient(circle at 14% 20%,#67e8f9 0 1px,transparent 1.8px),linear-gradient(135deg,#07152f,#172554,#312e81);border-color:#22d3ee;box-shadow:inset 0 0 16px #06b6d438,0 0 13px #22d3ee42}.mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="night-console"] .mk-fb-prev-actions button{color:inherit;background:#ffffff10}
      .mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="scholar-desk"] .mk-shop-preview-finder-builder{color:#4b3a20;background:linear-gradient(90deg,transparent 0 28px,#ef444433 28px 29px,transparent 29px),repeating-linear-gradient(0deg,#fff9df 0 19px,#bfd7f2 19px 20px);border-color:#c8a86b;box-shadow:4px 5px 0 #a162071f}
      .mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="aurora-studio"] .mk-shop-preview-finder-builder{color:#172554;background:linear-gradient(115deg,#bae6fd,#a7f3d0,#ddd6fe,#fbcfe8,#fde68a,#bae6fd);background-size:260%;border-color:#a78bfa;animation:mk-fb-preview-aurora 6s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="blueprint-engine"] .mk-shop-preview-finder-builder{color:#d9ffff;background:linear-gradient(#22d3ee1f 1px,transparent 1px),linear-gradient(90deg,#22d3ee1f 1px,transparent 1px),#071c28;background-size:12px 12px;border-color:#22d3ee;box-shadow:inset 0 0 15px #06b6d438}.mk-shop-series-preview[data-preview-kind="finder_builder_panel"][data-preview-variant="blueprint-engine"] .mk-fb-prev-actions button{color:inherit;background:#083344}
      .mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="prism-capsules"] .mk-fb-prev-actions button{color:#26356e;border-color:#70d9ed;background:linear-gradient(135deg,#cffafe,#ddd6fe,#fbcfe8);box-shadow:inset 0 1px #fff,0 3px 8px #4338ca2e}
      .mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="cyber-controls"] .mk-fb-prev-actions button{color:#d9ffff;border-color:#22d3ee;background:#071c28;box-shadow:0 0 8px #22d3ee66}.mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="cyber-controls"] .mk-fb-prev-actions .is-run{animation:mk-fb-preview-cyber 2s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="candy-pop"] .mk-fb-prev-actions button{color:#70254a;border-color:#fb7185;background:linear-gradient(135deg,#ffedd5,#fecdd3,#fbcfe8);box-shadow:0 3px 8px #f43f5e2e}
      .mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="forest-tactile"] .mk-fb-prev-actions button{color:#214e36;border-color:#4ade80;background:linear-gradient(#ecfdf5,#bbf7d0);box-shadow:inset 0 -2px #15803d2e,0 3px 7px #15803d24}
      .mk-shop-series-preview[data-preview-kind="finder_builder_buttons"][data-preview-variant="mono-keyboard"] .mk-fb-prev-actions button{color:#111;border-color:#111;border-radius:4px;background:#fff;box-shadow:2px 2px 0 #111;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="orbit-nodes"] .mk-fb-prev-chips span{padding-right:.65rem;border-color:#818cf8;background:#eef2ff}.mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="orbit-nodes"] .mk-fb-prev-chips span::after{content:"";position:absolute;right:.18rem;top:50%;width:.18rem;height:.18rem;border-radius:50%;background:#22d3ee;box-shadow:0 0 6px #22d3ee;transform-origin:-.28rem 0;animation:mk-fb-preview-orbit 2.2s linear infinite}
      .mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="neon-syntax"] .mk-fb-prev-chips span{color:#a7f3d0;border-color:#34d399;background:#052e2b;box-shadow:0 0 7px #34d39955}.mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="neon-syntax"] .mk-fb-prev-chips .is-op{color:#f0abfc;border-color:#e879f9;background:#3b0764}
      .mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="sticky-labels"] .mk-fb-prev-chips span{color:#594420;border-color:#d6a94c;border-radius:3px;background:#fff1a8;box-shadow:2px 3px 0 #a1620726;transform:rotate(-1deg);font-family:"Comic Sans MS",cursive}.mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="sticky-labels"] .mk-fb-prev-chips span:nth-child(2){transform:rotate(1.5deg)}
      .mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="crystal-capsules"] .mk-fb-prev-chips span{color:#075985;border-color:#7dd3fc;background:linear-gradient(135deg,#ffffffcc,#bae6fd99);box-shadow:inset 0 1px #fff,0 0 8px #38bdf855}
      .mk-shop-series-preview[data-preview-kind="finder_builder_tokens"][data-preview-variant="pixel-query"] .mk-fb-prev-chips span{color:#d9ffff;border:2px solid #22d3ee;border-radius:2px;background:#071c28;box-shadow:2px 2px 0 #8b5cf6;font-family:ui-monospace,monospace;text-transform:uppercase}
      @keyframes mk-fb-preview-aurora{50%{background-position:100% 50%}}
      @keyframes mk-fb-preview-cyber{50%{box-shadow:0 0 15px #22d3ee}}
      @keyframes mk-fb-preview-orbit{to{transform:rotate(360deg)}}
      .mk-shop-preview-sidepanel{display:grid;width:66%;gap:.42rem;padding:.48rem;border:1px solid #cbd5e1;border-radius:13px;background:linear-gradient(180deg,#f8fbff,#eef4ff);box-sizing:border-box;color:#1f2937;text-align:left}.mk-sp-prev-top{display:flex;align-items:center;gap:.28rem}.mk-sp-prev-top strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.48rem}.mk-sp-prev-top button{margin-left:auto;padding:.16rem .28rem;border:1px solid #cbd5e1;border-radius:999px;color:inherit;background:#fff;font:750 .34rem/1 system-ui;pointer-events:none}.mk-shop-preview-sidepanel section{display:grid;gap:.17rem;padding:.34rem;border:1px solid #dbe3ef;border-radius:9px;background:#ffffffb8}.mk-shop-preview-sidepanel section b{font-size:.43rem}.mk-shop-preview-sidepanel section span{padding:.14rem .25rem;border-radius:6px;font-size:.38rem;font-weight:680}.mk-shop-preview-sidepanel section .is-active{color:#4338ca;background:#e0e7ff}
      .mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="frosted-atlas"] .mk-shop-preview-sidepanel{background:linear-gradient(135deg,#ffffffdc,#dbeafea8,#e0f2feb8);border-color:#7dd3fc;box-shadow:inset 0 1px #fff,0 8px 18px #0e749026;backdrop-filter:blur(8px)}
      .mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="midnight-network"] .mk-shop-preview-sidepanel{color:#eef2ff;background:radial-gradient(circle at 15% 18%,#fff 0 1px,transparent 1.7px),radial-gradient(circle at 85% 35%,#67e8f9 0 1px,transparent 1.7px),linear-gradient(135deg,#07152f,#312e81,#581c87);border-color:#818cf8;box-shadow:0 0 15px #6366f15c}.mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="midnight-network"] .mk-shop-preview-sidepanel section{background:#08172dbf;border-color:#67e8f955}.mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="midnight-network"] .mk-sp-prev-top button{color:inherit;background:#ffffff10}
      .mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="scholar-paper"] .mk-shop-preview-sidepanel{color:#4b3a20;background:linear-gradient(90deg,transparent 0 25px,#ef444433 25px 26px,transparent 26px),repeating-linear-gradient(0deg,#fff9df 0 18px,#bfd7f2 18px 19px);border-color:#c8a86b;box-shadow:4px 5px 0 #a162071f}.mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="scholar-paper"] .mk-shop-preview-sidepanel section{background:#fff9dfb8;border-color:#c8a86b}
      .mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="aurora-drift"] .mk-shop-preview-sidepanel{color:#172554;background:linear-gradient(115deg,#bae6fd,#a7f3d0,#ddd6fe,#fbcfe8,#fde68a,#bae6fd);background-size:260%;border-color:#a78bfa;animation:mk-sp-preview-aurora 6s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="blueprint-grid"] .mk-shop-preview-sidepanel{color:#d9ffff;background:linear-gradient(#22d3ee1f 1px,transparent 1px),linear-gradient(90deg,#22d3ee1f 1px,transparent 1px),#071c28;background-size:12px 12px;border-color:#22d3ee;box-shadow:inset 0 0 15px #06b6d438}.mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="blueprint-grid"] .mk-shop-preview-sidepanel section{background:#083344d9;border-color:#22d3ee}.mk-shop-series-preview[data-preview-kind="sidepanel_surface"][data-preview-variant="blueprint-grid"] .mk-sp-prev-top button{color:inherit;background:#083344}
      .mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="crystal-stack"] .mk-shop-preview-sidepanel section,.mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="crystal-stack"] .mk-sp-prev-top button{border-color:#7dd3fc;background:linear-gradient(135deg,#ffffffd9,#bae6fd9c);box-shadow:inset 0 1px #fff,3px 4px 0 #38bdf82e}
      .mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="neon-hud"] .mk-shop-preview-sidepanel section,.mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="neon-hud"] .mk-sp-prev-top button{color:#d9ffff;border-color:#22d3ee;border-radius:3px;background:#071c28;box-shadow:inset 0 0 10px #06b6d438,0 0 8px #22d3ee55}
      .mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="notebook-tabs"] .mk-shop-preview-sidepanel section,.mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="notebook-tabs"] .mk-sp-prev-top button{color:#4b3a20;border-color:#d6a94c;border-radius:4px;background:#fff4bd;box-shadow:3px 4px 0 #a1620726;transform:rotate(-.5deg)}
      .mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="sakura-soft"] .mk-shop-preview-sidepanel section,.mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="sakura-soft"] .mk-sp-prev-top button{color:#831843;border-color:#f9a8d4;background:linear-gradient(135deg,#fff1f2,#fce7f3,#fae8ff);box-shadow:0 5px 12px #ec48992e}
      .mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="ink-blocks"] .mk-shop-preview-sidepanel section,.mk-shop-series-preview[data-preview-kind="sidepanel_cards"][data-preview-variant="ink-blocks"] .mk-sp-prev-top button{color:#111;border:2px solid #111;border-radius:3px;background:#fff;box-shadow:4px 4px 0 #111;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="aurora-pills"] .mk-shop-preview-sidepanel section span{color:#3730a3;background:linear-gradient(90deg,#cffafe,#ddd6fe,#fbcfe8);box-shadow:inset 0 0 0 1px #818cf866}.mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="aurora-pills"] .mk-shop-preview-sidepanel section .is-active{box-shadow:0 0 8px #8b5cf67a}
      .mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="neon-rails"] .mk-shop-preview-sidepanel section span{color:#cffafe;border-left:3px solid #22d3ee;border-radius:2px;background:#083344;box-shadow:-3px 0 8px #22d3ee66}.mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="neon-rails"] .mk-shop-preview-sidepanel section .is-active{color:#fff;box-shadow:-3px 0 10px #22d3ee,0 0 8px #22d3ee55}
      .mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="gold-bookmarks"] .mk-shop-preview-sidepanel section span{color:#6b4300;border-left:4px solid #d6a83d;border-radius:2px;background:#fff4bd}.mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="gold-bookmarks"] .mk-shop-preview-sidepanel section .is-active{box-shadow:inset 0 0 0 1px #d6a83d,0 0 8px #eab30866}
      .mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="forest-markers"] .mk-shop-preview-sidepanel section span{color:#166534;background:linear-gradient(90deg,#bbf7d0,#ecfdf5)}.mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="forest-markers"] .mk-shop-preview-sidepanel section span::before{content:"◆";margin-right:.18rem;color:#22c55e;font-size:.28rem}
      .mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="mono-underline"] .mk-shop-preview-sidepanel section span{color:#111;border-radius:0;background:linear-gradient(90deg,#111,#111) 0 100%/45% 1px no-repeat;font-family:ui-monospace,monospace}.mk-shop-series-preview[data-preview-kind="sidepanel_links"][data-preview-variant="mono-underline"] .mk-shop-preview-sidepanel section .is-active{background-size:100% 2px}
      @keyframes mk-sp-preview-aurora{50%{background-position:100% 50%}}
      .mk-shop-preview-mastery{display:grid;width:82%;gap:.42rem;padding:.55rem .62rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 18%,transparent);border-radius:12px;background:linear-gradient(135deg,rgba(63,81,181,.09),rgba(63,81,181,.03));box-sizing:border-box}.mk-shop-preview-mastery>strong{font-size:.58rem}.mk-shop-preview-mastery>div{display:flex;gap:.28rem;flex-wrap:wrap}.mk-shop-preview-mastery button{min-height:1.38rem;padding:.18rem .38rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 18%,transparent);border-radius:999px;color:inherit;background:rgba(255,255,255,.18);font:750 .42rem/1 system-ui;pointer-events:none}.mk-shop-preview-mastery .is-manage{margin-left:auto;width:1.38rem;padding:0}
      .mk-shop-series-preview[data-preview-kind="mastery_button"][data-preview-variant="aurora-glass"] .mk-shop-preview-mastery button{color:#26356e;border-color:#70d9ed;background:linear-gradient(135deg,#cffafe,#ddd6fe,#fbcfe8);box-shadow:inset 0 1px #fff,0 4px 10px #4338ca2e}
      .mk-shop-series-preview[data-preview-kind="mastery_button"][data-preview-variant="cyber-pulse"] .mk-shop-preview-mastery button{color:#d9ffff;border-color:#22d3ee;background:linear-gradient(135deg,#071c28,#123449);box-shadow:0 0 10px #22d3ee66;animation:mk-mastery-preview-cyber 2.2s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="mastery_button"][data-preview-variant="sunset-candy"] .mk-shop-preview-mastery button{color:#70254a;border-color:#fb7185;background:linear-gradient(135deg,#ffedd5,#fecdd3,#fbcfe8);box-shadow:0 4px 10px #f43f5e2e}
      .mk-shop-series-preview[data-preview-kind="mastery_button"][data-preview-variant="forest-tactile"] .mk-shop-preview-mastery button{color:#214e36;border-color:#4ade80;background:linear-gradient(#ecfdf5,#bbf7d0);box-shadow:inset 0 -2px #15803d2e,0 3px 7px #15803d24}
      .mk-shop-series-preview[data-preview-kind="mastery_button"][data-preview-variant="mono-keys"] .mk-shop-preview-mastery button{color:#111;border-color:#111;border-radius:4px;background:#fff;box-shadow:2px 2px 0 #111;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-kind="mastery_background"][data-preview-variant="frosted-study"] .mk-shop-preview-mastery{background:linear-gradient(135deg,#ffffffd9,#dbeafeaa,#e0f2feb8);box-shadow:inset 0 1px #fff,0 8px 18px #0e749022;backdrop-filter:blur(8px)}
      .mk-shop-series-preview[data-preview-kind="mastery_background"][data-preview-variant="midnight-cosmos"] .mk-shop-preview-mastery{color:#eef2ff;background:radial-gradient(circle at 15% 22%,#fff 0 1px,transparent 1.6px),radial-gradient(circle at 82% 18%,#a5f3fc 0 1px,transparent 1.7px),linear-gradient(135deg,#07152f,#312e81,#581c87);border-color:#818cf8}
      .mk-shop-series-preview[data-preview-kind="mastery_background"][data-preview-variant="warm-notebook"] .mk-shop-preview-mastery{color:#4b3a20;background:linear-gradient(90deg,transparent 0 30px,#ef444438 30px 31px,transparent 31px),repeating-linear-gradient(0deg,#fff9df 0 19px,#bfd7f2 19px 20px);border-color:#c8a86b}
      .mk-shop-series-preview[data-preview-kind="mastery_background"][data-preview-variant="aurora-wash"] .mk-shop-preview-mastery{color:#172554;background:linear-gradient(115deg,#bae6fd,#a7f3d0,#ddd6fe,#fbcfe8,#fde68a,#bae6fd);background-size:260%;animation:mk-mastery-preview-aurora 6s ease-in-out infinite;border-color:#a78bfa}
      .mk-shop-series-preview[data-preview-kind="mastery_background"][data-preview-variant="pixel-grid"] .mk-shop-preview-mastery{color:#d9ffff;background:linear-gradient(#22d3ee1a 1px,transparent 1px),linear-gradient(90deg,#22d3ee1a 1px,transparent 1px),#071c28;background-size:12px 12px;border-color:#22d3ee;box-shadow:inset 0 0 16px #06b6d433}
      .mk-shop-series-preview[data-preview-kind="mastery_border"][data-preview-variant="prism-trace"] .mk-shop-preview-mastery{border:2px solid #8b5cf6;box-shadow:0 0 0 1px #22d3ee66,0 0 13px #8b5cf666;animation:mk-mastery-preview-prism 3s ease-in-out infinite}
      .mk-shop-series-preview[data-preview-kind="mastery_border"][data-preview-variant="gold-circuit"] .mk-shop-preview-mastery{border:2px solid #d6a83d;box-shadow:inset 0 0 0 2px #fff0b34f,0 0 0 1px #8a5a13}
      .mk-shop-series-preview[data-preview-kind="mastery_border"][data-preview-variant="sakura-stitch"] .mk-shop-preview-mastery{border:2px dashed #f472b6;box-shadow:inset 0 0 0 3px #fbcfe861}
      .mk-shop-series-preview[data-preview-kind="mastery_border"][data-preview-variant="ice-crystal"] .mk-shop-preview-mastery{border:3px double #38bdf8;border-radius:16px;box-shadow:0 0 13px #60a5fa61}
      .mk-shop-series-preview[data-preview-kind="mastery_border"][data-preview-variant="ink-frame"] .mk-shop-preview-mastery{border:3px solid #111;border-radius:4px;box-shadow:5px 5px 0 #111}
      .mk-shop-series-preview[data-preview-kind="mastery_rating"][data-preview-variant="mastered-gold"] .mk-shop-preview-mastery .is-mastered{color:#7a4b00;border-color:#d6a83d;background:linear-gradient(#fff4bb,#efc456);box-shadow:0 0 11px #eab30899}
      .mk-shop-series-preview[data-preview-kind="mastery_rating"][data-preview-variant="clear-silver"] .mk-shop-preview-mastery .is-clear{color:#334155;border-color:#94a3b8;background:linear-gradient(#f8fafc,#cbd5e1);box-shadow:0 0 10px #94a3b899}
      @keyframes mk-mastery-preview-cyber{50%{box-shadow:0 0 16px #22d3ee}}
      @keyframes mk-mastery-preview-aurora{50%{background-position:100% 50%}}
      @keyframes mk-mastery-preview-prism{50%{border-color:#f472b6;box-shadow:0 0 0 1px #8b5cf685,0 0 16px #f472b67a}}
      .mk-shop-series-preview[data-preview-kind="quiz"]{background:radial-gradient(circle,#fff6c8,#ffd6ef)}.mk-shop-series-preview[data-preview-kind="quiz"] span{font-size:1.5rem;animation:mk-shop-preview-pop 1.2s infinite}
      .mk-shop-preview-concept-card{display:grid;width:76%;gap:.18rem;padding:.48rem .58rem;text-align:left}.mk-shop-preview-concept-card strong{font-size:.62rem}.mk-shop-preview-concept-card small{font-size:.43rem;opacity:.68}.mk-shop-preview-concept-card em{font-size:.42rem;font-style:normal;font-weight:800}
      .mk-shop-series-preview[data-preview-variant="glass-lab"] .mk-shop-preview-concept-card{background:#ffffff77;border:1px solid #8be5ff;border-radius:12px;box-shadow:inset 0 0 0 1px #fff,0 10px 22px #0ea5e922;backdrop-filter:blur(8px)}
      .mk-shop-series-preview[data-preview-variant="cyber-hud"] .mk-shop-preview-concept-card{color:#d9ffff;background:#071c28;border:1px solid #22d3ee;border-radius:3px;box-shadow:inset 0 0 15px #06b6d433}
      .mk-shop-series-preview[data-preview-variant="study-notes"] .mk-shop-preview-concept-card{color:#3f3213;background:repeating-linear-gradient(#fff9d7 0 18px,#b9d9ff 19px);border:1px solid #e0b44c;box-shadow:4px 5px 0 #cf9d3b22;transform:rotate(-1deg)}
      .mk-shop-series-preview[data-preview-variant="manga-panel"] .mk-shop-preview-concept-card{color:#111;background:#fff;border:3px solid #111;box-shadow:5px 5px 0 #111}
      .mk-shop-series-preview[data-preview-variant="cosmic-orbit"] .mk-shop-preview-concept-card{color:#eef4ff;background:radial-gradient(circle at 80% 20%,#fff 0 1px,transparent 2px),#16152f;border:1px solid #8b5cf6;border-radius:12px;box-shadow:0 0 16px #8b5cf644}
      .mk-shop-series-preview[data-preview-variant="blueprint-desk"] .mk-shop-preview-concept-card{color:#e0f2fe;background:linear-gradient(rgba(56,189,248,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(56,189,248,.14) 1px,transparent 1px),#0c4a6e;background-size:16px 16px;border:1px solid #38bdf8}
      .mk-shop-series-preview[data-preview-variant="forest-journal"] .mk-shop-preview-concept-card{color:#29431f;background:#e5edc6;border:1px solid #65a30d;box-shadow:inset 5px 0 #4d7c0f,4px 5px 0 #36531422}
      .mk-shop-series-preview[data-preview-variant="sunset-glass"] .mk-shop-preview-concept-card{color:#4c1d3d;background:linear-gradient(135deg,#fed7aa,#f9a8d4,#c4b5fd);border:1px solid #fb7185;border-radius:12px}
      .mk-shop-series-preview[data-preview-variant="retro-computer"] .mk-shop-preview-concept-card{color:#86efac;background:#052e16;border:2px solid #22c55e;border-radius:3px;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-variant="minimal-ink"] .mk-shop-preview-concept-card{color:#111;background:#fff;border:1px solid #111;box-shadow:4px 4px 0 #111}
      .mk-shop-preview-notification{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:.5rem;width:80%;padding:.48rem .55rem;text-align:left}.mk-shop-preview-notification i{font-style:normal;font-size:1rem}.mk-shop-preview-notification span{display:grid;gap:.12rem}.mk-shop-preview-notification strong{font-size:.58rem}.mk-shop-preview-notification small{font-size:.42rem;opacity:.68}
      .mk-shop-series-preview[data-preview-variant="neon-toast"] .mk-shop-preview-notification{color:#eaffff;background:#10162e;border:1px solid #22d3ee;border-radius:11px;box-shadow:0 0 13px #22d3ee55}
      .mk-shop-series-preview[data-preview-variant="royal-letter"] .mk-shop-preview-notification{color:#5a1732;background:#fff0c9;border:1px solid #9f3157;border-left:5px solid #8a1f43;border-radius:6px}
      .mk-shop-series-preview[data-preview-variant="holo-message"] .mk-shop-preview-notification{color:#352545;background:linear-gradient(120deg,#d9fbff,#f7cfff,#fff7ba);border:1px solid #fff;border-radius:12px}
      .mk-shop-series-preview[data-preview-variant="forest-sprite"] .mk-shop-preview-notification{color:#14563f;background:#dfffee;border:1px solid #24b58a;border-radius:12px;box-shadow:0 7px 15px #16a36e22}
      .mk-shop-series-preview[data-preview-variant="arcade-alert"] .mk-shop-preview-notification{color:#fff;background:#17152f;border:3px solid #facc15;box-shadow:4px 4px 0 #ec4899;font-family:ui-monospace,monospace}
      .mk-shop-series-preview[data-preview-variant="cloud-note"] .mk-shop-preview-notification{color:#0c4a6e;background:#e0f2fe;border:1px solid #7dd3fc;border-radius:12px;box-shadow:0 7px 15px #38bdf833}
      .mk-shop-series-preview[data-preview-variant="lava-signal"] .mk-shop-preview-notification{color:#fff7ed;background:linear-gradient(135deg,#1c0703,#7f1d1d);border:1px solid #fb923c;border-left:5px solid #f97316;border-radius:7px}
      .mk-shop-series-preview[data-preview-variant="frost-message"] .mk-shop-preview-notification{color:#172554;background:linear-gradient(135deg,#eff6ff,#bae6fd);border:1px solid #60a5fa;border-radius:12px}
      .mk-shop-series-preview[data-preview-variant="paper-plane"] .mk-shop-preview-notification{color:#4b3a20;background:#fffaf0;border:1px solid #c8a86b;border-radius:5px;box-shadow:4px 5px 0 #a1620722;transform:rotate(-.4deg)}
      .mk-shop-series-preview[data-preview-variant="constellation-ping"] .mk-shop-preview-notification{color:#eef2ff;background:radial-gradient(circle at 84% 22%,#fff 0 1px,transparent 2px),#17152f;border:1px solid #818cf8;border-radius:12px;box-shadow:0 0 14px #6366f155}
      .mk-shop-sound-sample{border:1px solid color-mix(in srgb,var(--md-default-fg-color) 18%,transparent);border-radius:999px;padding:.34rem .72rem;color:var(--md-default-fg-color);background:color-mix(in srgb,var(--md-default-bg-color) 92%,transparent);font:850 .55rem/1 system-ui;cursor:pointer}
      .mk-shop-sound-sample:hover{border-color:var(--md-accent-fg-color);background:color-mix(in srgb,var(--md-accent-fg-color) 10%,var(--md-default-bg-color))}
      .mk-shop-bgm-sample{display:grid;grid-template-columns:auto minmax(0,1fr);column-gap:.5rem;row-gap:.08rem;align-items:center;width:82%;padding:.48rem .62rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 16%,transparent);border-radius:13px;color:inherit;background:color-mix(in srgb,var(--md-default-bg-color) 88%,transparent);text-align:left;cursor:pointer}.mk-shop-bgm-sample>span{grid-row:1/3;display:grid;place-items:center;width:1.55rem;height:1.55rem;border-radius:50%;color:#fff;background:linear-gradient(135deg,#4f46e5,#ec4899)}.mk-shop-bgm-sample strong{font-size:.55rem}.mk-shop-bgm-sample small{font-size:.42rem;opacity:.62}
      .mk-shop-series-preview[data-preview-variant*="royal"],.mk-shop-series-preview[data-preview-variant="crown-drop"]{background:linear-gradient(135deg,#241509,#7a4511,#ffe29a)}
      .mk-shop-series-preview[data-preview-variant*="holo"],.mk-shop-series-preview[data-preview-variant="liquid-rainbow"]{background:linear-gradient(115deg,#9ff5ff,#ffb7ee,#fff3a0,#a8ffc8);background-size:220%;animation:mk-shop-rainbow 3s linear infinite}
      .mk-shop-series-preview[data-preview-variant*="sakura"],.mk-shop-series-preview[data-preview-variant*="petal"],.mk-shop-series-preview[data-preview-variant="heart-rain"]{background:linear-gradient(135deg,#fff0f7,#ffc7df)}
      .mk-shop-series-preview[data-preview-variant*="cosmic"],.mk-shop-series-preview[data-preview-variant*="galaxy"],.mk-shop-series-preview[data-preview-variant*="meteor"],.mk-shop-series-preview[data-preview-variant*="star-trail"]{color:#fff;background:radial-gradient(circle at 80% 20%,#fff 0 1px,transparent 2px),linear-gradient(135deg,#11152e,#4b1b72)}
      .mk-shop-series-preview[data-preview-variant*="cyber"],.mk-shop-series-preview[data-preview-variant*="neon"],.mk-shop-series-preview[data-preview-variant*="thunder"]{color:#dfffff;background:#071c28;border-color:#22d3ee;box-shadow:inset 0 0 20px #06b6d433}
      .mk-shop-series-preview[data-preview-variant*="pixel"],.mk-shop-series-preview[data-preview-variant*="arcade"]{color:#fff;background:#17152f;border:3px solid #facc15;border-radius:3px;box-shadow:5px 5px 0 #ec4899}
      .mk-shop-series-preview[data-preview-variant*="crystal"],.mk-shop-series-preview[data-preview-variant*="gem"]{background:linear-gradient(135deg,#dfffff,#8be5ff,#a78bfa)}
      .mk-shop-series-preview[data-preview-variant*="forest"],.mk-shop-series-preview[data-preview-variant*="fairy"]{background:linear-gradient(135deg,#e6fff0,#8de5bd)}
      @keyframes mk-shop-preview-pop{50%{transform:scale(1.25) rotate(8deg)}}@keyframes mk-shop-preview-float{50%{transform:translateY(-7px) rotate(-8deg)}}
      .mk-shop-celebration{position:fixed;inset:0;z-index:2147483550;display:grid;place-items:center;pointer-events:none;overflow:hidden}.mk-shop-celebration strong{font:900 clamp(2rem,8vw,6rem)/1 system-ui;color:#fff;text-shadow:0 0 18px #8b5cf6,0 4px 0 #4c1d95;animation:mk-shop-win 1.7s ease-out forwards}@keyframes mk-shop-win{0%{transform:scale(.2) rotate(-12deg);opacity:0}30%{transform:scale(1.1);opacity:1}100%{transform:scale(.92) translateY(-20px);opacity:0}}
      #mk-bgm-player{position:fixed;z-index:2147482100;right:max(10px,env(safe-area-inset-right));bottom:max(10px,env(safe-area-inset-bottom));display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;align-items:center;gap:.28rem;width:min(13.5rem,calc(100vw - 20px));padding:.30rem .36rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 17%,transparent);border-radius:12px;color:var(--md-default-fg-color);background:color-mix(in srgb,var(--md-default-bg-color) 94%,transparent);box-shadow:0 9px 24px rgba(15,23,42,.20);backdrop-filter:blur(14px)}
      #mk-bgm-player button,#mk-bgm-player select{color:inherit;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 16%,transparent);background:color-mix(in srgb,var(--md-default-fg-color) 6%,transparent);font:800 .55rem/1 system-ui}
      #mk-bgm-player button{display:grid;place-items:center;min-width:1.34rem;height:1.34rem;padding:0 .28rem;border-radius:999px;cursor:pointer}
      #mk-bgm-player .mk-bgm-main{min-width:0;display:block}.mk-bgm-title{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:900 .50rem/1.2 system-ui}.mk-bgm-meta{display:none}.mk-bgm-playlist{position:absolute;right:0;bottom:calc(100% + .42rem);display:none;width:min(17rem,calc(100vw - 20px));max-height:15rem;overflow:auto;padding:.44rem;border:1px solid color-mix(in srgb,var(--md-default-fg-color) 16%,transparent);border-radius:12px;background:var(--md-default-bg-color);box-shadow:0 14px 36px rgba(15,23,42,.24)}#mk-bgm-player.is-open .mk-bgm-playlist{display:grid;gap:.28rem}.mk-bgm-playlist-head{display:flex;align-items:center;justify-content:space-between;gap:.4rem;margin-bottom:.12rem}.mk-bgm-playlist-head select{height:1.42rem;border-radius:999px;padding:0 .38rem}.mk-bgm-track{display:grid!important;grid-template-columns:auto minmax(0,1fr);gap:.34rem!important;justify-items:start!important;width:100%;height:auto!important;min-height:1.9rem!important;padding:.30rem .36rem!important;border-radius:9px!important;text-align:left}.mk-bgm-track span{display:grid;gap:.06rem;min-width:0}.mk-bgm-track strong,.mk-bgm-track small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mk-bgm-track strong{font-size:.49rem}.mk-bgm-track small{font-size:.39rem;opacity:.6}.mk-bgm-track.is-current{border-color:#8b5cf6!important;background:color-mix(in srgb,#8b5cf6 13%,transparent)!important}.mk-bgm-credit{font-size:.40rem;color:inherit;opacity:.62;text-decoration:underline}
      @media(max-width:540px){#mk-bgm-player{grid-template-columns:auto minmax(0,1fr) auto;width:min(10.5rem,calc(100vw - 16px));right:max(8px,env(safe-area-inset-right));bottom:max(8px,env(safe-area-inset-bottom));padding:.26rem .30rem}#mk-bgm-player .mk-bgm-next{display:none}}
      @media(prefers-reduced-motion:reduce){.mk-shop-fx-particle,.mk-shop-series-preview span,.mk-shop-preview-mastery,.mk-shop-preview-mastery button,.mk-shop-preview-connections,.mk-shop-preview-connections *,.mk-shop-preview-connections *::before,.mk-shop-preview-connections *::after,.mk-shop-preview-finder-builder,.mk-shop-preview-finder-builder *,.mk-shop-preview-finder-builder *::before,.mk-shop-preview-finder-builder *::after,.mk-shop-preview-sidepanel,.mk-shop-preview-sidepanel *,.mk-shop-preview-sidepanel *::before,.mk-shop-preview-sidepanel *::after,.mk-shop-celebration strong,#${PROGRESS_ID}>span,#${PROGRESS_ID}>span::after{animation:none!important}}
    `;(document.head||root).appendChild(style);}
function fxLayer(){let layer=document.querySelector(".mk-shop-fx-layer");if(!layer){layer=document.createElement("div");layer.className="mk-shop-fx-layer";document.body.appendChild(layer);}
return layer;}
function burst(target,symbols,count=10){if(!target||!symbols)return;const rect=target.getBoundingClientRect();const layer=fxLayer();for(let i=0;i<count;i+=1){const p=document.createElement("i");p.className="mk-shop-fx-particle";p.textContent=symbols[i%symbols.length];p.style.setProperty("--x",`${rect.left + rect.width / 2}px`);p.style.setProperty("--y",`${rect.top + rect.height / 2}px`);p.style.setProperty("--dx",`${(Math.random() - .5) * 150}px`);p.style.setProperty("--dy",`${-30 - Math.random() * 120}px`);p.style.setProperty("--rot",`${(Math.random() - .5) * 400}deg`);p.style.setProperty("--size",`${14 + Math.random() * 15}px`);layer.appendChild(p);setTimeout(()=>p.remove(),1000);}}
const reactionSymbols={coin_burst:["🟡","✦"],heart_rain:["❤","♡"],thunder_hit:["⚡","✦"],petal_pop:["🌸","✿"],galaxy_pulse:["✦","🪐","•"],prism_pop:["🔷","✦","◇"],bubble_beat:["🫧","○","◌"],flame_charge:["🔥","✦"],snow_spark:["❄️","✧"],lucky_clover:["🍀","✦"]};function suffix(attr,prefix){return String(root.getAttribute(attr)||"").replace(`${prefix}_`,"");}
let progressRaf=0;let progressGeometryDirty=true;let progressMax=1;let progressTop=-1;let progressLastLabel=-1;let progressResizeObserver=null;function renderProgress(){const active=root.hasAttribute("data-mk-reading-progress");let bar=document.getElementById(PROGRESS_ID);if(!active){if(bar)bar.remove();progressLastLabel=-1;return;}
if(!bar){bar=document.createElement("div");bar.id=PROGRESS_ID;bar.setAttribute("aria-label","Reading progress");bar.innerHTML='<span></span><b><input aria-hidden="true" tabindex="-1" readonly value="0%"></b>';document.body.appendChild(bar);progressGeometryDirty=true;}
if(progressGeometryDirty){const header=document.querySelector(".md-header");const tabs=document.querySelector(".md-tabs");let top=header?Math.max(0,header.getBoundingClientRect().bottom):0;if(tabs){const rect=tabs.getBoundingClientRect();if(rect.bottom>top&&rect.top<=top+4)top=rect.bottom;}
const nextTop=Math.round(top);if(nextTop!==progressTop){progressTop=nextTop;bar.style.setProperty("--mk-reading-bar-top",`${nextTop}px`);}
progressMax=Math.max(1,document.documentElement.scrollHeight-innerHeight);progressGeometryDirty=false;}
const percent=Math.min(100,Math.max(0,scrollY/progressMax*100));const fill=bar.firstElementChild;if(fill)fill.style.width=`${percent}%`;const rounded=Math.round(percent);if(rounded!==progressLastLabel){progressLastLabel=rounded;const label=bar.querySelector("b > input");const value=`${rounded}%`;if(label&&label.value!==value)label.value=value;}}
function scheduleProgress(geometryChanged){if(geometryChanged)progressGeometryDirty=true;if(progressRaf)return;progressRaf=requestAnimationFrame(()=>{progressRaf=0;renderProgress();});}
function observeProgressGeometry(){if(progressResizeObserver){try{progressResizeObserver.disconnect();}catch(_){}}
if(typeof ResizeObserver!=="function")return;progressResizeObserver=new ResizeObserver(()=>scheduleProgress(true));[document.querySelector(".md-header"),document.querySelector(".md-tabs"),document.querySelector(".md-main"),document.querySelector("article.md-content__inner")].filter(Boolean).forEach((node)=>{try{progressResizeObserver.observe(node);}catch(_){}});}
function playSound(kind){if(!kind)return;try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const ctx=playSound.ctx||(playSound.ctx=new Ctx());const osc=ctx.createOscillator(),gain=ctx.createGain();const map={arcade:[220,"square",1.45,.16,.035],crystal:[880,"sine",1.6,.2,.028],cyber:[330,"sawtooth",2.1,.15,.026],magic:[660,"sine",1.8,.24,.025],minimal:[150,"sine",1.18,.1,.022],typewriter:[430,"square",.72,.075,.026],wood:[190,"triangle",.62,.13,.032],water:[780,"sine",.48,.22,.028],temple_bell:[520,"sine",2,.55,.024],sci_fi:[280,"sawtooth",3.2,.2,.024],soft_piano:[440,"sine",.76,.42,.026],bamboo:[245,"triangle",.54,.12,.036],bubble:[720,"sine",1.9,.16,.028],camera:[980,"square",.42,.07,.022],vinyl:[170,"sawtooth",.92,.11,.018]};const cfg=map[kind]||map.minimal;osc.type=cfg[1];osc.frequency.setValueAtTime(cfg[0],ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(40,cfg[0]*cfg[2]),ctx.currentTime+cfg[3]*.78);gain.gain.setValueAtTime(cfg[4],ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+cfg[3]);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+cfg[3]+.02);}catch(_){}}
function shopScriptBaseUrl(){try{const script=Array.from(document.scripts||[]).find((node)=>/\/javascripts\/cosmetic-fx\.js(?:\?|$)/.test(String(node.src||"")));if(script&&script.src)return new URL("../",script.src);}catch(_){}
return new URL("./",location.href);}
function shopAssetUrl(path){try{return new URL(String(path||"").replace(/^\/+/,""),shopScriptBaseUrl()).href;}
catch(_){return String(path||"");}}
function readBgmState(){try{const state=JSON.parse(localStorage.getItem(BGM_STATE_KEY)||"{}");return state&&typeof state==="object"?state:{};}catch(_){return{};}}
function writeBgmState(patch){const next=Object.assign({},readBgmState(),patch&&typeof patch==="object"?patch:{});try{localStorage.setItem(BGM_STATE_KEY,JSON.stringify(next));}catch(_){}
return next;}
function bgmCatalog(){try{const api=window.MkAccountData||null;const rows=api&&typeof api.shopCatalog==="function"?api.shopCatalog():[];return(Array.isArray(rows)?rows:[]).filter((item)=>item&&item.bgmTrack&&item.bgmUrl);}catch(_){return[];}}
function availableBgmTracks(){const api=window.MkAccountData||null;const catalog=bgmCatalog();let inventory={owned:{},activeTrials:[]};try{if(api&&typeof api.getShopInventory==="function")inventory=api.getShopInventory()||inventory;}catch(_){}
try{if(api&&typeof api.getActiveShopTrials==="function")inventory.activeTrials=api.getActiveShopTrials()||[];}catch(_){}
const trialId=String(root.getAttribute("data-mk-bgm-track")||"");return catalog.filter((item)=>{if(inventory&&inventory.owned&&inventory.owned[item.id])return true;if(item.id===trialId)return true;return Array.isArray(inventory.activeTrials)&&inventory.activeTrials.some((row)=>row&&!row.muted&&String(row.itemId||"")===String(item.id||""));});}
function bgmAudio(){if(!window.__mkBgmAudio){const audio=new Audio();audio.preload="none";audio.volume=Math.min(.8,Math.max(.05,Number(readBgmState().volume||.32)));audio.addEventListener("play",()=>renderBgmPlayer());audio.addEventListener("pause",()=>renderBgmPlayer());audio.addEventListener("ended",()=>playAdjacentBgm(1,true));window.__mkBgmAudio=audio;}
return window.__mkBgmAudio;}
function currentBgmTrack(tracks){const rows=tracks||availableBgmTracks();const state=readBgmState();return rows.find((item)=>String(item.id)===String(state.itemId||""))||rows[0]||null;}
function selectBgm(itemId,autoplay){const tracks=availableBgmTracks();const track=tracks.find((item)=>String(item.id)===String(itemId||""))||tracks[0]||null;if(!track){renderBgmPlayer();return;}
const audio=bgmAudio();const src=shopAssetUrl(track.bgmUrl);if(audio.src!==src){audio.pause();audio.src=src;audio.currentTime=0;}
writeBgmState({itemId:track.id});renderBgmPlayer();if(autoplay)audio.play().catch(()=>{});}
function playAdjacentBgm(direction,autoplay){const tracks=availableBgmTracks();if(!tracks.length)return;const state=readBgmState();const current=currentBgmTrack(tracks);let next=null;if(String(state.mode||"sequence")==="random"&&tracks.length>1){const pool=tracks.filter((item)=>!current||item.id!==current.id);next=pool[Math.floor(Math.random()*pool.length)]||tracks[0];}else{const at=Math.max(0,tracks.findIndex((item)=>current&&item.id===current.id));next=tracks[(at+Number(direction||1)+tracks.length)%tracks.length];}
selectBgm(next&&next.id,autoplay);}
function toggleBgm(){const tracks=availableBgmTracks();if(!tracks.length)return;const audio=bgmAudio();const current=currentBgmTrack(tracks);const desired=current?shopAssetUrl(current.bgmUrl):"";if(!audio.src||audio.src!==desired)selectBgm(current.id,true);else if(audio.paused)audio.play().catch(()=>{});else audio.pause();}
function renderBgmPlayer(){const tracks=availableBgmTracks();let player=document.getElementById(BGM_PLAYER_ID);if(!tracks.length){if(player)player.remove();try{if(window.__mkBgmAudio)window.__mkBgmAudio.pause();}catch(_){}
return;}
if(!player){player=document.createElement("div");player.id=BGM_PLAYER_ID;player.innerHTML=`<button type="button" class="mk-bgm-play" aria-label="Play background music">▶</button><div class="mk-bgm-main"><strong class="mk-bgm-title"></strong><small class="mk-bgm-meta"></small></div><button type="button" class="mk-bgm-next" aria-label="Next background track">›</button><div class="mk-bgm-more"><button type="button" class="mk-bgm-list-toggle" aria-label="Open background music playlist">☰</button><div class="mk-bgm-playlist"><div class="mk-bgm-playlist-head"><strong>Background music</strong><select aria-label="Playlist order"><option value="sequence">In order</option><option value="random">Random</option></select></div><div class="mk-bgm-tracks"></div><a class="mk-bgm-credit" href="${shopAssetUrl("bgm-credits.html")}">Music credits · CC BY / CC0</a></div></div>`;player.querySelector(".mk-bgm-play").addEventListener("click",toggleBgm);player.querySelector(".mk-bgm-next").addEventListener("click",()=>playAdjacentBgm(1,true));player.querySelector(".mk-bgm-list-toggle").addEventListener("click",()=>player.classList.toggle("is-open"));player.querySelector("select").addEventListener("change",(event)=>writeBgmState({mode:event.target.value==="random"?"random":"sequence"}));document.body.appendChild(player);}
const current=currentBgmTrack(tracks);const audio=bgmAudio();player.querySelector(".mk-bgm-title").textContent=current?current.title:"Background music";player.querySelector(".mk-bgm-meta").textContent=current?`${current.bgmCulture || "Instrumental"} · ${current.bgmArtist || "Music artist"}`:"";player.querySelector(".mk-bgm-play").textContent=audio.paused?"▶":"❚❚";player.querySelector(".mk-bgm-play").setAttribute("aria-label",audio.paused?"Play background music":"Pause background music");player.querySelector("select").value=readBgmState().mode==="random"?"random":"sequence";const list=player.querySelector(".mk-bgm-tracks");list.innerHTML="";tracks.forEach((track)=>{const button=document.createElement("button");button.type="button";button.className=`mk-bgm-track${current && current.id === track.id ? " is-current" : ""}`;button.innerHTML=`<b>${current && current.id === track.id && !audio.paused ? "❚❚" : "▶"}</b><span><strong>${track.title}</strong><small>${track.bgmCulture || "Instrumental"}</small></span>`;button.addEventListener("click",()=>{selectBgm(track.id,true);player.classList.remove("is-open");});list.appendChild(button);});}
function playBgmSample(itemId){const track=bgmCatalog().find((item)=>String(item.id)===String(itemId||""));if(!track)return;try{const main=window.__mkBgmAudio;if(main&&!main.paused)main.pause();const old=window.__mkBgmSampleAudio;if(old){old.pause();if(old.__mkItemId===track.id&&old.currentTime>0){window.__mkBgmSampleAudio=null;return;}}
const sample=new Audio(shopAssetUrl(track.bgmUrl));sample.preload="metadata";sample.volume=.34;sample.__mkItemId=track.id;window.__mkBgmSampleAudio=sample;sample.play().catch(()=>{});window.setTimeout(()=>{if(window.__mkBgmSampleAudio===sample){sample.pause();sample.currentTime=0;window.__mkBgmSampleAudio=null;}},20000);}catch(_){}}
let lastCelebrateAt=0;function celebrate(){if(Date.now()-lastCelebrateAt<500)return;lastCelebrateAt=Date.now();const kind=suffix("data-mk-quiz-celebration","quiz");if(!kind)return;const labels={victory_fireworks:"🎆 QUIZ COMPLETE 🎆",pixel_victory:"★ LEVEL CLEAR ★",crown_drop:"♛ CHAMPION ♛",meteor_shower:"☄ STELLAR RESULT ☄",confetti_cannon:"🎉 GREAT WORK 🎉",disco_finish:"🪩 DISCO FINISH 🪩",sakura_shower:"🌸 QUIZ BLOOM 🌸",lightning_rank:"⚡ RANK UP ⚡",ocean_splash:"🌊 CLEAN FINISH 🌊",aurora_crown:"👑 AURORA CROWN 👑"};const box=document.createElement("div");box.className="mk-shop-celebration";box.innerHTML=`<strong>${labels[kind] || "QUIZ COMPLETE"}</strong>`;document.body.appendChild(box);const symbols={victory_fireworks:["🎆","✦","•"],pixel_victory:["■","◆","★"],crown_drop:["♛","✦","◆"],meteor_shower:["☄","✦"],confetti_cannon:["🎉","▰","●"],disco_finish:["🪩","◆","✦"],sakura_shower:["🌸","✿","♡"],lightning_rank:["⚡","✦","★"],ocean_splash:["🌊","💧","✦"],aurora_crown:["👑","✦","◇"]};burst(document.body,symbols[kind]||["🎉","✦","◆"],26);setTimeout(()=>box.remove(),1900);}
document.addEventListener("click",(event)=>{const preview=event.target&&event.target.closest?event.target.closest(".mk-shop-series-preview"):null;if(preview){const kind=String(preview.getAttribute("data-preview-kind")||"");const variant=String(preview.getAttribute("data-preview-variant")||"").replace(/-/g,"_");if(kind==="reaction")burst(preview,reactionSymbols[variant]||["✦","❤"],10);if(kind==="quiz")burst(preview,["🎉","✦","◆"],16);if(kind==="sound"){playSound(variant);return;}
if(kind==="bgm"){const button=event.target&&event.target.closest?event.target.closest("[data-bgm-item-id]"):null;if(button)playBgmSample(button.getAttribute("data-bgm-item-id")||"");return;}}
const target=event.target&&event.target.closest?event.target.closest("button,a,[role='button']"):null;if(!target)return;const reaction=target.closest(".mk-comment-reaction");if(reaction){const card=reaction.closest(".mk-comment-card");const effectId=String(card&&card.getAttribute("data-reaction-effect")||(card&&card.getAttribute("data-comment-owner")==="1"?root.getAttribute("data-mk-reaction-effect")||"":""));const kind=effectId.replace("reaction_","");if(kind)burst(reaction,reactionSymbols[kind],12);}
playSound(suffix("data-mk-sound-pack","sound"));},true);document.addEventListener("mk:ai-quiz-completed",celebrate);window.addEventListener("mk:ai-quiz-completed",celebrate);window.addEventListener("mk:bgm-select",(event)=>{const detail=event&&event.detail||{};selectBgm(detail.itemId||"",detail.autoplay!==false);});window.addEventListener("mk-shop-inventory-change",()=>window.setTimeout(renderBgmPlayer,80));window.addEventListener("mk-shop-trial-change",()=>window.setTimeout(renderBgmPlayer,80));addEventListener("scroll",()=>scheduleProgress(false),{passive:true});addEventListener("resize",()=>scheduleProgress(true),{passive:true});document.addEventListener("DOMContentSwitch",()=>{observeProgressGeometry();scheduleProgress(true);});new MutationObserver(()=>{scheduleProgress(true);renderBgmPlayer();}).observe(root,{attributes:true,attributeFilter:["data-mk-reading-progress","data-mk-bgm-track"]});ensureStyles();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{observeProgressGeometry();scheduleProgress(true);renderBgmPlayer();},{once:true});else{observeProgressGeometry();scheduleProgress(true);renderBgmPlayer();}})();