(function(){"use strict";const KEY="mk_perf_probe_enabled_v1";const START=(performance&&performance.now)?performance.now():Date.now();const params=new URLSearchParams(String(location.search||""));const param=params.get("mkperf");try{if(param==="0"||param==="off"||param==="false"){sessionStorage.removeItem(KEY);localStorage.removeItem(KEY);}else if(param==="1"||param==="on"||param==="true"){sessionStorage.setItem(KEY,"1");}else if(param==="stick"){localStorage.setItem(KEY,"1");}}catch(_){}
let enabled=false;try{enabled=param==="1"||param==="on"||param==="true"||param==="stick"||sessionStorage.getItem(KEY)==="1"||localStorage.getItem(KEY)==="1";}catch(_){enabled=param==="1"||param==="on"||param==="true"||param==="stick";}
if(!enabled)return;const state={href:location.href,userAgent:navigator.userAgent,startedAt:new Date().toISOString(),marks:[],fetches:[],xhr:[],storage:[],resources:[],longTasks:[],paints:[],rafGaps:[],classChanges:[],errors:[],counters:Object.create(null)};function now(){return(performance&&performance.now)?performance.now():Date.now();}
function rel(t){return Math.round((Number(t==null?now():t)-START)*10)/10;}
function cleanUrl(value){try{const u=new URL(String(value||""),location.href);if(u.origin===location.origin)return u.pathname.replace(/^\/+/,"")+u.search;return u.origin+u.pathname;}catch(_){return String(value||"").slice(0,240);}}
function clip(value,n){const s=String(value==null?"":value);return s.length>n?s.slice(0,n-1)+"...":s;}
function add(bucket,row,limit){const arr=state[bucket];if(!arr)return row;arr.push(row);if(arr.length>(limit||400))arr.splice(0,arr.length-(limit||400));return row;}
function mark(name,detail){return add("marks",{t:rel(),name:String(name||""),detail:detail||null,path:location.pathname},800);}
function count(name){state.counters[name]=(state.counters[name]||0)+1;}
function observePerformance(){if(typeof PerformanceObserver!=="function")return;function observe(type,cb){try{const po=new PerformanceObserver((list)=>{try{list.getEntries().forEach(cb);}catch(err){recordError("po:"+type,err);}});po.observe({type,buffered:true});}catch(_){}}
observe("navigation",(e)=>{mark("navigation",{duration:Math.round(e.duration||0),domContentLoaded:Math.round(e.domContentLoadedEventEnd||0),load:Math.round(e.loadEventEnd||0),transferSize:e.transferSize||0});});observe("paint",(e)=>{add("paints",{t:rel(e.startTime),name:e.name},40);});observe("largest-contentful-paint",(e)=>{add("paints",{t:rel(e.startTime),name:"largest-contentful-paint",size:e.size||0,element:e.element&&e.element.tagName?e.element.tagName.toLowerCase():""},40);});observe("longtask",(e)=>{const attribution=Array.prototype.slice.call(e.attribution||[]).map((a)=>({name:a.name||"",type:a.entryType||"",container:a.containerType||"",src:cleanUrl(a.containerSrc||"")}));add("longTasks",{t:rel(e.startTime),duration:Math.round((e.duration||0)*10)/10,attribution},300);});observe("resource",(e)=>{const kind=e.initiatorType||"";const name=cleanUrl(e.name||"");if(!/script|fetch|xmlhttprequest|css|link/i.test(kind)&&!/\.(js|css|json)(\?|$)/i.test(name))return;add("resources",{t:rel(e.startTime),name,type:kind,duration:Math.round((e.duration||0)*10)/10,transferSize:e.transferSize||0,encodedBodySize:e.encodedBodySize||0,decodedBodySize:e.decodedBodySize||0},500);});}
function wrapFetch(){if(typeof window.fetch!=="function"||window.fetch.__mkPerfWrapped)return;const original=window.fetch;const wrapped=function(){const started=now();const input=arguments[0];const url=cleanUrl(input&&input.url?input.url:input);count("fetch");mark("fetch:start",{url});return original.apply(this,arguments).then((res)=>{add("fetches",{t:rel(started),url,duration:Math.round((now()-started)*10)/10,status:res&&res.status,ok:!!(res&&res.ok)},300);return res;},(err)=>{add("fetches",{t:rel(started),url,duration:Math.round((now()-started)*10)/10,error:clip(err&&(err.message||err),180)},300);throw err;});};wrapped.__mkPerfWrapped=true;window.fetch=wrapped;}
function wrapXhr(){if(!window.XMLHttpRequest||XMLHttpRequest.prototype.__mkPerfWrapped)return;const proto=XMLHttpRequest.prototype;const open=proto.open;const send=proto.send;proto.open=function(method,url){try{this.__mkPerf={method:String(method||"GET"),url:cleanUrl(url)};}catch(_){}
return open.apply(this,arguments);};proto.send=function(){const meta=this.__mkPerf||{};const started=now();count("xhr");try{this.addEventListener("loadend",()=>{add("xhr",{t:rel(started),method:meta.method||"",url:meta.url||"",duration:Math.round((now()-started)*10)/10,status:this.status},200);});}catch(_){}
return send.apply(this,arguments);};proto.__mkPerfWrapped=true;}
function wrapStorage(){if(!window.Storage||Storage.prototype.__mkPerfWrapped)return;const proto=Storage.prototype;["getItem","setItem","removeItem","clear"].forEach((method)=>{const original=proto[method];if(typeof original!=="function")return;proto[method]=function(){const started=now();let ok=true;try{return original.apply(this,arguments);}catch(err){ok=false;throw err;}finally{const duration=now()-started;const key=method==="clear"?"*":String(arguments[0]||"");const value=method==="setItem"?String(arguments[1]||""):"";const bytes=value.length;if(duration>=2||bytes>=50000||/^mk_account_|^mk_hot_|concept_mastery|quiz|activity|sync/i.test(key)){add("storage",{t:rel(started),area:this===localStorage?"local":(this===sessionStorage?"session":"storage"),method,key:clip(key,120),bytes,duration:Math.round(duration*10)/10,ok},400);}}};});proto.__mkPerfWrapped=true;}
function observeEvents(){["DOMContentLoaded","load","pageshow","pagehide","visibilitychange","DOMContentSwitch","navigation:load","mk:sidebar-sort-done","mk:sidebar-sort-rendered","mk:mastery-widget-ready","mk:learning-path-ready","mk:random-tabs-ready","mk-local-activity-change","mk-account-sync-start","mk-account-sync-end","mk:site-motion-change","fb:ready","aiq:ready"].forEach((eventName)=>{const target=/^(load|pageshow|pagehide|visibilitychange)$/.test(eventName)?window:document;try{target.addEventListener(eventName,(ev)=>{mark("event:"+eventName,{hidden:!!document.hidden,persisted:!!(ev&&ev.persisted)});},{passive:true,capture:true});}catch(_){}});}
function observeHtmlClasses(){const root=document.documentElement;let prev=root.className||"";try{const mo=new MutationObserver(()=>{const next=root.className||"";if(next===prev)return;const row={t:rel(),added:next.split(/\s+/).filter((x)=>x&&prev.split(/\s+/).indexOf(x)<0),removed:prev.split(/\s+/).filter((x)=>x&&next.split(/\s+/).indexOf(x)<0)};if(row.added.length||row.removed.length)add("classChanges",row,200);prev=next;});mo.observe(root,{attributes:true,attributeFilter:["class"]});}catch(_){}}
function observeRafGaps(){if(typeof requestAnimationFrame!=="function")return;let last=0;function tick(ts){if(last&&ts-last>80){add("rafGaps",{t:rel(ts),gap:Math.round((ts-last)*10)/10},200);}
last=ts;requestAnimationFrame(tick);}
requestAnimationFrame(tick);}
function recordError(source,err){add("errors",{t:rel(),source,message:clip(err&&(err.message||err),240)},100);}
function report(){const byScript={};state.resources.forEach((r)=>{if(!/\.js(\?|$)/i.test(r.name))return;byScript[r.name]=byScript[r.name]||{count:0,duration:0,transferSize:0,decodedBodySize:0};byScript[r.name].count+=1;byScript[r.name].duration+=Number(r.duration||0);byScript[r.name].transferSize+=Number(r.transferSize||0);byScript[r.name].decodedBodySize+=Number(r.decodedBodySize||0);});const scriptResources=Object.keys(byScript).map((name)=>({name,count:byScript[name].count,duration:Math.round(byScript[name].duration*10)/10,transferSize:byScript[name].transferSize,decodedBodySize:byScript[name].decodedBodySize})).sort((a,b)=>b.duration-a.duration);return{meta:{href:state.href,currentHref:location.href,startedAt:state.startedAt,generatedAt:new Date().toISOString(),userAgent:state.userAgent,perfVariant:window.__MK_PERF_VARIANT||null},summary:{elapsed:rel(),counters:state.counters,longTaskCount:state.longTasks.length,longTaskTotal:Math.round(state.longTasks.reduce((sum,x)=>sum+Number(x.duration||0),0)*10)/10,worstLongTasks:state.longTasks.slice().sort((a,b)=>b.duration-a.duration).slice(0,15),worstFetches:state.fetches.slice().sort((a,b)=>b.duration-a.duration).slice(0,15),worstStorage:state.storage.slice().sort((a,b)=>b.duration-a.duration).slice(0,20),worstRafGaps:state.rafGaps.slice().sort((a,b)=>b.gap-a.gap).slice(0,15),scriptResources},raw:state};}
function logSummary(label){const r=report();try{console.groupCollapsed("[mkperf] "+label+" "+Math.round(r.summary.elapsed)+"ms");console.table(r.summary.scriptResources.slice(0,15));console.table(r.summary.worstLongTasks.slice(0,10));console.table(r.summary.worstFetches.slice(0,10));console.table(r.summary.worstStorage.slice(0,10));console.info("Full report:",r);console.info("Copy JSON with: await window.__mkPerf.copy()");console.groupEnd();}catch(_){}}
async function copyReport(){const text=JSON.stringify(report(),null,2);if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text);console.info("[mkperf] report copied to clipboard");return text.length;}
console.info(text);return text.length;}
window.__mkPerf={state,mark,report,copy:copyReport,log:()=>logSummary("manual")};window.addEventListener("error",(ev)=>recordError("error",ev&&(ev.error||ev.message)),true);window.addEventListener("unhandledrejection",(ev)=>recordError("unhandledrejection",ev&&ev.reason),true);mark("probe-enabled");observePerformance();wrapFetch();wrapXhr();wrapStorage();observeEvents();observeHtmlClasses();observeRafGaps();setTimeout(()=>logSummary("5s"),5000);setTimeout(()=>logSummary("12s"),12000);window.addEventListener("pagehide",()=>logSummary("pagehide"),{capture:true});})();