(function(){function __mkFetchSearchIndex(url,init){const shared=window.__mkFetchJsonShared;if(typeof shared==="function")return shared(url,init);return fetch(url,init).then(function(r){return r&&r.ok?r.json():null;});}
const STORAGE_SCOPE="random_scope_v3";const STORAGE_LAST_NON_RANDOM="random_last_non_random_v3";const RANDOM_ROUTE_PENDING_KEY="random_route_pending_v1";const GPS_ROUTE_KEY="lp_gps_route_v1";const GPS_ROUTE_TICKET_KEY="lp_gps_route_ticket_v1";const GRAPH_URL="assets/concept-graph.json";const AI_INDEX_URL="assets/ai-mcq-index.json";const AI_QUIZ_SESSIONS_KEY="concept_quiz_sessions_v1";const RANDOM_AI_RECENT_EXCLUDE_MS=30*24*60*60*1000;const MASTERY_KEY="concept_mastery_v1";const ACCOUNT_FILE_KEY="mk_account_data_file_v1";const PENDING_XP_QUEUE_KEY="mk_xp_pending_activity_queue_v1";const RANDOM_AI_NOTICE_KEY="random_ai_notice_v1";const RANDOM_MODE_KEY="random_review_mode_kind_v1";const RANDOM_AI_NAV_FLAG="random_ai_nav_flag_v1";const RANDOM_AI_OPENED_KEY="random_ai_opened_arrival_v1";const RANDOM_AI_ENTRY_URL_KEY="random_ai_entry_url_v1";const RANDOM_AI_ONLY_UNTESTED_KEY="random_ai_only_untested_after_check_v1";const RANDOM_ARRIVAL_ID_KEY="random_arrival_id_v1";const RANDOM_ARRIVAL_LOC_KEY="random_arrival_loc_v1";const SELF_TEST_MODE_KEY="random_review_mode_v1";const SELF_TEST_NAV_FLAG="random_review_nav_flag_v1";function queueRandomXp(metric,detail){try{const key="mk_xp_pending_activity_queue_v1";const arr=JSON.parse(localStorage.getItem(key)||"[]");arr.push({metric,details:detail||{},opts:{scope:`${metric}:${detail && (detail.mode || detail.scope || detail.path || detail.eventName || Date.now())}`,throttleMs:0},queuedAt:Date.now(),source:"random-page-fallback"});localStorage.setItem(key,JSON.stringify(arr.slice(-300)));}catch(_){}}
function recordRandomXp(metric,detail){try{const d=Object.assign({source:"random-page",path:location.pathname||""},detail||{});if(window.MkXpActivity&&typeof window.MkXpActivity.record==="function"){window.MkXpActivity.record(metric,d);return;}
if(metric==="random_browse_start"&&window.MkXpActivity&&typeof window.MkXpActivity.recordRandomBrowseStarted==="function"){window.MkXpActivity.recordRandomBrowseStarted(d);return;}
if(metric==="guided_study_start"&&window.MkXpActivity&&typeof window.MkXpActivity.recordGuidedStudyStarted==="function"){window.MkXpActivity.recordGuidedStudyStarted(d);return;}
if(window.MkAccountData&&typeof window.MkAccountData.recordActivity==="function"){window.MkAccountData.recordActivity(metric,d,{scope:`${metric}:${d.mode || d.scope || d.path || d.eventName || Date.now()}`,throttleMs:0});return;}
queueRandomXp(metric,d);document.dispatchEvent(new CustomEvent("mk:xp-activity",{detail:Object.assign({metric},d)}));}catch(_){}}
function isCustomRandomPath(pathname){const p=String(pathname||"").toLowerCase();return p.includes("custom-random");}
function isTrueRandomPagePath(pathname){const p=String(pathname||"").toLowerCase();if(isCustomRandomPath(p))return false;return/(^|\/)random(\/|\.html$)/.test(p)||/(^|\/)random\/index\.html$/.test(p);}
function isTrueRandomHref(href){const h=String(href||"").toLowerCase();if(!h)return false;if(h.includes("custom-random"))return false;const clean=h.split("#")[0].split("?")[0];return/(^|\/)random(\/|\.html$)/.test(clean)||/(^|\/)random\/index\.html$/.test(clean);}
function getSiteRootUrl(){const script=document.querySelector('script[src*="assets/javascripts/bundle"]');const link=document.querySelector('link[href*="assets/stylesheets/main"]')||document.querySelector('link[href*="assets/stylesheets"]');const attr=script?script.getAttribute("src"):(link?link.getAttribute("href"):null);const assetUrl=attr?new URL(attr,document.baseURI):new URL(document.baseURI);const p=assetUrl.pathname;const idx=p.indexOf("/assets/");if(idx>=0){const rootPath=p.slice(0,idx+1);return assetUrl.origin+rootPath;}
const base=new URL(document.baseURI);if(!base.pathname.endsWith("/"))base.pathname+="/";return base.origin+base.pathname;}
function relPathFromSiteRoot(absPathname){const siteRoot=new URL(getSiteRootUrl());const rootPath=siteRoot.pathname.endsWith("/")?siteRoot.pathname:siteRoot.pathname+"/";let p=String(absPathname||window.location.pathname);if(p.startsWith(rootPath))p=p.slice(rootPath.length);p=p.replace(/^\/+/,"").replace(/\/+$/,"");return p;}
function splitSegs(relPath){return(relPath||"").split("/").filter(Boolean);}
function rememberLastNonRandom(){const now=window.location.pathname;if(!isTrueRandomPagePath(now)&&!isCustomRandomPath(now)){try{sessionStorage.setItem(STORAGE_LAST_NON_RANDOM,now);}catch(_){}}}
function isYearFolder(seg){const s=String(seg||"").toLowerCase();return/^year[-_ ]?\d+$/.test(s);}
function inferCourseScopeFromPath(absPathname){const rel=relPathFromSiteRoot(absPathname);const segs=splitSegs(rel);if(!segs.length)return"";const s0=segs[0];const s1=segs[1];if(isYearFolder(s0)){if(!s1)return"";if(String(s1).toLowerCase().endsWith(".html"))return"";return`${s0}/${s1}/`;}
if(String(s0||"").toLowerCase().endsWith(".html"))return"";return`${s0}/`;}
function storeScope(scope){try{sessionStorage.setItem(STORAGE_SCOPE,scope||"");}catch(_){}}
function readScope(){try{return sessionStorage.getItem(STORAGE_SCOPE)||"";}catch(_){return"";}}
async function loadSearchIndex(){const siteRoot=getSiteRootUrl();const url=new URL("search/search_index.json",siteRoot).toString();const j=await __mkFetchSearchIndex(url);if(!j)throw new Error("Cannot load search index at "+url);return j;}
function isConceptLocation(loc){const s0=String(loc||"");if(!s0)return false;const clean=s0.split("#")[0].replace(/^\/+/,"").replace(/\/+$/,"");if(!clean)return false;const low=clean.toLowerCase();if(!low.endsWith(".html"))return false;const base=(clean.split("/").pop()||"").toLowerCase();if(!base)return false;if(base==="index.html"||low.endsWith("/index.html"))return false;if(base==="404.html")return false;if(/^random[^\/]*\.html$/.test(base))return false;const badBases=new Set(["find.html","custom-random.html","trending.html","contributors.html","about.html","about-this-wiki.html"]);if(badBases.has(base))return false;if(low.includes("assets/"))return false;if(low.includes("/search/"))return false;if(low.includes("/find"))return false;if(low.includes("/trending"))return false;if(low.includes("/contributors"))return false;if(low.includes("/about"))return false;const segs=splitSegs(clean);return segs.length>=3;}
function tagsFromSearchDoc(doc){const values=[];const add=(value)=>{if(Array.isArray(value))values.push(...value);else if(typeof value==="string")values.push(value);};add(doc&&doc.tags);add(doc&&doc.tag);add(doc&&doc.meta&&doc.meta.tags);add(doc&&doc.meta&&doc.meta.tag);return values.map((value)=>String(value||"").trim().toLowerCase()).filter(Boolean);}
function isCoreCurriculumDoc(doc){const tags=tagsFromSearchDoc(doc);return!tags.includes("curriculum-enrichment")&&!tags.includes("curriculum-retired");}
function conceptCandidates(indexJson,scopePrefix){const docs=indexJson&&indexJson.docs?indexJson.docs:[];const scope=String(scopePrefix||"").replace(/^\/+/,"");return docs.filter(isCoreCurriculumDoc).map(d=>d&&d.location).filter(Boolean).map(String).filter(isConceptLocation).filter(loc=>{if(!scope)return true;const clean=loc.replace(/^\/+/,"");return clean.startsWith(scope);});}
function pickRandomFromList(candidates){const arr=Array.isArray(candidates)?candidates.filter(Boolean):[];if(!arr.length)return null;const i=Math.floor(Math.random()*arr.length);return arr[i];}
function pickWeightedRandom(items,weightFn){const arr=Array.isArray(items)?items.filter(Boolean):[];let total=0;const rows=arr.map((item)=>{const weight=Math.max(0,Number(typeof weightFn==="function"?weightFn(item):1)||0);total+=weight;return{item,weight};}).filter((row)=>row.weight>0);if(!rows.length||total<=0)return pickRandomFromList(arr);let target=Math.random()*total;for(const row of rows){target-=row.weight;if(target<=0)return row.item;}
return rows[rows.length-1].item;}
function pickRandomLocation(indexJson,scopePrefix,predicate){let candidates=conceptCandidates(indexJson,scopePrefix);if(typeof predicate==="function")candidates=candidates.filter(predicate);return pickRandomFromList(candidates);}
function toAbsoluteUrl(loc){const siteRoot=getSiteRootUrl();const cleanLoc=String(loc).replace(/^\//,"");return new URL(cleanLoc,siteRoot).toString().split("#")[0]+"#top";}
function normLoc(loc){return String(loc||"").split("#")[0].replace(/^\/+/,"").trim();}
function canonLoc(loc){const s0=normLoc(loc).replace(/\\/g,"/");if(!s0)return"";let s=s0.replace(/\/index\.html?$/i,"");s=s.replace(/\/+$/g,"");return s;}
function readLocalJson(key,fallback){try{const raw=localStorage.getItem(key);if(!raw)return fallback;const parsed=JSON.parse(raw);return parsed==null?fallback:parsed;}catch(_){return fallback;}}
function sessionPathAliases(loc){const out=new Set();const push=(value)=>{const raw=String(value||"").trim();if(!raw)return;const c=aiCanon(raw);if(c)out.add(c);try{if(/^[a-z]+:\/\//i.test(raw)){const u=new URL(raw,getSiteRootUrl());const rel=relPathFromSiteRoot(u.pathname);const r=aiCanon(rel);if(r)out.add(r);}}catch(_){}};push(loc);Array.from(out).forEach((base)=>{if(base&&base.endsWith(".html"))push(base.slice(0,-5));if(base&&!base.endsWith(".html"))push(base+".html");});return out;}
function pathMatchesLoc(path,loc){const a=sessionPathAliases(path);const b=sessionPathAliases(loc);for(const x of a){if(b.has(x))return true;}
return false;}
function rememberRandomAiNotice(message){try{if(message)sessionStorage.setItem(RANDOM_AI_NOTICE_KEY,String(message));else sessionStorage.removeItem(RANDOM_AI_NOTICE_KEY);}catch(_){}}
function clearGpsRouteState(){try{sessionStorage.removeItem(GPS_ROUTE_KEY);sessionStorage.removeItem(GPS_ROUTE_TICKET_KEY);}catch(_){}}
function writeGpsRouteTicket(loc){try{const to=normLoc(loc);if(!to){sessionStorage.removeItem(GPS_ROUTE_TICKET_KEY);return;}
sessionStorage.setItem(GPS_ROUTE_TICKET_KEY,JSON.stringify({ts:Date.now(),to}));}catch(_){}}
function readMasteryLevel(loc){try{const raw=localStorage.getItem("concept_mastery_v1");if(!raw)return null;const all=JSON.parse(raw);const rec=all&&typeof all==="object"?all[normLoc(loc)]:null;const m=rec&&typeof rec.m==="number"?rec.m:null;return(m===0||m===1||m===2||m===3)?m:null;}catch(_){return null;}}
function readMasteryRecord(loc){try{const raw=localStorage.getItem("concept_mastery_v1");if(!raw)return null;const all=JSON.parse(raw);if(!all||typeof all!=="object")return null;const key=normLoc(loc);if(all[key])return all[key];const target=canonLoc(key).toLowerCase();const found=Object.keys(all).find((k)=>canonLoc(k).toLowerCase()===target);return found?all[found]:null;}catch(_){return null;}}
function isUnvisitedConcept(loc){const rec=readMasteryRecord(loc);if(!rec||typeof rec!=="object")return true;const m=rec.m;const hasRating=m===0||m===1||m===2||m===3;const hasView=!!(rec.visited||Number(rec.viewCount||rec.visitCount||rec.lastViewed||rec.lastSeen||0)>0||(Array.isArray(rec.history)&&rec.history.some((h)=>{const kind=String(h&&(h.kind||h.type||h.event||h.action)||"").toLowerCase();return kind==="view"||kind==="visit"||kind==="seen";})));return!hasRating&&!hasView;}
function aiCanon(loc){let s=canonLoc(loc).replace(/\\/g,"/").toLowerCase();try{s=decodeURIComponent(s);}catch(_){}
return s;}
function aiKeyAliases(loc){const base=aiCanon(loc);const out=new Set();const push=(v)=>{const x=aiCanon(v);if(x)out.add(x);};push(base);if(base&&!base.endsWith(".html"))push(base+".html");if(base.endsWith(".html"))push(base.slice(0,-5));if(base.endsWith("/"))push(base.slice(0,-1));return out;}
async function loadAiIndexKeySet(){const siteRoot=getSiteRootUrl();const url=new URL(AI_INDEX_URL,siteRoot).toString();const res=await fetch(url,{credentials:"same-origin"});if(!res.ok)throw new Error("Cannot load AI quiz index at "+url);const index=await res.json();const concepts=index&&Array.isArray(index.concepts)?index.concepts:[];const set=new Set();concepts.forEach((key)=>{aiKeyAliases(key).forEach((x)=>set.add(x));});return set;}
function locHasAiQuiz(loc,aiKeySet){if(!aiKeySet||!aiKeySet.size)return false;for(const key of aiKeyAliases(loc)){if(aiKeySet.has(key))return true;}
return false;}
function readAiQuizSessions(){const parsed=readLocalJson(AI_QUIZ_SESSIONS_KEY,{});return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed:{};}
function isCompletedAiSession(session){if(!session||typeof session!=="object")return false;if(session.completed===true||session.resultProduced===true||session.result_produced===true)return true;if(session.completed_at||session.completedAt||session.result_at||session.resultAt)return true;if(session.suggested_mastery!=null||session.suggestedMastery!=null)return true;if(session.result_id||session.resultId)return true;const qs=Array.isArray(session.questions)?session.questions:[];return qs.length>0&&(session.correct_count!=null||session.correctCount!=null||session.correct!=null||session.score!=null);}
function aiSessionTime(session){return Number(session&&(session.started_at||session.startedAt||session.ts||session.completed_at||session.completedAt||session.result_at||session.resultAt||session.updated_at||session.updatedAt))||0;}
function isAiSessionAttempt(session){if(!session||typeof session!=="object")return false;if(aiSessionTime(session)>0)return true;const qs=Array.isArray(session.questions)?session.questions:[];return qs.length>0||isCompletedAiSession(session);}
function sessionBelongsToLoc(session,loc,fallbackPath){if(!session||typeof session!=="object")return pathMatchesLoc(fallbackPath,loc);const candidates=[session.concept_id,session.conceptId,session.path,session.page_path,session.pagePath,session.location,session.href,fallbackPath].filter(Boolean);return candidates.some((value)=>pathMatchesLoc(value,loc));}
function localSessionsLatestAttemptForLoc(loc,sessions){const store=sessions&&typeof sessions==="object"?sessions:readAiQuizSessions();let latest=0;for(const[key,arr0]of Object.entries(store)){const arr=Array.isArray(arr0)?arr0:[];if(!arr.length)continue;for(const session of arr){if(!isAiSessionAttempt(session))continue;if(pathMatchesLoc(key,loc)||sessionBelongsToLoc(session,loc,key)){latest=Math.max(latest,aiSessionTime(session));}}}
return latest;}
function eventLooksCompletedAiQuiz(ev){if(!ev||typeof ev!=="object")return false;const metric=String(ev.metric||ev.type||"").toLowerCase();if(!(metric==="ai_quiz"||metric==="ai_quiz_complete"||metric.indexOf("ai_quiz")>=0))return false;const d=ev.details&&typeof ev.details==="object"?ev.details:{};if(ev.type==="ai_quiz_complete"||ev.completed===true||d.completed===true)return true;if(d.resultProduced===true||d.result_produced===true||d.completedAt||d.completed_at||d.resultId||d.result_id)return true;return false;}
function aiEventTime(ev){const d=ev&&ev.details&&typeof ev.details==="object"?ev.details:{};return Number(ev&&(ev.ts||ev.createdAt||ev.created_at||ev.updatedAt||ev.updated_at)||d.completedAt||d.completed_at||d.startedAt||d.started_at||d.ts||0)||0;}
function eventPathMatchesLoc(ev,loc){if(!ev||typeof ev!=="object")return false;const d=ev.details&&typeof ev.details==="object"?ev.details:{};const candidates=[ev.path,ev.conceptId,ev.concept_id,ev.page_path,ev.pagePath,d.path,d.conceptId,d.concept_id,d.page_path,d.pagePath].filter(Boolean);if(candidates.some((value)=>pathMatchesLoc(value,loc)))return true;const session=d.session&&typeof d.session==="object"?d.session:null;return!!(session&&sessionBelongsToLoc(session,loc,ev.path||d.path||""));}
function accountEventsLatestAiQuizForLoc(loc){let latest=0;const account=readLocalJson(ACCOUNT_FILE_KEY,null);const events=account&&Array.isArray(account.eventLog)?account.eventLog:[];for(const ev of events){if(eventLooksCompletedAiQuiz(ev)&&eventPathMatchesLoc(ev,loc))latest=Math.max(latest,aiEventTime(ev));}
const pending=readLocalJson(PENDING_XP_QUEUE_KEY,[]);if(Array.isArray(pending)){for(const item of pending){const ev={metric:item&&item.metric,type:item&&item.type,path:item&&item.path,ts:item&&item.queuedAt,details:item&&item.details};if(eventLooksCompletedAiQuiz(ev)&&eventPathMatchesLoc(ev,loc))latest=Math.max(latest,aiEventTime(ev));}}
return latest;}
function masteryRecordLooksAiAccepted(record){if(!record||typeof record!=="object")return false;const hay=[record.source,record.via,record.changeKind,record.change_kind,record.reason].map((x)=>String(x||"").toLowerCase()).join(" ");if(/\b(ai|aiq|mcq)\b/.test(hay)||/ai-?accept/.test(hay)||/ai-?mcq/.test(hay))return true;const history=[].concat(Array.isArray(record.history)?record.history:[]).concat(Array.isArray(record.reviewHistory)?record.reviewHistory:[]).concat(Array.isArray(record.masteryHistory)?record.masteryHistory:[]);return history.some((item)=>{if(!item||typeof item!=="object")return false;const kind=String(item.kind||item.type||item.event||item.action||"").toLowerCase();const src=String(item.source||item.via||item.reason||"").toLowerCase();return kind!=="view"&&(/\b(ai|aiq|mcq)\b/.test(src)||/ai-?accept/.test(src)||/ai-?mcq/.test(src));});}
function masteryRecordLatestAiAcceptedAt(record){if(!masteryRecordLooksAiAccepted(record))return 0;const history=[].concat(Array.isArray(record.history)?record.history:[]).concat(Array.isArray(record.reviewHistory)?record.reviewHistory:[]).concat(Array.isArray(record.masteryHistory)?record.masteryHistory:[]);let latest=0;for(const item of history){if(!item||typeof item!=="object")continue;const kind=String(item.kind||item.type||item.event||item.action||"").toLowerCase();const src=String(item.source||item.via||item.reason||"").toLowerCase();if(kind==="view")continue;if(/\b(ai|aiq|mcq)\b/.test(src)||/ai-?accept/.test(src)||/ai-?mcq/.test(src)){latest=Math.max(latest,Number(item.ts||item.time||item.at||item.createdAt||0)||0);}}
return latest||Number(record.ratingVerifiedAt||record.lastReviewed||record.updatedAt||0)||0;}
function latestAiQuizSignalForLoc(loc,sessions){let latest=Math.max(localSessionsLatestAttemptForLoc(loc,sessions),accountEventsLatestAiQuizForLoc(loc));const all=readLocalJson(MASTERY_KEY,{});if(all&&typeof all==="object"&&!Array.isArray(all)){for(const[key,rec]of Object.entries(all)){if(pathMatchesLoc(key,loc))latest=Math.max(latest,masteryRecordLatestAiAcceptedAt(rec));}}
return latest;}
function locSetHas(set,loc){if(!set||!set.size)return false;for(const alias of sessionPathAliases(loc)){if(set.has(alias))return true;}
return false;}
function addLatestAiLoc(map,loc,ts){const t=Number(ts||0)||0;if(!map||!loc||!t)return;for(const alias of sessionPathAliases(loc)){const old=Number(map.get(alias)||0)||0;if(t>old)map.set(alias,t);}}
function latestAiFromProfile(profile,loc){const map=profile&&profile.latestAiByAlias;if(!map||!map.size)return 0;let latest=0;for(const alias of sessionPathAliases(loc)){latest=Math.max(latest,Number(map.get(alias)||0)||0);}
return latest;}
function addAiSessionToProfile(profile,session,fallbackPath){if(!profile||!isAiSessionAttempt(session))return;const ts=aiSessionTime(session);addLatestAiLoc(profile.latestAiByAlias,fallbackPath,ts);if(session&&typeof session==="object"){[session.concept_id,session.conceptId,session.path,session.page_path,session.pagePath,session.location,session.href].filter(Boolean).forEach((value)=>addLatestAiLoc(profile.latestAiByAlias,value,ts));}
if(isCompletedAiSession(session)){addAiLocAliases(profile.aiAcceptedSet,fallbackPath);if(session&&typeof session==="object"){[session.concept_id,session.conceptId,session.path,session.page_path,session.pagePath,session.location,session.href].filter(Boolean).forEach((value)=>addAiLocAliases(profile.aiAcceptedSet,value));}}}
function addAiEventToProfile(profile,ev){if(!profile||!eventLooksCompletedAiQuiz(ev))return;const ts=aiEventTime(ev);const d=ev&&ev.details&&typeof ev.details==="object"?ev.details:{};[ev&&ev.path,ev&&ev.conceptId,ev&&ev.concept_id,ev&&ev.page_path,ev&&ev.pagePath,d.path,d.conceptId,d.concept_id,d.page_path,d.pagePath].filter(Boolean).forEach((value)=>{addAiLocAliases(profile.aiAcceptedSet,value);addLatestAiLoc(profile.latestAiByAlias,value,ts);});const session=d.session&&typeof d.session==="object"?d.session:null;if(session)addAiSessionToProfile(profile,session,ev&&ev.path||d.path||"");}
function buildRandomAiProfile(sessions){const profile={ratingSet:new Set(),visitedSet:new Set(),aiAcceptedSet:new Set(),latestAiByAlias:new Map(),};const store=sessions&&typeof sessions==="object"?sessions:readAiQuizSessions();for(const[key,arr0]of Object.entries(store)){const arr=Array.isArray(arr0)?arr0:[];arr.forEach((session)=>addAiSessionToProfile(profile,session,key));}
const account=readLocalJson(ACCOUNT_FILE_KEY,null);const events=account&&Array.isArray(account.eventLog)?account.eventLog:[];events.forEach((ev)=>addAiEventToProfile(profile,ev));const pending=readLocalJson(PENDING_XP_QUEUE_KEY,[]);if(Array.isArray(pending)){pending.forEach((item)=>addAiEventToProfile(profile,{metric:item&&item.metric,type:item&&item.type,path:item&&item.path,ts:item&&item.queuedAt,details:item&&item.details}));}
const all=readLocalJson(MASTERY_KEY,{});if(all&&typeof all==="object"&&!Array.isArray(all)){for(const[key,rec]of Object.entries(all)){if(masteryRecordHasExplicitRating(rec))addAiLocAliases(profile.ratingSet,key);if(masteryRecordHasVisit(rec))addAiLocAliases(profile.visitedSet,key);if(masteryRecordLooksAiAccepted(rec)){addAiLocAliases(profile.aiAcceptedSet,key);addLatestAiLoc(profile.latestAiByAlias,key,masteryRecordLatestAiAcceptedAt(rec));}}}
return profile;}
function masteryRecordHasExplicitRating(rec){if(!rec||typeof rec!=="object")return false;const m=Number(rec.m);return m===0||m===1||m===2||m===3;}
function masteryRecordHasVisit(rec){if(!rec||typeof rec!=="object")return false;return!!(rec.visited||Number(rec.viewCount||rec.visitCount||rec.lastViewed||rec.lastSeen||0)>0||(Array.isArray(rec.history)&&rec.history.some((h)=>{const kind=String(h&&(h.kind||h.type||h.event||h.action)||"").toLowerCase();return kind==="view"||kind==="visit"||kind==="seen";})));}
function randomAiCandidateWeight(loc,sessions,profile){const latestAi=profile?latestAiFromProfile(profile,loc):latestAiQuizSignalForLoc(loc,sessions);if(latestAi&&Date.now()-latestAi<RANDOM_AI_RECENT_EXCLUDE_MS)return 0;const rec=profile?null:readMasteryRecord(loc);const hasRating=profile?locSetHas(profile.ratingSet,loc):masteryRecordHasExplicitRating(rec);const hasVisit=profile?locSetHas(profile.visitedSet,loc):masteryRecordHasVisit(rec);const hasAi=!!latestAi||(profile?locSetHas(profile.aiAcceptedSet,loc):masteryRecordLooksAiAccepted(rec));if(!hasVisit&&!hasRating)return 10;if(hasVisit&&!hasRating)return 6;if(hasRating&&!hasAi)return 3;if(hasAi)return 1;return 2;}
function pickRandomAiLocation(indexJson,scopePrefix,aiKeySet,sessions){const profile=buildRandomAiProfile(sessions);const candidates=conceptCandidates(indexJson,scopePrefix).filter((loc)=>locHasAiQuiz(loc,aiKeySet)).map((loc)=>({loc,weight:randomAiCandidateWeight(loc,sessions,profile)})).filter((row)=>row.weight>0);return pickWeightedRandom(candidates,(row)=>row.weight)?.loc||null;}
function addAiLocAliases(set,loc){if(!set||!loc)return;sessionPathAliases(loc).forEach((alias)=>set.add(alias));}
function armRandomAiQuizNavigation(loc,mode){const target=normLoc(loc);try{sessionStorage.setItem(RANDOM_MODE_KEY,"ai");sessionStorage.removeItem(SELF_TEST_MODE_KEY);sessionStorage.removeItem(SELF_TEST_NAV_FLAG);sessionStorage.setItem(RANDOM_AI_NAV_FLAG,"1");sessionStorage.removeItem(RANDOM_AI_OPENED_KEY);const arrivalId=String(Date.now())+"_"+Math.random().toString(16).slice(2);sessionStorage.setItem(RANDOM_ARRIVAL_ID_KEY,arrivalId);sessionStorage.setItem(RANDOM_ARRIVAL_LOC_KEY,target);sessionStorage.setItem("random_ai_source_v1",String(mode||"random-ai"));sessionStorage.setItem(RANDOM_AI_ENTRY_URL_KEY,String(window.location.href||""));if(String(mode||"").toLowerCase().includes("untested"))sessionStorage.setItem(RANDOM_AI_ONLY_UNTESTED_KEY,"1");}catch(_){}}
function armNormalRandomNavigation(loc){try{sessionStorage.setItem(RANDOM_MODE_KEY,"normal");sessionStorage.removeItem(RANDOM_AI_NAV_FLAG);sessionStorage.removeItem(RANDOM_AI_OPENED_KEY);sessionStorage.removeItem(SELF_TEST_NAV_FLAG);}catch(_){}}
function masteryReady(m){if(m===3||m===2)return 1;if(m===1)return 0.5;if(m===0)return 0;return 0;}
async function loadConceptGraph(){const siteRoot=getSiteRootUrl();const url=new URL(GRAPH_URL,siteRoot).toString();const res=await fetch(url,{credentials:"same-origin"});if(!res.ok)throw new Error("Cannot load graph at "+url);return await res.json();}
function getGraphPrereqs(graph,loc){const key=normLoc(loc);if(!graph||!key)return[];const src=(graph.prereqOf&&graph.prereqOf[key])||(graph.prereqs&&graph.prereqs[key])||[];return Array.isArray(src)?src:[];}
function getGraphDependents(graph,loc){const key=normLoc(loc);if(!graph||!key)return[];const src=(graph.dependents&&graph.dependents[key])||(graph.dependentOf&&graph.dependentOf[key])||[];return Array.isArray(src)?src:[];}
function compareRoutePrereqs(graph,a,b){const locA=normLoc(a);const locB=normLoc(b);const readyA=masteryReady(readMasteryLevel(locA));const readyB=masteryReady(readMasteryLevel(locB));if(readyA!==readyB)return readyA-readyB;const preA=getGraphPrereqs(graph,locA).length;const preB=getGraphPrereqs(graph,locB).length;if(preA!==preB)return preB-preA;const depA=getGraphDependents(graph,locA).length;const depB=getGraphDependents(graph,locB).length;if(depA!==depB)return depB-depA;return String(locA).localeCompare(String(locB),undefined,{sensitivity:"base"});}
function buildGuidedRoutePath(graph,targetLoc){const target=normLoc(targetLoc);if(!target||!isConceptLocation(target))return[];const path=[target];const seen=new Set([canonLoc(target)]);let cur=target;for(let depth=0;depth<7;depth+=1){const prereqs=getGraphPrereqs(graph,cur).map(normLoc).filter(Boolean).filter(isConceptLocation).sort((a,b)=>compareRoutePrereqs(graph,a,b));const next=prereqs.find((loc)=>!seen.has(canonLoc(loc)));if(!next)break;path.unshift(next);seen.add(canonLoc(next));cur=next;}
return path;}
function storeGpsRouteState(targetLoc,path,startIndex){try{const cleanPath=(Array.isArray(path)?path:[]).map(normLoc).filter(Boolean).filter((loc,idx,arr)=>arr.findIndex((x)=>canonLoc(x)===canonLoc(loc))===idx);if(!cleanPath.length){clearGpsRouteState();return false;}
let idx=Number.isFinite(Number(startIndex))?Number(startIndex):0;idx=Math.max(0,Math.min(cleanPath.length-1,idx));const payload={ts:Date.now(),target:normLoc(targetLoc||cleanPath[cleanPath.length-1]||""),path:cleanPath,currentIndex:idx,currentLoc:normLoc(cleanPath[idx]||""),completed:idx===cleanPath.length-1&&canonLoc(cleanPath[idx]||"")===canonLoc(targetLoc||cleanPath[cleanPath.length-1]||"")};sessionStorage.setItem(GPS_ROUTE_KEY,JSON.stringify(payload));return true;}catch(_){return false;}}
function readRandomEntryModeFromUrl(urlLike){try{const url=new URL(urlLike||window.location.href,document.baseURI);const raw=String(url.searchParams.get("mode")||"").toLowerCase().trim();if(raw==="route")return"route";if(raw==="unvisited"||raw==="random-unvisited")return"unvisited";if(raw==="ai"||raw==="ai-quiz"||raw==="random-ai")return"ai";if(raw==="ai-untested"||raw==="untested-ai"||raw==="random-ai-untested")return"ai-untested";return"concept";}catch(_){return"concept";}}
function readRandomEntryMode(){return readRandomEntryModeFromUrl(window.location.href);}
function storeRandomRoutePending(loc){try{const target=normLoc(loc);if(!target)return;sessionStorage.setItem(RANDOM_ROUTE_PENDING_KEY,JSON.stringify({target,ts:Date.now()}));}catch(_){}}
function clearRandomRoutePending(){try{sessionStorage.removeItem(RANDOM_ROUTE_PENDING_KEY);}catch(_){}}
async function randomJump(scope,options){const indexJson=await loadSearchIndex();const mode=options&&options.mode?String(options.mode):"concept";recordRandomXp(mode==="route"||/route/i.test(mode)?"guided_study_start":"random_browse_start",{source:"randomJump",eventName:"randomJump",scope:scope||"",mode});let loc=null;if(mode==="unvisited"){loc=pickRandomLocation(indexJson,scope||"",isUnvisitedConcept);if(!loc)loc=pickRandomLocation(indexJson,scope||"");}else if(mode==="ai"||mode==="ai-untested"){let aiKeys=null;try{aiKeys=await loadAiIndexKeySet();}catch(_){aiKeys=null;}
if(aiKeys&&aiKeys.size){const sessions=readAiQuizSessions();loc=pickRandomAiLocation(indexJson,scope||"",aiKeys,sessions);}}else{loc=pickRandomLocation(indexJson,scope||"");}
if(!loc){clearRandomRoutePending();clearGpsRouteState();if(mode==="ai-untested"||mode==="ai")rememberRandomAiNotice("No eligible AI quizzes were found in the current scope. Concepts attempted in the past 30 days are excluded.");return false;}
rememberRandomAiNotice("");try{sessionStorage.setItem("random_review_mode_v1","1");}catch(_){}
if(mode==="route"){armNormalRandomNavigation(loc);try{const graph=await loadConceptGraph();const routePath=buildGuidedRoutePath(graph,loc);if(storeGpsRouteState(loc,routePath,0)){clearRandomRoutePending();const startLoc=normLoc(routePath[0]||loc);writeGpsRouteTicket(startLoc);window.location.assign(toAbsoluteUrl(startLoc));return true;}}catch(_){}
storeRandomRoutePending(loc);clearGpsRouteState();window.location.assign(toAbsoluteUrl(loc));return true;}
clearRandomRoutePending();clearGpsRouteState();if(mode==="ai"||mode==="ai-untested")armRandomAiQuizNavigation(loc,mode);else armNormalRandomNavigation(loc);window.location.assign(toAbsoluteUrl(loc));return true;}
async function directRandomJumpFromHref(href,options){const rawHref=String(href||"");if(!isTrueRandomHref(rawHref))return false;const scope=options&&Object.prototype.hasOwnProperty.call(options,"scope")?String(options.scope||""):(readScope()||"");const mode=options&&options.mode?String(options.mode):readRandomEntryModeFromUrl(rawHref);return await randomJump(scope,{mode});}
function bindRandomScopeRecorder(){if(window.__randomScopeRecorderBoundV3)return;window.__randomScopeRecorderBoundV3=true;document.addEventListener("click",(ev)=>{const a=ev.target&&ev.target.closest?ev.target.closest("a"):null;if(!a)return;const href=a.getAttribute("href")||"";if(!href)return;if(!isTrueRandomHref(href))return;const mode=a.getAttribute("data-random-scope")||"";if(mode==="course"){const courseScope=inferCourseScopeFromPath(window.location.pathname);storeScope(courseScope||"");}else{storeScope("");}},true);}
async function autoOnRandomPage(){if(!isTrueRandomPagePath(window.location.pathname))return;const scope=readScope()||"";const mode=readRandomEntryMode();try{await randomJump(scope,{mode});}catch(e){clearRandomRoutePending();console.warn("Random auto jump failed:",e);}}
function init(){rememberLastNonRandom();bindRandomScopeRecorder();autoOnRandomPage();}
if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",init);}else{init();}
document.addEventListener("DOMContentSwitch",init);window.MkRandom=Object.assign({},window.MkRandom||{},{jump:randomJump,jumpFromHref:directRandomJumpFromHref,storeScope,inferCourseScopeFromPath});})();