(function(){try{window.__searchEnterVersion="v8-same-find-inplace-no-preload";}catch(_){}
const KEY="find_pending_token_v2";const LEGACY_KEY="find_pending_token_v1";const RUN_LOCK_KEY="__find_autoflow_ran_v2__";const SCROLL_Y_KEY="__md_scroll_y__";const PALETTE_KEY="__md_palette_cache__";const MATERIAL_PALETTE_LS_KEY="__palette";function norm(s){return String(s||"").replace(/\s+/g," ").trim();}
function sleep(ms){return new Promise((r)=>setTimeout(r,ms));}
function isFindPage(){try{const p0=String(window.location.pathname||"").toLowerCase();const clean=p0.replace(/\/index\.html$/,"").replace(/\/find\.html$/,"/find").replace(/\/+$/,"");if(clean==="find"||clean.endsWith("/find"))return true;if(p0.endsWith("/find.html")||p0.endsWith("/find/index.html"))return true;}catch(_){}
try{if(document.body&&document.body.classList&&document.body.classList.contains("mk-find-page"))return true;if(document.getElementById("find-builder"))return true;const form=document.getElementById("search-form");const results=document.getElementById("search-results");const input=document.getElementById("search-input");if(form&&results&&input&&form.contains(input))return true;}catch(_){}
return false;}
function isDirectLpFindFlow(){try{const url=new URL(window.location.href);return String(url.searchParams.get("src")||"").trim()==="lp_direct";}catch(_){return false;}}
function isMaterialSearchInput(el){try{if(!el||!el.matches)return false;if(el.closest&&el.closest('#find-builder, #search-form, .fb-tokensearch-wrap'))return false;if(!/^input$/i.test(el.tagName||""))return false;const type=String(el.getAttribute('type')||'').toLowerCase();if(type&&type!=='search'&&type!=='text')return false;const shell=el.closest&&el.closest('.md-search, .md-header');const hasMaterialMarker=el.matches('input[data-md-component="search-query"]');const classLooksRight=el.matches('input.md-search__input, input[type="search"]');const nameLooksRight=el.matches('input[name="q"], input[name="query"], input[name="search"]');const textLooksRight=(()=>{try{const ph=String(el.getAttribute('placeholder')||'').toLowerCase();const aria=String(el.getAttribute('aria-label')||'').toLowerCase();const role=String(el.getAttribute('role')||'').toLowerCase();return role==='searchbox'||ph.includes('search')||aria.includes('search');}catch(_){return false;}})();return!!(hasMaterialMarker||(shell&&(classLooksRight||nameLooksRight||textLooksRight)));}catch(_){return false;}}
function getEventSearchInput(ev){try{const target=ev&&ev.target;if(isMaterialSearchInput(target))return target;const active=document.activeElement;if(isMaterialSearchInput(active))return active;if(target&&target.closest){const shell=target.closest('.md-search, .md-header');if(shell){const input=shell.querySelector('input[data-md-component="search-query"], input.md-search__input, input[type="search"], input[name="q"], input[name="query"]');if(isMaterialSearchInput(input))return input;}}}catch(_){}
return null;}
function isMaterialSearchForm(form){try{if(!form||!form.matches)return false;if(form.closest&&form.closest('#find-builder, #search-form, .fb-tokensearch-wrap'))return false;if(form.closest&&form.closest('.md-search, .md-header'))return true;return!!form.querySelector('input[data-md-component="search-query"], input.md-search__input');}catch(_){return false;}}
function getSearchInputFromForm(form){try{if(!form||!form.querySelector)return null;const input=form.querySelector('input[data-md-component="search-query"], input.md-search__input, input[type="search"], input[name="q"], input[name="query"]');return isMaterialSearchInput(input)?input:null;}catch(_){return null;}}
function stopEnterEvent(e){if(!e)return;try{e.preventDefault();}catch(_){}
try{e.stopPropagation();}catch(_){}
try{if(e.stopImmediatePropagation)e.stopImmediatePropagation();}catch(_){}}
function consumeGuestSearch(query,source){try{if(window.MkGuestAccess&&typeof window.MkGuestAccess.consume==="function"){return!!window.MkGuestAccess.consume("search",{query:String(query||""),source:source||"header-search",dedupeMs:2500});}}catch(_){}
return true;}
function markSameFindTopSearchIntent(ms){if(!isFindPage())return;const until=Date.now()+Math.max(1600,Number(ms)||0);try{window.__findHeaderSamePageHandledUntilV8=until;}catch(_){}
try{window.__findHeaderSamePageHandledUntilV7=until;}catch(_){}
try{window.__findHeaderEnterSuppressUntilV8=until;}catch(_){}
try{window.__findHeaderEnterSuppressUntilV6=until;}catch(_){}
try{window.__mkFindSamePageTopSearchUntil=until;}catch(_){}
try{window.__rkCancelPreloadForFindSamePage&&window.__rkCancelPreloadForFindSamePage('search-enter');}catch(_){}}
function hasSameFindTopSearchIntent(){try{const now=Date.now();return isFindPage()&&(now<Number(window.__findHeaderSamePageHandledUntilV8||0)||now<Number(window.__findHeaderSamePageHandledUntilV7||0)||now<Number(window.__mkFindSamePageTopSearchUntil||0));}catch(_){return false;}}
function getHeaderSearchInputs(){try{return Array.from(document.querySelectorAll('input[data-md-component="search-query"], .md-search input, .md-header input[type="search"], .md-header input[role="searchbox"]')).filter((el)=>isMaterialSearchInput(el));}catch(_){return[];}}
function getPrimaryHeaderSearchInput(){try{const active=document.activeElement;if(isMaterialSearchInput(active))return active;}catch(_){}
const inputs=getHeaderSearchInputs();return inputs[0]||null;}
async function dispatchFindAutofillOnCurrentPage(q,nonce){const token=norm(q);if(!token||!isFindPage())return false;markSameFindTopSearchIntent(3200);try{if(typeof window.__mkFindAutofillFromTopSearch==="function"){const ok=window.__mkFindAutofillFromTopSearch(token,{nonce:nonce||"",source:"search-enter-direct"});if(ok)return true;}}catch(_){}
try{sessionStorage.removeItem(KEY);}catch(_){}
try{sessionStorage.removeItem(LEGACY_KEY);}catch(_){}
try{sessionStorage.removeItem(RUN_LOCK_KEY);}catch(_){}
try{sessionStorage.removeItem("__se_find_autofill_nonce_v2__");}catch(_){}
const ready=await new Promise((resolve)=>{try{if(window.__fbReadyV1)return resolve(true);}catch(_){}
let done=false;const finish=(ok)=>{if(done)return;done=true;try{window.removeEventListener("fb:ready",onReady);}catch(_){}
resolve(!!ok);};const onReady=()=>finish(true);try{window.addEventListener("fb:ready",onReady,{once:true});}catch(_){}
setTimeout(()=>finish(false),2200);});try{window.dispatchEvent(new CustomEvent("find:autofill",{detail:{token,nonce:nonce||"",ready,samePage:true}}));return true;}catch(_){return false;}}
function persistPaletteOnly(){try{const paletteRaw=localStorage.getItem(MATERIAL_PALETTE_LS_KEY)||"";if(paletteRaw)sessionStorage.setItem(PALETTE_KEY,paletteRaw);}catch(_){}}
function restorePaletteEarly(){try{const paletteRaw=sessionStorage.getItem(PALETTE_KEY)||"";if(paletteRaw)localStorage.setItem(MATERIAL_PALETTE_LS_KEY,paletteRaw);}catch(_){}}
restorePaletteEarly();function getSiteRootUrl(){const script=document.querySelector('script[src*="assets/javascripts/bundle"]');const link=document.querySelector('link[href*="assets/stylesheets/main"]')||document.querySelector('link[href*="assets/stylesheets"]');const attr=script?script.getAttribute("src"):link?link.getAttribute("href"):null;const assetUrl=attr?new URL(attr,document.baseURI):new URL(document.baseURI);const p=assetUrl.pathname;const idx=p.indexOf("/assets/");if(idx>=0)return assetUrl.origin+p.slice(0,idx+1);const base=new URL(document.baseURI);if(!base.pathname.endsWith("/"))base.pathname+="/";return base.origin+base.pathname;}
function rememberScrollY(){try{sessionStorage.setItem(SCROLL_Y_KEY,String(window.scrollY||0));}catch(_){}}
function _removeScrollLockStyles(el){if(!el||!el.style)return;["overflow","overflow-x","overflow-y","position","top","left","right","bottom","height","width","touch-action","padding-right","margin-right","transform","transition","animation","-webkit-overflow-scrolling"].forEach((prop)=>{try{el.style.removeProperty(prop);}catch(_){}});}
function isHeaderSearchActuallyOpen(){try{const headerSearch=document.querySelector('.md-header .md-search');const toggle=document.querySelector('input.md-toggle[data-md-toggle="search"]')||document.querySelector('input#__search')||document.querySelector('#__search');const activeEl=document.activeElement;const focusedInside=!!(headerSearch&&activeEl&&headerSearch.contains&&headerSearch.contains(activeEl));const toggleOpen=!!(toggle&&toggle.checked);const shellActive=!!(headerSearch&&headerSearch.classList&&headerSearch.classList.contains('md-search--active'));const visible=(()=>{try{const shell=headerSearch&&headerSearch.querySelector?headerSearch.querySelector('.md-search__inner'):null;if(!shell)return false;const cs=window.getComputedStyle(shell);if(cs.display==='none'||cs.visibility==='hidden'||Number(cs.opacity||1)===0)return false;const r=shell.getBoundingClientRect();return!!(r&&r.width>20&&r.height>20);}catch(_){return false;}})();return visible&&(focusedInside||toggleOpen||shellActive||document.documentElement.classList.contains('md-search--active')||document.body.classList.contains('md-search--active'));}catch(_){return false;}}
function releaseScrollLockAndRestoreScroll(opts){const options=opts&&typeof opts==="object"?opts:{};const keepFocus=!!options.keepFocus;try{const html=document.documentElement;const body=document.body;if(keepFocus&&isHeaderSearchActuallyOpen())return;const top=body&&body.style?body.style.top:"";const lockedY=top&&/-?\d+px/.test(top)?Math.abs(parseInt(top,10)):0;document.querySelectorAll("[data-md-scrollfix]").forEach((el)=>{try{el.removeAttribute("data-md-scrollfix");}catch(_){}});if(html){try{html.removeAttribute("data-md-scrollfix");}catch(_){}}
if(body){try{body.removeAttribute("data-md-scrollfix");}catch(_){}}
["md-search--active","md-dialog--active","md-overlay--active","md-sidebar--active","md-nav--active"].forEach((cls)=>{try{if(html&&html.classList)html.classList.remove(cls);}catch(_){}
try{if(body&&body.classList)body.classList.remove(cls);}catch(_){}});_removeScrollLockStyles(html);_removeScrollLockStyles(body);document.querySelectorAll(".md-container, .md-main, .md-content, .md-grid, .md-page").forEach((el)=>{_removeScrollLockStyles(el);});let y=lockedY;if(!y){const saved=sessionStorage.getItem(SCROLL_Y_KEY);y=saved?parseInt(saved,10)||0:0;}
if(y>0){try{window.scrollTo(0,y);}catch(_){}}
try{sessionStorage.removeItem(SCROLL_Y_KEY);}catch(_){}
const list=document.querySelector(".md-search-result__list");if(list&&list.style){try{list.style.removeProperty("display");}catch(_){}}
const overlay=document.querySelector(".md-search__overlay");if(overlay&&overlay.style){try{overlay.style.removeProperty("display");}catch(_){}}
if(!keepFocus){try{if(document.activeElement&&document.activeElement.blur)document.activeElement.blur();}catch(_){}}}catch(_){}}
function dismissKeyboard(){try{const active=document.activeElement;if(active&&active.blur)active.blur();}catch(_){}
try{if(!document.body)return;const tmp=document.createElement("button");tmp.type="button";tmp.tabIndex=-1;tmp.setAttribute("aria-hidden","true");tmp.style.position="fixed";tmp.style.opacity="0";tmp.style.left="0";tmp.style.top="0";tmp.style.width="1px";tmp.style.height="1px";document.body.appendChild(tmp);try{tmp.focus({preventScroll:true});}catch(_){try{tmp.focus();}catch(_){}}
try{tmp.blur();}catch(_){}
tmp.remove();}catch(_){}}
function forceCloseMaterialSearchUI(temporaryDisablePointerMs){try{const html=document.documentElement;const body=document.body;const toggle=document.querySelector('input.md-toggle[data-md-toggle="search"]')||document.querySelector("input#__search")||document.querySelector("#__search");if(toggle){try{toggle.checked=false;}catch(_){}
try{toggle.dispatchEvent(new Event("change",{bubbles:true}));}catch(_){}}
const mdInput=document.querySelector('input[data-md-component="search-query"]');if(mdInput){try{mdInput.blur();}catch(_){}}
try{if(document.activeElement&&document.activeElement.blur)document.activeElement.blur();}catch(_){}
if(html)html.classList.remove("md-search--active");if(body)body.classList.remove("md-search--active");releaseScrollLockAndRestoreScroll({keepFocus:true});const overlay=document.querySelector(".md-search__overlay");const search=document.querySelector(".md-search");const backdrop=document.getElementById("mk-mobile-search-backdrop");const disableFor=typeof temporaryDisablePointerMs==="number"?temporaryDisablePointerMs:0;if(disableFor>0){if(overlay){overlay.dataset.__pe=overlay.style.pointerEvents||"";overlay.dataset.__disp=overlay.style.display||"";overlay.style.pointerEvents="none";overlay.style.display="none";}
if(search){search.dataset.__pe=search.style.pointerEvents||"";search.style.pointerEvents="none";}
if(backdrop){backdrop.dataset.__pe=backdrop.style.pointerEvents||"";backdrop.dataset.__op=backdrop.style.opacity||"";backdrop.style.pointerEvents="none";backdrop.style.opacity="0";}
setTimeout(()=>{try{const stillActive=(document.documentElement&&document.documentElement.classList.contains("md-search--active"))||(document.body&&document.body.classList.contains("md-search--active"))||(toggle&&toggle.checked);if(!stillActive){if(overlay){const pe=overlay.dataset.__pe||"";const disp=overlay.dataset.__disp||"";overlay.style.pointerEvents=pe;overlay.style.display=disp;delete overlay.dataset.__pe;delete overlay.dataset.__disp;}
if(search){const pe2=search.dataset.__pe||"";search.style.pointerEvents=pe2;delete search.dataset.__pe;}
if(backdrop){const pe3=backdrop.dataset.__pe||"";const op3=backdrop.dataset.__op||"";backdrop.style.pointerEvents=pe3;backdrop.style.opacity=op3;delete backdrop.dataset.__pe;delete backdrop.dataset.__op;}}}catch(_){}},disableFor);}}catch(_){}}
function burstUnlockScrollOnly(durationMs){const steps=[0,16,50,120,250,500,900];const end=typeof durationMs==="number"?durationMs:1000;releaseScrollLockAndRestoreScroll({keepFocus:true});steps.forEach((t)=>{if(t>end)return;setTimeout(()=>{releaseScrollLockAndRestoreScroll({keepFocus:true});},t);});}
function clearMaterialSearchInputLight(targetInput){const input=targetInput||getPrimaryHeaderSearchInput();if(!input)return;input.value="";try{input.dispatchEvent(new Event("input",{bubbles:true}));}catch(_){}}
function readPendingPayload(){let raw="";try{raw=sessionStorage.getItem(KEY)||"";}catch(_){}
raw=String(raw||"");let q="";let nonce="";const trimmed=raw.trim();if(trimmed&&trimmed.startsWith("{")){try{const obj=JSON.parse(trimmed);q=norm(obj&&obj.q);nonce=norm(obj&&obj.nonce);}catch(_){q=norm(trimmed);}}else{q=norm(trimmed);}
if(!q){try{q=norm(sessionStorage.getItem(LEGACY_KEY)||"");}catch(_){}}
if(!q){try{const params=new URLSearchParams(window.location.search);q=norm(params.get("q")||"");}catch(_){}}
return{q,nonce};}
async function runAutoflowOnFind(){if(!isFindPage())return;if(isDirectLpFindFlow()){try{sessionStorage.removeItem(KEY);}catch(_){}
try{sessionStorage.removeItem(LEGACY_KEY);}catch(_){}
try{sessionStorage.removeItem(RUN_LOCK_KEY);}catch(_){}
return;}
const payload=readPendingPayload();const q=payload.q;if(!q)return;const nonce=String(payload.nonce||"");const lockVal=nonce?`${window.location.pathname}::${q}::${nonce}`:`${window.location.pathname}::${q}`;const guard=(window.__findAutoflowGuardV3=window.__findAutoflowGuardV3||{running:false,lockVal:""});if(guard.running&&guard.lockVal===lockVal)return;if(guard.lockVal===lockVal)return;guard.running=true;guard.lockVal=lockVal;const DISPATCH_LOCK_KEY="__se_find_autofill_nonce_v2__";try{try{sessionStorage.removeItem(RUN_LOCK_KEY);}catch(_){}
burstUnlockScrollOnly(1400);try{const last=sessionStorage.getItem(DISPATCH_LOCK_KEY)||"";if(lockVal&&last===lockVal)return;}catch(_){}
const ready=await new Promise((resolve)=>{try{if(window.__fbReadyV1)return resolve(true);}catch(_){}
let done=false;const onReady=()=>{if(done)return;done=true;try{window.removeEventListener("fb:ready",onReady);}catch(_){}
resolve(true);};try{window.addEventListener("fb:ready",onReady,{once:true});}catch(_){}
setTimeout(()=>{if(done)return;done=true;try{window.removeEventListener("fb:ready",onReady);}catch(_){}
resolve(false);},12000);});burstUnlockScrollOnly(1200);try{window.dispatchEvent(new CustomEvent("find:autofill",{detail:{token:q,nonce,ready}}));}catch(_){}
setTimeout(()=>burstUnlockScrollOnly(1000),0);setTimeout(()=>burstUnlockScrollOnly(1000),180);try{if(lockVal)sessionStorage.setItem(DISPATCH_LOCK_KEY,lockVal);}catch(_){}
try{sessionStorage.removeItem(KEY);}catch(_){}
try{sessionStorage.removeItem(LEGACY_KEY);}catch(_){}
try{const url=new URL(window.location.href);if(url.searchParams.has("q")){url.searchParams.delete("q");history.replaceState({},"",url.toString());}}catch(_){}}finally{guard.running=false;}}
async function handleMaterialSearchEnter(input,e){if(!input||!e)return false;const evType=String(e.type||"").toLowerCase();const isSubmit=evType==="submit";if(!isSubmit&&e.key!=="Enter")return false;if(e.isComposing||e.keyCode===229||input.__mkSearchComposing)return false;if(!isMaterialSearchInput(input))return false;const q=norm(input.value||"");if(!q)return false;stopEnterEvent(e);if(!consumeGuestSearch(q,isFindPage()?"header-search-find-page":"header-search"))return true;try{window.__findHeaderEnterSuppressUntilV6=Date.now()+1600;}catch(_){}
rememberScrollY();persistPaletteOnly();const nonce=`${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;if(isFindPage()){markSameFindTopSearchIntent(3200);clearMaterialSearchInputLight(input);dismissKeyboard();forceCloseMaterialSearchUI(650);releaseScrollLockAndRestoreScroll({keepFocus:true});setTimeout(()=>releaseScrollLockAndRestoreScroll({keepFocus:true}),0);setTimeout(()=>releaseScrollLockAndRestoreScroll({keepFocus:true}),80);await dispatchFindAutofillOnCurrentPage(q,nonce);return true;}
try{sessionStorage.removeItem(RUN_LOCK_KEY);sessionStorage.setItem(KEY,JSON.stringify({q,nonce}));}catch(_){}
try{sessionStorage.setItem(LEGACY_KEY,q);}catch(_){}
clearMaterialSearchInputLight(input);dismissKeyboard();forceCloseMaterialSearchUI(1400);releaseScrollLockAndRestoreScroll();setTimeout(()=>releaseScrollLockAndRestoreScroll(),0);setTimeout(()=>releaseScrollLockAndRestoreScroll(),80);setTimeout(()=>releaseScrollLockAndRestoreScroll(),220);await sleep(240);const root=getSiteRootUrl();const u=new URL("find.html",root);window.location.assign(u.toString());return true;}
function bindMaterialSearchEnter(){const inputs=getHeaderSearchInputs();if(!window.__findHeaderHistoryGuardV7){window.__findHeaderHistoryGuardV7=true;try{const origPush=history.pushState;const origReplace=history.replaceState;const shouldSuppressFindHistory=(url)=>{try{if(!isFindPage())return false;if(!hasSameFindTopSearchIntent())return false;if(url==null||url==="")return false;const u=new URL(String(url),window.location.href);const p0=String(u.pathname||"").toLowerCase();const clean=p0.replace(/\/index\.html$/,"").replace(/\/find\.html$/,"/find").replace(/\/+$/,"");return clean==="find"||clean.endsWith("/find")||p0.endsWith("/find.html")||p0.endsWith("/find/index.html");}catch(_){return false;}};history.pushState=function(state,title,url){if(shouldSuppressFindHistory(url))return undefined;return origPush.apply(this,arguments);};history.replaceState=function(state,title,url){if(shouldSuppressFindHistory(url))return undefined;return origReplace.apply(this,arguments);};}catch(_){}}
if(!window.__findHeaderSameFindClickGuardV8){window.__findHeaderSameFindClickGuardV8=true;const onClickCapture=(e)=>{try{if(!hasSameFindTopSearchIntent())return;const a=e&&e.target&&e.target.closest?e.target.closest('a[href]'):null;if(!a)return;const u=new URL(a.getAttribute('href')||'',window.location.href);const p0=String(u.pathname||'').toLowerCase();const clean=p0.replace(/\/index\.html$/,'').replace(/\/find\.html$/,'/find').replace(/\/+$/,'');if(!(clean==='find'||clean.endsWith('/find')||p0.endsWith('/find.html')||p0.endsWith('/find/index.html')))return;stopEnterEvent(e);}catch(_){}};window.addEventListener('click',onClickCapture,true);document.addEventListener('click',onClickCapture,true);}
if(!window.__findHeaderEnterWindowGuardV6){window.__findHeaderEnterWindowGuardV6=true;const onEnterCapture=(e)=>{try{if(!e||e.key!=="Enter")return;const input=getEventSearchInput(e);if(!input)return;if(e.isComposing||e.keyCode===229||input.__mkSearchComposing)return;if(isFindPage())markSameFindTopSearchIntent(3200);handleMaterialSearchEnter(input,e);}catch(_){}};const onLateEnterCapture=(e)=>{try{if(!e||e.key!=="Enter")return;const input=getEventSearchInput(e);if(!input)return;if(e.isComposing||e.keyCode===229||input.__mkSearchComposing)return;if(Date.now()<Number(window.__findHeaderEnterSuppressUntilV6||0))stopEnterEvent(e);}catch(_){}};window.addEventListener("keydown",onEnterCapture,true);window.addEventListener("keypress",onLateEnterCapture,true);window.addEventListener("keyup",onLateEnterCapture,true);}
if(!window.__findHeaderEnterDocGuardV6){window.__findHeaderEnterDocGuardV6=true;document.addEventListener("keydown",(e)=>{try{if(!e||e.key!=="Enter")return;const input=getEventSearchInput(e);if(!input)return;if(e.isComposing||e.keyCode===229||input.__mkSearchComposing)return;if(isFindPage())markSameFindTopSearchIntent(3200);handleMaterialSearchEnter(input,e);}catch(_){}},true);}
if(!window.__findHeaderSubmitGuardV6){window.__findHeaderSubmitGuardV6=true;const onSubmitCapture=(e)=>{try{const form=e&&e.target;if(!isFindPage())return;if(!isMaterialSearchForm(form))return;const input=getSearchInputFromForm(form)||getPrimaryHeaderSearchInput();if(!input)return;if(e.isComposing||e.keyCode===229||input.__mkSearchComposing)return;markSameFindTopSearchIntent(3200);handleMaterialSearchEnter(input,e);}catch(_){}};window.addEventListener("submit",onSubmitCapture,true);document.addEventListener("submit",onSubmitCapture,true);}
if(!inputs.length)return;inputs.forEach((input)=>{if(!input||input.dataset.findEnterBoundV6==="1")return;input.dataset.findEnterBoundV6="1";input.dataset.findEnterBoundV4="1";input.dataset.findEnterBoundV3="1";input.dataset.findEnterBoundV2="1";input.addEventListener("focus",()=>{rememberScrollY();markSameFindTopSearchIntent(2400);},{passive:true});input.addEventListener("input",()=>markSameFindTopSearchIntent(2400),{passive:true});input.addEventListener("keydown",(e)=>{if(e&&(e.isComposing||e.keyCode===229||input.__mkSearchComposing))return;if(e&&e.key==="Enter"&&isFindPage())markSameFindTopSearchIntent(3200);handleMaterialSearchEnter(input,e);},true);});}
function init(){restorePaletteEarly();bindMaterialSearchEnter();runAutoflowOnFind();}
window.addEventListener("pageshow",(e)=>{try{if(!e||!e.persisted)return;const isMobile=(()=>{try{return!!(window.matchMedia&&(window.matchMedia("(pointer: coarse)").matches||window.matchMedia("(max-width: 900px)").matches));}catch(_){return false;}})();if(!isMobile)return;const toggle=document.querySelector('input.md-toggle[data-md-toggle="search"]')||document.querySelector("input#__search")||document.querySelector("#__search");const shell=document.querySelector(".md-search__inner");const visible=(()=>{try{if(!shell)return false;const cs=window.getComputedStyle(shell);if(cs.display==="none"||cs.visibility==="hidden"||Number(cs.opacity||1)===0)return false;const r=shell.getBoundingClientRect();return r&&r.height>20&&r.width>20;}catch(_){return false;}})();const active=(toggle&&toggle.checked)||(document.documentElement&&document.documentElement.classList.contains("md-search--active"))||(document.body&&document.body.classList.contains("md-search--active"));if(!active||!visible){try{if(toggle)toggle.checked=false;}catch(_){}
forceCloseMaterialSearchUI(0);releaseScrollLockAndRestoreScroll({keepFocus:true});}}catch(_){}});document.addEventListener("DOMContentLoaded",init);document.addEventListener("DOMContentSwitch",init);try{if(isFindPage()){burstUnlockScrollOnly(1600);setTimeout(()=>burstUnlockScrollOnly(1200),220);}}catch(_){}})();