(function(){"use strict";const IDS={control:"mk-sidebar-sortdock",style:"mk-sidebar-sort-rebuild-style-v101-dark-theme-sidebar-floor",debugStyle:"mk-sidebar-sort-rebuild-debug-style"};const STORAGE_KEYS={courseMode:"mk_sidebar_sort_mode_course_v5",yearMode:"mk_sidebar_sort_mode_year_v3",groupOpen:"mk_sidebar_group_open_v1",currentScopeOpen:"mk_sidebar_current_scope_open_v1",globalYearOpen:"mk_sidebar_global_year_open_v1"};const ATTR={injected:"data-msb-injected",group:"data-msb-group",groupKind:"data-msb-group-kind",groupOpen:"data-msb-group-open",groupCollapsedItem:"data-msb-group-collapsed-item",groupCollapsedLead:"data-msb-group-collapsed-lead",duplicateCurrent:"data-msb-dup-current",courseKey:"data-msb-course-key",baseIndex:"data-msb-base-index",sortKind:"data-msb-sort-kind",sortMode:"data-msb-sort-mode",scopeCollapsed:"data-msb-scope-collapsed",syntheticGroup:"data-msb-synthetic-group"};const CLS={head:"msb-group-head",headLecture:"msb-group-head--lecture",headBlock:"msb-group-head--block",headRow:"msb-group-head__row",headText:"msb-group-head__text",headBtn:"msb-group-head__btn",headChevron:"msb-group-head__chevron",lead:"msb-group-lead",first:"msb-group-first",mid:"msb-group-mid",last:"msb-group-last",single:"msb-group-single",hover:"msb-group-hover",dock:"msb-sortdock",dockBox:"msb-sortdock__box",dockLabel:"msb-sortdock__label",dockButton:"msb-sortdock__btn"};const MODE={COURSE_LECTURE:"lecture",YEAR_BLOCK:"block",ALPHA:"alpha"};const GLOBAL_EXISTING_LINK_SELECTOR='a[href], .md-nav__link[href], .md-tabs__link[href], .md-header__link[href]';const GLOBAL_YEAR_LINK_SELECTOR='.md-sidebar--primary a.md-nav__link[href], .md-sidebar--primary .md-nav__link[href], .md-tabs__link[href], .md-header__link[href]';const SIDEBAR_CACHE_PREFIX="mk-sb-rendercache-v2:";function html(){return document.documentElement;}
function asArray(list){return Array.prototype.slice.call(list||[]);}
function isElement(node){return!!node&&node.nodeType===1;}
function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
function cssEscape(value){const text=String(value||"");if(window.CSS&&typeof window.CSS.escape==="function")return window.CSS.escape(text);return text.replace(/[^a-zA-Z0-9_-]/g,function(ch){return"\\"+ch;});}
function safePath(loc){return String(loc||"").split("#")[0].replace(/^\/+/,"").trim();}
function asStringList(value){if(!value)return[];if(Array.isArray(value))return value.map(String).filter(Boolean);if(typeof value==="string")return[value];return[];}
function isTouchLikeViewport(){try{return!!(window.matchMedia&&window.matchMedia("(hover: none), (pointer: coarse)").matches);}catch(_){return false;}}
function siteRootUrl(){const script=document.querySelector('script[src*="assets/javascripts/bundle"]');const link=document.querySelector('link[href*="assets/stylesheets/main"]')||document.querySelector('link[href*="assets/stylesheets"]')||document.querySelector('script[src*="assets/javascripts"]');const attr=script?script.getAttribute("src"):(link?(link.getAttribute("href")||link.getAttribute("src")):null);const assetUrl=attr?new URL(attr,document.baseURI):new URL(document.baseURI);const pathname=assetUrl.pathname||"/";const idx=pathname.indexOf("/assets/");if(idx>=0){return assetUrl.origin+pathname.slice(0,idx+1);}
const base=new URL(document.baseURI);if(!base.pathname.endsWith("/"))base.pathname+="/";return base.origin+base.pathname;}
function splitSegments(rel){return String(rel||"").split("/").filter(Boolean);}
function cleanTitle(text){return String(text||"").replace(/\s*¶\s*$/u,"").replace(/\u00B6/g,"").replace(/\s+/g," ").trim();}
function unitNounFromType(type){return String(type||"lecture").toLowerCase()==="week"?"Week":"Lecture";}
function unitGroupPrefix(type){return String(type||"lecture").toLowerCase()==="week"?"W":"L";}
function unitTypeFromGroupId(groupId){return/^W/i.test(String(groupId||""))?"week":"lecture";}
function courseKeyFromScope(scope){return scope&&scope.yearSeg&&scope.courseSeg?scope.yearSeg+"/"+scope.courseSeg:"";}
function globalYearStorageKey(yearSeg){return String(yearSeg||"").replace(/^\/+/,"").replace(/\/+$/,"").trim();}
function getPrimarySidebar(){return document.querySelector(".md-sidebar--primary");}
function directNavLink(item){if(!item||!item.querySelector)return null;return item.querySelector(':scope > a.md-nav__link, :scope > label.md-nav__link, :scope > .md-nav__link');}
function directChildList(node){if(!node||!node.querySelector)return null;return node.querySelector(':scope > nav.md-nav > .md-nav__list');}
function isRealConceptRel(rel,coursePrefix){const r=String(rel||"").replace(/^\/+/,"").replace(/\/+$/,"");if(!r||!coursePrefix)return false;const prefix=String(coursePrefix||"").replace(/^\/+/,"").replace(/\/+$/,"")+"/";if(!r.startsWith(prefix))return false;const tail=r.slice(prefix.length);if(!tail||!tail.trim())return false;if(/^index(?:\.html?)?$/i.test(tail))return false;if(/\//.test(tail))return false;return true;}
function alphaCompare(a,b){const leftTitle=String(a&&a.title||"");const rightTitle=String(b&&b.title||"");const byTitle=leftTitle.localeCompare(rightTitle,undefined,{sensitivity:"base"});if(byTitle!==0)return byTitle;const leftRel=String(a&&a.rel||"");const rightRel=String(b&&b.rel||"");const byRel=leftRel.localeCompare(rightRel,undefined,{sensitivity:"base"});if(byRel!==0)return byRel;return Number(a&&a.baseIndex||0)-Number(b&&b.baseIndex||0);}
function withTimeout(promise,ms){return new Promise(function(resolve,reject){let done=false;const timer=window.setTimeout(function(){if(done)return;done=true;reject(new Error("timeout"));},Math.max(1,Number(ms)||0));promise.then(function(value){if(done)return;done=true;window.clearTimeout(timer);resolve(value);},function(err){if(done)return;done=true;window.clearTimeout(timer);reject(err);});});}
function groupStorageKey(scope,groupId){const year=scope&&scope.yearSeg?scope.yearSeg:"";const course=scope&&scope.courseSeg?scope.courseSeg:"";return[scope&&scope.kind||"",year,course,groupId||""].join("|");}
function isSameCourseScope(left,right){return!!(left&&right&&left.kind==="course"&&right.kind==="course"&&left.yearSeg===right.yearSeg&&left.courseSeg===right.courseSeg);}
function unifiedCloneUsesYearOverview(root){if(!(root instanceof HTMLElement))return false;return!!root.querySelector('[data-msb-clone-list-kind="course-overview"]');}
function blockLabelFromIndex(index){const n=Math.floor(index/2)+1;const suffix=index%2===0?"A":"B";return"Block "+n+suffix;}
function isMobileViewport(){try{return!!(window.matchMedia&&window.matchMedia("(max-width: 76.1875em)").matches);}catch(_){return false;}}
function drawerToggle(){return document.querySelector('input[data-md-toggle="drawer"], input#__drawer');}
function pageScrollXNow(){try{return Math.max(0,Number(window.scrollX)||0,Number(window.pageXOffset)||0,Number(document.documentElement&&document.documentElement.scrollLeft)||0,Number(document.body&&document.body.scrollLeft)||0);}catch(_){return 0;}}
function pageScrollYNow(){try{return Math.max(0,Number(window.scrollY)||0,Number(window.pageYOffset)||0,Number(document.documentElement&&document.documentElement.scrollTop)||0,Number(document.body&&document.body.scrollTop)||0);}catch(_){return 0;}}
function cssPx(value){const n=Number(value);if(!Number.isFinite(n))return'0px';return(Math.round(n*1000)/1000)+'px';}
function isIOSWebKitMobile(){try{const ua=String(navigator.userAgent||"");const platform=String(navigator.platform||"");const isiOS=/iP(?:hone|ad|od)/i.test(ua)||(/Mac/i.test(platform)&&Number(navigator.maxTouchPoints||0)>1);if(!isiOS)return false;return true;}catch(_){return false;}}
function unifiedDrawerMotionEnabled(){try{if(window.MkSiteMotion&&typeof window.MkSiteMotion.isEnabled==='function'){return!!window.MkSiteMotion.isEnabled();}}catch(_){}
try{return!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches);}catch(_){return true;}}
function elementTopInScrollContent(el,scrollWrap){if(!(el instanceof HTMLElement)||!(scrollWrap instanceof HTMLElement))return 0;try{const er=el.getBoundingClientRect();const wr=scrollWrap.getBoundingClientRect();if(er&&wr&&Number.isFinite(er.top)&&Number.isFinite(wr.top)){return(Number(scrollWrap.scrollTop)||0)+(er.top-wr.top);}}catch(_){}
let y=0;let cur=el;let guard=0;while(cur&&cur!==scrollWrap&&guard<80){y+=Number(cur.offsetTop)||0;cur=cur.offsetParent instanceof HTMLElement?cur.offsetParent:cur.parentElement;guard+=1;if(cur&&!scrollWrap.contains(cur))break;}
return y;}
function unifiedCloneListScroller(clone){if(!(clone instanceof HTMLElement))return null;const scroller=clone.querySelector(':scope > .msb-unified-list-scroll');return scroller instanceof HTMLElement?scroller:clone;}
function visualViewportMetrics(){const vv=window.visualViewport;if(vv){const left=Number(vv.offsetLeft)||0;const top=Number(vv.offsetTop)||0;const width=Number(vv.width)||window.innerWidth||0;const height=Number(vv.height)||window.innerHeight||0;const right=left+width;const bottom=top+height;const layoutBottomGap=Math.max(0,Math.round((window.innerHeight||0)-bottom));return{left,top,width,height,right,bottom,layoutBottomGap};}
return{left:0,top:0,width:window.innerWidth||0,height:window.innerHeight||0,right:window.innerWidth||0,bottom:window.innerHeight||0,layoutBottomGap:0};}
function desktopScrollbarWidth(root){if(root instanceof HTMLElement){try{const cs=window.getComputedStyle(root);const raw=cs.getPropertyValue('--msb-desktop-scrollbar-width')||cs.width;const n=parseFloat(raw);if(Number.isFinite(n)&&n>0)return n;}catch(_){}
try{const rect=root.getBoundingClientRect();if(rect&&rect.width>0)return rect.width;}catch(_){}}
return 9;}
function sidebarCacheEnabled(){try{if(localStorage.getItem("mk_enable_sidebar_cache")!=="1")return false;}catch(_){return false;}
try{return!!window.sessionStorage;}catch(_){return false;}}
function sidebarCacheCourseKey(scope){if(!scope||scope.kind!=="course"||!scope.yearSeg||!scope.courseSeg)return"";return scope.yearSeg+"/"+scope.courseSeg;}
function currentCourseBarChevronSvg(className){const cls=className?' '+className:'';return'<svg class="ccb-chevron'+cls+'" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 3.5L10.5 8 6 12.5"></path></svg>';}
function swallowMobileDrawerBackdropEvent(event){if(!event)return;try{if(typeof event.preventDefault==='function')event.preventDefault();}catch(_){}
try{if(typeof event.stopImmediatePropagation==='function')event.stopImmediatePropagation();}catch(_){}
try{if(typeof event.stopPropagation==='function')event.stopPropagation();}catch(_){}}
window.MkSB=Object.assign(window.MkSB||{},{IDS,STORAGE_KEYS,ATTR,CLS,MODE,GLOBAL_EXISTING_LINK_SELECTOR,GLOBAL_YEAR_LINK_SELECTOR,SIDEBAR_CACHE_PREFIX,html,asArray,isElement,clamp,cssEscape,safePath,asStringList,isTouchLikeViewport,siteRootUrl,splitSegments,cleanTitle,unitNounFromType,unitGroupPrefix,unitTypeFromGroupId,courseKeyFromScope,globalYearStorageKey,getPrimarySidebar,directNavLink,directChildList,isRealConceptRel,alphaCompare,withTimeout,groupStorageKey,isSameCourseScope,unifiedCloneUsesYearOverview,blockLabelFromIndex,isMobileViewport,drawerToggle,pageScrollXNow,pageScrollYNow,cssPx,isIOSWebKitMobile,unifiedDrawerMotionEnabled,elementTopInScrollContent,unifiedCloneListScroller,visualViewportMetrics,desktopScrollbarWidth,sidebarCacheEnabled,sidebarCacheCourseKey,currentCourseBarChevronSvg,swallowMobileDrawerBackdropEvent});})();