(function(){'use strict';const UI='[data-wiki-explain-ui]';const CONTROL='button,a[href],input,select,textarea,summary,[role="button"],[role="tab"],[role="menuitem"],[role="switch"],[role="checkbox"],[role="slider"]';const SEMANTIC=CONTROL+',[role="meter"],meter,progress,[data-explain],h1,h2,h3,h4,p,li,dt,dd,th,td,figcaption,img,svg,canvas';const clean=value=>String(value||'').replace(/\s+/g,' ').trim().slice(0,180);const matches=(el,selector)=>{try{return el.matches(selector);}catch(_){return false;}};const closest=(el,selector)=>{try{return el.closest(selector);}catch(_){return null;}};const query=(el,selector)=>{try{return el.querySelectorAll(selector);}catch(_){return[];}};function label(el){const explicit=el.getAttribute('aria-label')||el.getAttribute('title')||el.getAttribute('alt');if(explicit)return clean(explicit);const ids=(el.getAttribute('aria-labelledby')||'').split(/\s+/).filter(Boolean);const labelled=ids.map(id=>el.ownerDocument?.getElementById(id)?.textContent||'').join(' ');if(clean(labelled))return clean(labelled);if(matches(el,'input,textarea,select,[contenteditable="true"]')){return clean(el.labels?.[0]?.textContent)||'Input field';}
return clean(el.innerText||el.textContent).replace(/¶/g,'').trim();}
function distance(from,to){let d=0;for(let e=from;e;e=e.parentElement,d++)if(e===to)return d;return 1000;}
function allowKey(event){if(['Tab','Shift','Control','Alt','Meta'].includes(event.key))return true;return!!(event.ctrlKey||event.metaKey)&&['f','l','r','t','w','+','-','0'].includes(event.key.toLowerCase());}
function visible(el){if(!el?.isConnected||closest(el,'[hidden],[inert],[aria-hidden="true"],details:not([open]) > :not(summary)'))return false;const css=getComputedStyle(el);return css.display!=='none'&&css.visibility!=='hidden'&&css.opacity!=='0'&&!!el.getClientRects().length;}
function semanticTarget(hit){if(!hit||hit.nodeType!==1)hit=hit?.parentElement;if(!hit||closest(hit,UI))return null;return closest(hit,CONTROL+',[role="meter"],meter,progress,[data-explain]')||closest(hit,SEMANTIC)||hit;}
function pointerTarget(event,doc){return doc.elementFromPoint?.(event.clientX,event.clientY)||event.target;}
function labelledControl(hit){const wrapper=closest(hit,'label'),control=wrapper?.control;if(!control)return null;const action=closest(hit,CONTROL);if(action&&action!==control)return null;return{wrapper,control,region:wrapper.contains(control)?wrapper:control};}
function fallback(target){const name=label(target),tag=target.tagName.toLowerCase(),role=target.getAttribute('role');if(matches(target,'input,textarea,select,[contenteditable="true"]')){const type=target.getAttribute('type')||'';if(type==='password')return{title:name||'Private credential',text:'Enter the credential requested by this form. Explain mode never reads or displays what you type here.'};if(type==='checkbox'||type==='radio')return{title:name||'Selection',text:type==='radio'?'Select one option in this group.':'Turn this option on or off.'};if(type==='range')return{title:name||'Adjustment slider',text:'Drag or use arrow keys to adjust the setting shown beside the slider.'};return{title:name||'Input field',text:tag==='select'?'Choose one of the options in this list.':'Enter the information requested by the field label.'};}
if(matches(target,'summary'))return{title:name||'Expandable section',text:'Expand or collapse the contents of this section.'};if(tag==='a'&&target.hasAttribute('href')){const href=target.getAttribute('href')||'';if(closest(target,'article')&&/^#/.test(href))return{title:name||'Section link',text:'Jump to this section on the current page.'};if(/^(mailto:|tel:)/i.test(href))return{title:name||'Contact link',text:'Open your device’s contact application for this address.'};return{title:name||'Page link',text:'Open this linked page to continue reading.'};}
if(role==='tab')return{title:name||'Panel tab',text:'Switch the contents of this panel to the named section. Other tabs offer different views of the same workspace.'};if(matches(target,'button,[role="button"],[role="menuitem"]'))return{title:name||'Action control',text:(target.disabled||target.getAttribute('aria-disabled')==='true')?'This action is currently unavailable. Check its nearby status or requirements.':'No detailed explanation is available for this control yet.'};if(matches(target,'[role="meter"],meter,progress'))return{title:name||'Progress indicator',text:'A summary of the measure named beside this indicator. Read its label for the scope; different percentages on the Wiki represent different measures, not course grades.'};if(/^h[1-6]$/.test(tag))return{title:name||'Section heading',text:'The topic of the section directly below.'};if(matches(target,'img,svg,canvas'))return{title:name||'Illustration',text:'An illustration of the surrounding topic. Refer to its caption for context.'};if(closest(target,'.mk-comments,.mk-comment,.mk-local-activity-modal,.mk-public-profile-modal'))return{title:'Panel content',text:'Information supplied by this panel or its contributor.'};if(closest(target,'article,.md-typeset'))return{title:'Reading area',text:'Published notes and examples. Mathematical quantities are defined in the surrounding text.'};return{title:'Page region',text:'Select a nearby control or indicator for a specific explanation.'};}
function resolve(hit,rules=[],guides=[],pathname=''){if(!hit||closest(hit,UI))return null;const association=labelledControl(hit);const target=semanticTarget(association?.control||hit);if(!target)return null;const candidates=[],actionable=matches(target,CONTROL);for(const rule of rules){const direct=closest(hit,rule.selector);const match=direct||(association&&closest(association.control,rule.selector));if(!match||(actionable&&match!==target&&!target.contains(match)))continue;const title=typeof rule.title==='function'?rule.title(match):rule.title;const text=typeof rule.text==='function'?rule.text(match):rule.text;const associated=association&&match===association.control;const region=associated?association.region:match;if(title&&text)candidates.push({target:region,title,text,kind:'Feature explanation',score:distance(hit,associated?association.wrapper:match)*100-(Number(rule.priority)||0),id:rule.id});}
for(const entry of guides){if(entry.path){try{if(!new RegExp(entry.path).test(pathname))continue;}catch(_){continue;}}
const surface=closest(hit,entry.surface||'main');if(!surface||(entry.when&&!entry.when(surface)))continue;for(const step of entry.steps||[]){if(!step.target||typeof step.text!=='string')continue;const match=closest(hit,step.target)||(association&&closest(association.control,step.target));if(!match||!surface.contains(match)||(actionable&&match!==target&&!target.contains(match)))continue;const associated=association&&match===association.control;candidates.push({target:associated?association.region:match,title:step.title,text:step.text,kind:'Feature explanation',score:distance(hit,associated?association.wrapper:match)*100+20,id:entry.id});}}
if(candidates.length)return candidates.sort((a,b)=>a.score-b.score)[0];return{...fallback(target),target:association?.region||target,kind:'About this item',id:'semantic'};}
function fit(view,size,target){const pad=12,width=Math.min(size.width,view.width-pad*2),height=Math.min(size.height,view.height-pad*2-56);const clamp=(n,lo,hi)=>Math.max(lo,Math.min(n,hi));const box=(x,y)=>({x:clamp(x,pad,view.width-width-pad),y:clamp(y,pad,view.height-height-pad-56)});if(!target)return box(view.width-width-pad,view.height-height-68);const below=box((target.left+target.right-width)/2,target.bottom+16),above=box(pad,target.top-height-16);const sides=[box(target.right+16,target.top),box(target.left-width-16,target.top)];const list=view.height<500?[below,above,...sides]:[...sides,below,above];const overlap=p=>Math.max(0,Math.min(p.x+width,target.right)-Math.max(p.x,target.left))*Math.max(0,Math.min(p.y+height,target.bottom)-Math.max(p.y,target.top));return list.sort((a,b)=>overlap(a)-overlap(b))[0];}
function cardHeight(view,target){const full=Math.max(80,view.height-84);if(view.height>=500||!target)return full;const below=view.height-target.bottom-84,above=target.top-28;const room=Math.max(below,above);return room>=150?Math.min(full,room):full;}
if(typeof module!=='undefined'&&module.exports)module.exports={clean,label,semanticTarget,pointerTarget,fallback,resolve,fit,cardHeight,allowKey};if(typeof window==='undefined'||!window.document||window.MkExplain)return;const SURFACES='dialog,[role="dialog"][aria-modal="true"],#lp-map-modal,#lp-h1sg-modal,#lp-gps-modal,.mk-rt-panel,#mk-quick-shop-menu,#mk-startup-menu';let root,toggle,hint,card,outline,live,active=false,selected=null,previous=null,pointer=null,frame=0,timer=0,observer,scrollExit=false,scrollExitUntil=0;let menu=null,menuOpen=false;const merged=()=>{try{return!!window.MkGuides?.launch&&matchMedia('(max-width: 700px)').matches;}catch(_){return false;}};const watched=new WeakSet();function node(tag,cls,text){const el=document.createElement(tag);if(cls)el.className=cls;if(text)el.textContent=text;return el;}
function button(text,action){const el=node('button','wx-button',text);el.type='button';el.dataset.wxAction=action;return el;}
function host(){const surfaces=[...query(document,SURFACES)].filter(el=>!closest(el,UI+',[data-wiki-guide-ui]'));if(observer)for(const el of surfaces)if(!watched.has(el)){watched.add(el);observer.observe(el,{childList:true,attributes:true,attributeFilter:['hidden','aria-hidden','open','style','class']});}
return surfaces.filter(visible).pop()||document.body;}
function mount(){if(!document.body)return;if(!root){root=node('div','wx-root');root.id='wiki-explain-root';root.dataset.wikiExplainUi='';root.setAttribute('popover','manual');toggle=button('Explain','toggle');toggle.classList.add('wx-toggle');toggle.setAttribute('aria-label','Explain this screen');toggle.setAttribute('aria-pressed','false');const icon=document.createElementNS('http://www.w3.org/2000/svg','svg');icon.setAttribute('viewBox','0 0 24 24');icon.setAttribute('aria-hidden','true');const circle=document.createElementNS(icon.namespaceURI,'circle');circle.setAttribute('cx','12');circle.setAttribute('cy','12');circle.setAttribute('r','9');const path=document.createElementNS(icon.namespaceURI,'path');path.setAttribute('d','M9.6 9a2.5 2.5 0 0 1 4.8 1c0 1.6-2.4 1.8-2.4 3.5M12 17h.01');icon.append(circle,path);toggle.prepend(icon);const caption=node('span','wx-toggle-label','Explain');toggle.lastChild.textContent='';toggle.append(caption);hint=node('div','wx-hint','Select an item to explain.');hint.hidden=true;outline=node('div','wx-outline');outline.hidden=true;outline.setAttribute('aria-hidden','true');card=node('section','wx-card');card.hidden=true;card.setAttribute('role','dialog');card.setAttribute('aria-modal','false');card.setAttribute('aria-labelledby','wx-title');live=node('span','wx-sr');live.setAttribute('role','status');live.setAttribute('aria-live','polite');root.append(outline,card,hint,toggle,live);}
syncToggle();const parent=host();if(root.parentNode!==parent){try{root.hidePopover();}catch(_){}parent.append(root);}
root.dataset.wxMap=String(!!closest(parent,'#lp-map-modal,#lp-h1sg-modal,#lp-gps-modal,.lp-modal'));try{if(!root.matches(':popover-open'))root.showPopover();}catch(_){}}
function reposition(){frame=0;if(!root)return;const vv=window.visualViewport,view={width:vv?.width||innerWidth,height:vv?.height||innerHeight},ox=vv?.offsetLeft||0,oy=vv?.offsetTop||0;if(card.hidden)return;let rect=selected?.target?.isConnected?selected.target.getBoundingClientRect():null;if(!rect||rect.width<=0||rect.height<=0){outline.hidden=true;rect=null;}
else{const left=Math.max(ox+3,rect.left-4),top=Math.max(oy+3,rect.top-4),right=Math.min(ox+view.width-3,rect.right+4),bottom=Math.min(oy+view.height-3,rect.bottom+4);outline.hidden=right<=left||bottom<=top;if(!outline.hidden)Object.assign(outline.style,{left:left+'px',top:top+'px',width:right-left+'px',height:bottom-top+'px'});rect={left:left-ox,right:right-ox,top:top-oy,bottom:bottom-oy};}
card.style.maxHeight=cardHeight(view,rect)+'px';const pos=fit(view,{width:card.offsetWidth,height:card.offsetHeight},rect);Object.assign(card.style,{left:pos.x+ox+'px',top:pos.y+oy+'px'});}
function schedule(){if(active&&!frame)frame=requestAnimationFrame(reposition);}
function syncToggle(){if(!toggle)return;root.toggleAttribute('data-wx-with-guides',!!window.MkGuides?.launch);const help=merged()&&!active;toggle.setAttribute('aria-label',active?'Exit explain mode':help?'Help for this screen':'Explain this screen');if(help){toggle.setAttribute('aria-haspopup','menu');toggle.setAttribute('aria-expanded',String(menuOpen));}
else{toggle.removeAttribute('aria-haspopup');toggle.removeAttribute('aria-expanded');}
toggle.classList.toggle('wx-toggle--hint',help&&!!window.MkGuides?.hint);}
function openMenu(){if(!menu){menu=node('div','wx-menu');menu.setAttribute('role','menu');menu.hidden=true;const guide=button('Guide for this screen','menu-guide'),explain=button('Explain this screen','menu-explain');guide.append(node('span','wx-menu-new','New'));for(const item of[guide,explain])item.setAttribute('role','menuitem');menu.append(guide,explain);root.append(menu);}
menu.querySelector('.wx-menu-new').hidden=!window.MkGuides?.hint;menu.hidden=false;menuOpen=true;toggle.setAttribute('aria-expanded','true');const r=toggle.getBoundingClientRect(),width=menu.offsetWidth,height=menu.offsetHeight;const top=r.top>height+20?r.top-height-8:r.bottom+8;Object.assign(menu.style,{left:Math.max(12,Math.min(innerWidth-width-12,r.right-width))+'px',top:top+'px'});menu.querySelector('button').focus({preventScroll:true});}
function closeMenu(restoreFocus){if(!menuOpen)return;const strandedFocus=menu.contains(document.activeElement);menuOpen=false;menu.hidden=true;toggle.setAttribute('aria-expanded','false');if(restoreFocus||strandedFocus)toggle.focus({preventScroll:true});}
function dismissCard(){selected=null;card.hidden=true;outline.hidden=true;hint.hidden=!active;toggle.hidden=false;}
function setActive(value,restoreFocus=true){mount();closeMenu(false);if(active===value)return;active=value;root.dataset.wxActive=String(active);document.documentElement.toggleAttribute('data-wiki-explaining',active);toggle.setAttribute('aria-pressed',String(active));toggle.querySelector('.wx-toggle-label').textContent=active?'Exit explain':'Explain';syncToggle();dismissCard();if(active){scrollExit=false;pointer=null;previous=document.activeElement;window.MkGuides?.suspend('explain');live.textContent='Explain mode on. Select an item, or focus it and press Enter. Escape exits.';}
else{window.MkGuides?.resume('explain',{quiet:true});live.textContent='Explain mode off.';if(restoreFocus&&previous?.isConnected&&!closest(previous,UI))previous.focus?.({preventScroll:true});}}
function pick(hit){const result=resolve(hit,window.MkExplainContent||[],[...(window.MkGuidePages||[]),...(window.MkGuideAccount||[])],location.pathname);if(!result)return;selected=result;mount();card.replaceChildren();hint.hidden=true;const title=node('h2','',result.title);title.id='wx-title';title.tabIndex=-1;const text=node('p','wx-description',result.text);const foot=node('div','wx-card-foot');foot.append(button('Exit explanation','exit'));card.append(title,text,foot);card.hidden=false;toggle.hidden=true;reposition();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)card.animate?.([{opacity:0,transform:'translateY(7px) scale(.98)'},{opacity:1,transform:'none'}],{duration:190,easing:'cubic-bezier(.2,.7,.2,1)'});title.focus({preventScroll:true});live.textContent=result.title.replace(/[.!?]+$/,'')+'. '+result.text;}
const stop=event=>{if(event.cancelable)event.preventDefault();event.stopImmediatePropagation();};function own(event){return!!closest(event.target,UI);}
function exitForScroll(event){if(!active||own(event))return;scrollExit=true;scrollExitUntil=performance.now()+350;setActive(false,false);}
function onClick(event){if(scrollExit&&!own(event)){scrollExit=false;if(performance.now()<scrollExitUntil){stop(event);return;}}
if(own(event)){const action=closest(event.target,'[data-wx-action]')?.dataset.wxAction;if(!action)return;stop(event);if(action==='toggle'){if(!active&&merged()){if(menuOpen)closeMenu(true);else openMenu();}else setActive(!active);}
else if(action==='menu-guide'){closeMenu(true);window.MkGuides?.launch?.();}
else if(action==='menu-explain'){closeMenu(true);setActive(true);}
else if(action==='exit')setActive(false);return;}
if(menuOpen)closeMenu(false);if(!active)return;stop(event);if(pointer?.moved||pointer?.selected){pointer=null;return;}
pick(pointer?.hit||event.target);pointer=null;}
const mountSoon=()=>{try{requestAnimationFrame(mount);}catch(_){mount();}};function start(){window.addEventListener('click',onClick,true);window.addEventListener('pointerdown',event=>{if(own(event)){event.stopImmediatePropagation();return;}
if(!active){if(scrollExit&&performance.now()<scrollExitUntil){stop(event);return;}
scrollExit=false;clearTimeout(timer);timer=setTimeout(mount,100);return;}
pointer={x:event.clientX,y:event.clientY,moved:false,hit:pointerTarget(event,document)};stop(event);},{capture:true,passive:false});window.addEventListener('pointermove',event=>{if(!active||own(event))return;if(pointer&&Math.hypot(event.clientX-pointer.x,event.clientY-pointer.y)>9)pointer.moved=true;event.stopImmediatePropagation();},{capture:true,passive:true});for(const type of['mousedown','mouseup','pointerup','dblclick','contextmenu','touchstart','touchend'])window.addEventListener(type,event=>{if(own(event)){event.stopImmediatePropagation();return;}
if(!active)return;if(type==='pointerup'&&pointer&&!pointer.moved&&semanticTarget(labelledControl(pointer.hit)?.control||pointer.hit)?.disabled){pick(pointer.hit);pointer.selected=true;}
if(type.startsWith('touch'))event.stopImmediatePropagation();else stop(event);},{capture:true,passive:type.startsWith('touch')});for(const type of['mouseover','pointerover','mouseenter','pointerenter','focus','focusin'])window.addEventListener(type,event=>{if(active&&!own(event))event.stopImmediatePropagation();},true);window.addEventListener('mousemove',event=>{if(active&&!own(event))event.stopImmediatePropagation();},{capture:true,passive:true});window.addEventListener('touchmove',event=>{if(active&&!own(event)){exitForScroll(event);event.stopImmediatePropagation();}},{capture:true,passive:true});window.addEventListener('keydown',event=>{if(menuOpen&&event.key==='Escape'){stop(event);closeMenu(true);return;}
if(menuOpen&&['ArrowDown','ArrowUp','Home','End'].includes(event.key)){stop(event);const items=[...menu.querySelectorAll('[role="menuitem"]')];const current=items.indexOf(document.activeElement);const next=event.key==='Home'?0:event.key==='End'?items.length-1:(current+(event.key==='ArrowDown'?1:items.length-1))%items.length;items[next]?.focus({preventScroll:true});return;}
if(!active)return;if(event.key==='Escape'){stop(event);setActive(false);return;}
if(!own(event)&&['PageDown','PageUp','Home','End','ArrowDown','ArrowUp'].includes(event.key)&&!closest(event.target,CONTROL)){exitForScroll(event);return;}
if(!own(event)&&(event.key==='Enter'||event.key===' ')){stop(event);pick(event.target);}
else if(!own(event)&&!allowKey(event))stop(event);},true);window.addEventListener('keyup',event=>{if(active&&!own(event)&&!allowKey(event))stop(event);},true);window.addEventListener('focusin',event=>{if(menuOpen&&event.target!==toggle&&!menu?.contains(event.target))closeMenu(false);},true);for(const type of['beforeinput','paste','cut','drop'])window.addEventListener(type,event=>{if(active&&!own(event))stop(event);},true);window.addEventListener('wheel',event=>{if(!active||own(event))return;const input=closest(event.target,'input,select,textarea');exitForScroll(event);if(input)stop(event);},{capture:true,passive:false});window.addEventListener('scroll',event=>{if(menuOpen&&!own(event))closeMenu(false);exitForScroll(event);},{capture:true,passive:true});window.addEventListener('resize',()=>{closeMenu(false);syncToggle();schedule();},{passive:true});window.addEventListener('mk:guides-hint',syncToggle);window.visualViewport?.addEventListener('resize',schedule,{passive:true});window.visualViewport?.addEventListener('scroll',exitForScroll,{passive:true});observer=new MutationObserver(records=>{if(!records.some(record=>!closest(record.target,UI)&&(record.type!=='childList'||[...record.addedNodes,...record.removedNodes].some(el=>el.nodeType===1&&!matches(el,UI)))))return;clearTimeout(timer);timer=setTimeout(()=>{mount();if(selected&&!selected.target.isConnected)dismissCard();schedule();},100);});observer.observe(document.body,{childList:true});mountSoon();window.addEventListener('pagehide',()=>{if(active)setActive(false);});if(window.document$?.subscribe)window.document$.subscribe(()=>{if(active)setActive(false);mountSoon();});}
window.MkExplain={open:()=>setActive(true),close:()=>setActive(false),get active(){return active;}};if(document.body)start();else document.addEventListener('DOMContentLoaded',start,{once:true});})();