(function(){"use strict";function themeConnectionGeometry(points,width,height){const names=["calculus","probability","algebra","models"];if(!(width>0&&height>0)||!Number.isFinite(width+height)||names.some(name=>!points[name]||!Number.isFinite(points[name].x+points[name].y)))return null;const n=value=>Math.round(value*100)/100;const xy=point=>n(point.x)+" "+n(point.y);const hub={x:width*.51,y:height*.51};const pairs=[["calculus","models"],["algebra","probability"],["calculus","algebra"],["probability","models"]];return{hub,paths:pairs.map(([from,to],index)=>{const a=points[from],b=points[to];const d=index<2?`M ${xy(a)} Q ${n(hub.x)} ${n(a.y)} ${xy(hub)} Q ${n(hub.x)} ${n(b.y)} ${xy(b)}`:`M ${xy(a)} Q ${n(width * (index === 2 ? .12 : .9))} ${n((a.y + b.y) / 2)} ${xy(b)}`;return{from,to,d};})};}
function mountThemeConnections(root){const scene=root.querySelector(".wh-scene"),html=document.documentElement;if(!scene||!html||typeof document.createElementNS!=="function")return function(){};const names=["calculus","probability","algebra","models"];const labels=names.map(name=>scene.querySelector(".wh-node-"+name));if(labels.some(node=>!node))return function(){};let svg=null,paths=[],dot=null,frame=0,stopped=false,lastGeometry="";const ns="http://www.w3.org/2000/svg";function element(tag,attributes){const node=document.createElementNS(ns,tag);Object.entries(attributes).forEach(([key,value])=>node.setAttribute(key,value));return node;}
function remove(){if(svg)svg.remove();svg=null;paths=[];dot=null;lastGeometry="";}
function draw(){frame=0;if(stopped||!root.isConnected)return;if(!html.hasAttribute("data-mk-image-interface-theme")){remove();return;}
const width=scene.clientWidth,height=scene.clientHeight;const points=Object.fromEntries(labels.map((node,i)=>[names[i],{x:node.offsetLeft+node.offsetWidth/2,y:node.offsetTop+node.offsetHeight/2}]));const geometry=themeConnectionGeometry(points,width,height);if(!geometry)return;const key=JSON.stringify([width,height,geometry]);if(key===lastGeometry)return;if(!svg){svg=element("svg",{class:"wh-theme-links","aria-hidden":"true",focusable:"false",preserveAspectRatio:"none"});paths=geometry.paths.map(link=>{const halo=element("path",{class:"wh-link-halo","data-from":link.from,"data-to":link.to});const ink=element("path",{class:"wh-link-ink","data-from":link.from,"data-to":link.to});svg.append(halo,ink);return[halo,ink];});dot=element("circle",{class:"wh-link-hub",r:"4"});svg.append(dot);scene.append(svg);}
svg.setAttribute("viewBox",`0 0 ${width} ${height}`);geometry.paths.forEach((link,i)=>paths[i].forEach(path=>path.setAttribute("d",link.d)));dot.setAttribute("cx",geometry.hub.x);dot.setAttribute("cy",geometry.hub.y);lastGeometry=key;}
function schedule(){if(!stopped&&!frame)frame=requestAnimationFrame(draw);}
const resize=typeof ResizeObserver==="function"?new ResizeObserver(schedule):null;if(resize){resize.observe(scene);labels.forEach(node=>resize.observe(node));}
const themes=typeof MutationObserver==="function"?new MutationObserver(schedule):null;if(themes)themes.observe(html,{attributes:true,attributeFilter:["data-mk-image-interface-theme"]});window.addEventListener("resize",schedule,{passive:true});draw();return function(){stopped=true;if(frame)cancelAnimationFrame(frame);if(resize)resize.disconnect();if(themes)themes.disconnect();window.removeEventListener("resize",schedule);remove();};}
if(typeof module!=="undefined"&&module.exports)module.exports={themeConnectionGeometry,mountThemeConnections};if(typeof document==="undefined")return;let cleanup=function(){};function boot(){cleanup();const root=document.querySelector("[data-wiki-home]");if(!root)return;const abort=new AbortController();const removeThemeConnections=mountThemeConnections(root);const on=(target,event,callback,options)=>target.addEventListener(event,callback,Object.assign({},options,{signal:abort.signal}));const hero=root.querySelector(".wh-hero"),button=root.querySelector("[data-wh-motion]");const reduced=window.matchMedia("(prefers-reduced-motion: reduce), (max-width: 700px)");let paused=false,frame=0;function motionBlocked(){return reduced.matches||document.documentElement.classList.contains("mk-motion-off")||!!(window.MkSiteMotion&&window.MkSiteMotion.isReduced());}
function draw(){frame=0;if(!root.isConnected||document.hidden||motionBlocked()||paused)return;const box=hero.getBoundingClientRect();if(box.bottom<0||box.top>window.innerHeight)return;hero.style.setProperty("--wh-scroll",Math.round(Math.max(0,Math.min(450,-box.top)))+"px");}
function schedule(){if(!frame&&!motionBlocked()&&!paused&&!document.hidden)frame=requestAnimationFrame(draw);}
function updateMotion(){button.hidden=motionBlocked();button.setAttribute("aria-pressed",String(paused));button.textContent=paused?"Resume depth effect":"Pause depth effect";if(frame)cancelAnimationFrame(frame);frame=0;if(paused||motionBlocked())hero.style.setProperty("--wh-scroll","0px");else schedule();}
on(button,"click",function(){paused=!paused;updateMotion();});on(window,"scroll",schedule,{passive:true});on(window,"resize",schedule,{passive:true});on(document,"visibilitychange",schedule);on(reduced,"change",updateMotion);on(window,"mk:site-motion-change",updateMotion);on(window,"mk:motionchange",updateMotion);updateMotion();cleanup=function(){abort.abort();removeThemeConnections();if(frame)cancelAnimationFrame(frame);};}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();if(typeof document$!=="undefined")document$.subscribe(boot);})();